-- Enums (shared across domains)
CREATE TYPE "AccountKind" AS ENUM ('COMPANY_STAFF', 'END_CLIENT', 'PLATFORM_ADMIN');
CREATE TYPE "CompanyRole" AS ENUM ('OWNER', 'MANAGER', 'MEMBER');
CREATE TYPE "CompanyMemberStatus" AS ENUM ('PENDING', 'ACTIVE', 'LEFT');
CREATE TYPE "InvitationStatus" AS ENUM ('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED');
CREATE TYPE "VerificationStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE "PackageStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');
CREATE TYPE "PackagePaymentMode" AS ENUM ('PREPAID', 'ON_SITE');
CREATE TYPE "PackageBookingStatus" AS ENUM ('PENDING_PAYMENT', 'CONFIRMED', 'CANCELLED', 'COMPLETED');
CREATE TYPE "CompanySubscriptionPlan" AS ENUM ('FREE', 'PRO', 'BUSINESS');
CREATE TYPE "CompanySubscriptionStatus" AS ENUM ('TRIAL', 'ACTIVE', 'SUSPENDED', 'EXPIRED');
CREATE TYPE "InterventionStatus" AS ENUM ('NEW', 'SCHEDULED', 'EN_ROUTE', 'IN_PROGRESS', 'COMPLETED', 'INVOICED', 'PAID', 'CANCELLED');
CREATE TYPE "QuoteStatus" AS ENUM ('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'CONVERTED');
CREATE TYPE "InvoicePaymentStatus" AS ENUM ('UNPAID', 'PAID', 'OVERDUE');
CREATE TYPE "ConsentType" AS ENUM ('TEAM_DATA_PROCESSING', 'PORTAL_DATA_PROCESSING');
CREATE TYPE "PaymentProductType" AS ENUM ('COMPANY_SUBSCRIPTION', 'PACKAGE_PREPAID');
