import type { BlueprintPricingRule, EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

function withQtyExplanations(rules: BlueprintPricingRule[]): BlueprintPricingRule[] {
  return rules.map((rule) => ({
    ...rule,
    explanation: {
      template: rule.wastePct
        ? `${rule.qtyKey}: {${rule.qtyKey}} ${rule.unit} + ${rule.wastePct}% pierderi × {unitPrice} MDL/${rule.unit}`
        : `${rule.qtyKey}: {${rule.qtyKey}} ${rule.unit} × {unitPrice} MDL/${rule.unit}`,
      variables: [rule.qtyKey],
    },
  }));
}

export const acoperisBlueprint: EstimateBlueprintConfig = baseConfig({
  accessDifficultyImpact: { easy: 1.0, medium: 1.2, difficult: 1.35 },
  urgencyImpact: { urgent: 1.2, emergency: 1.5 },
  planPointTypes: [
    { type: 'roof_plane', label: 'Suprafață acoperiș', color: '#f97316' },
    { type: 'chimney', label: 'Coș de fum', color: '#7c2d12' },
    { type: 'skylight', label: 'Fereastră mansardă', color: '#38bdf8' },
    { type: 'gutter', label: 'Jgheaburi & scurgeri', color: '#fed7aa' },
  ],
  workModules: [
    {
      key: 'demolition',
      label: 'Demontare acoperiș vechi',
      helpText: 'Demontare învelitoare existentă și evacuare resturi. Activați doar dacă se refacă acoperișul.',
      defaultEnabled: false,
      stageCodes: ['demontare'],
      fieldKeys: ['oldRoofRemoval'],
      requiresQtyKeys: ['oldRoofRemovalArea'],
      section: 'Pregătire',
    },
    {
      key: 'timber_structure',
      label: 'Structură lemn (căpriori)',
      helpText: 'Schelet din lemn + astereală sub învelitoare.',
      defaultEnabled: true,
      stageCodes: ['structura'],
      fieldKeys: ['baseArea', 'roofShape'],
      section: 'Structură',
    },
    {
      key: 'membrane',
      label: 'Membrană & folie',
      helpText: 'Folie anticondens / hidroizolație sub învelitoare.',
      defaultEnabled: true,
      stageCodes: ['membrana'],
      fieldKeys: ['roofSlope', 'membraneType'],
      section: 'Structură',
    },
    {
      key: 'insulation',
      label: 'Izolație termică',
      helpText: 'Vată minerală / polistiren între căpriori. Recomandat pentru climatul Moldovei.',
      defaultEnabled: true,
      stageCodes: ['izolare'],
      fieldKeys: ['insulationRequired', 'insulationThicknessMm'],
      requiresQtyKeys: ['insulationArea'],
      section: 'Structură',
    },
    {
      key: 'covering',
      label: 'Învelitoare',
      helpText: 'Tablă metalică sau țiglă peste membrană.',
      defaultEnabled: true,
      stageCodes: ['invelitoare'],
      fieldKeys: ['coveringType'],
      section: 'Învelitoare',
    },
    {
      key: 'valleys',
      label: 'Dolii (endova)',
      helpText: 'Îmbinări interioare ale planurilor de acoperiș (la L/T/U-shape).',
      defaultEnabled: true,
      stageCodes: ['accesorii', 'membrana', 'invelitoare'],
      fieldKeys: ['valleyLengthM'],
      requiresQtyKeys: ['valleyLengthM'],
      section: 'Învelitoare',
    },
    {
      key: 'wall_flashing',
      label: 'Priză la perete',
      helpText: 'Profile metalice de etanșare unde acoperișul se sprijină pe perete vertical.',
      defaultEnabled: true,
      stageCodes: ['accesorii', 'invelitoare'],
      fieldKeys: ['wallIntersectionLengthM'],
      requiresQtyKeys: ['wallIntersectionLengthM'],
      section: 'Învelitoare',
    },
    {
      key: 'gutters',
      label: 'Jgheaburi & scurgere',
      helpText: 'Jgheaburi orizontale + burlane verticale pentru evacuarea apei.',
      defaultEnabled: true,
      stageCodes: ['scurgere'],
      fieldKeys: ['gutterLengthM'],
      section: 'Scurgere & streașină',
    },
    {
      key: 'snow_guards',
      label: 'Parazăpadă',
      helpText: 'Bariere pentru zăpadă pe coamă — recomandat pentru siguranță în Moldova.',
      defaultEnabled: true,
      stageCodes: ['accesorii'],
      fieldKeys: ['snowGuardLengthM', 'snowGuardRows'],
      requiresQtyKeys: ['snowGuardTotalM'],
      section: 'Învelitoare',
    },
    {
      key: 'scaffolding',
      label: 'Schelă / lucru la înălțime',
      helpText: 'Schela devine necesară pentru acoperișuri înalte sau acces dificil.',
      defaultEnabled: false,
      stageCodes: ['schela'],
      fieldKeys: ['buildingHeightM', 'storyCount', 'scaffoldingRequired'],
      requiresQtyKeys: ['scaffoldingLengthM'],
      section: 'Pregătire',
    },
    {
      key: 'soffit',
      label: 'Streașină (podsoarea carnișului)',
      helpText: 'Obturarea cu lemn / PVC a părții de jos a streașinii. Estetic + protejează lemnul căpriorilor.',
      defaultEnabled: false,
      stageCodes: ['streasina'],
      fieldKeys: ['soffitLengthM'],
      requiresQtyKeys: ['soffitLengthM'],
      section: 'Scurgere & streașină',
    },
    {
      key: 'skylights',
      label: 'Ferestre de mansardă (Velux)',
      helpText: 'Montaj ferestre tip Velux în acoperiș — fiecare include rama, etanșarea și instalarea.',
      defaultEnabled: false,
      stageCodes: ['lucarne'],
      fieldKeys: ['skylightCount'],
      requiresQtyKeys: ['skylightCount'],
      section: 'Extra',
    },
    {
      key: 'gable',
      label: 'Fronton (peretele triunghiular sub coamă)',
      helpText: 'Finisarea părții triunghiulare a peretelui de sub coamă (tablă, lemn, panou). Apare la acoperișuri în două sau patru ape.',
      defaultEnabled: false,
      stageCodes: ['fronton'],
      fieldKeys: ['gableArea'],
      requiresQtyKeys: ['gableArea'],
      section: 'Extra',
    },
    {
      key: 'roof_drip_edge',
      label: 'Picurător streașină',
      helpText: 'Profil metalic montat între învelitoare și jgheab care direcționează apa în jgheab. Recomandat pe toate proiectele. Lungimea = perimetrul streașinii (≈ jgheaburi).',
      defaultEnabled: false,
      stageCodes: ['picurator_streasina'],
      fieldKeys: ['roofDripEdgeLengthM'],
      requiresQtyKeys: ['roofDripEdgeLengthM'],
      section: 'Scurgere & streașină',
    },
  ],
  customFields: [
    {
      key: 'baseArea',
      label: 'Suprafață la sol (amprenta clădirii)',
      type: 'number',
      unit: 'm²',
      required: true,
      validation: { min: 5 },
      helpText: 'Suprafața de teren acoperită de clădire — NU suprafața scaturilor. Aria reală a acoperișului se calculează automat din pantă.',
      placeholder: 'ex. 80',
      section: 'General',
    },
    {
      key: 'roofSlope',
      label: 'Panta acoperișului',
      type: 'number',
      unit: 'grade',
      required: false,
      defaultValue: 30,
      validation: { min: 0, max: 75 },
      helpText: 'Unghi față de orizontală. Tipic: 20-35° pentru tablă, 30-45° pentru țiglă.',
      warningRules: [
        { when: 'roofSlope > 60', message: 'Pantă foarte abruptă — necesită verificare manuală de către maistru.' },
      ],
      section: 'General',
    },
    {
      key: 'roofShape',
      label: 'Formă acoperiș',
      type: 'select',
      options: ['rectangle', 'l-shape', 't-shape', 'u-shape', 'complex'],
      required: false,
      defaultValue: 'rectangle',
      helpText:
        'Coeficienți complexitate: rectangle ×1.0, L-shape ×1.2 (+dolii), T/U-shape ×1.35, complex ×1.5. Influențează manopera și lungimea doliilor.',
      warningRules: [
        { when: "roofShape === 'l-shape'", message: 'Acoperiș în L — manopera crește automat cu +20% și se adaugă dolii.' },
        { when: "roofShape === 't-shape'", message: 'Acoperiș în T — manopera crește automat cu +35% și se adaugă dolii.' },
        { when: "roofShape === 'u-shape'", message: 'Acoperiș în U — manopera crește automat cu +35% și se adaugă dolii.' },
        { when: "roofShape === 'complex'", message: 'Formă complexă — manopera crește automat cu +50%; devizul necesită verificare manuală.' },
      ],
      section: 'General',
    },
    {
      key: 'oldRoofRemoval',
      label: 'Demontare acoperiș vechi',
      type: 'boolean',
      required: false,
      defaultValue: false,
      helpText: 'Bifați dacă se demontează acoperișul existent înainte.',
      section: 'General',
    },
    {
      key: 'insulationRequired',
      label: 'Izolație termică inclusă',
      type: 'boolean',
      required: false,
      defaultValue: true,
      helpText: 'Recomandat ON pentru locuințe.',
      section: 'General',
    },
    {
      key: 'valleyLengthM',
      label: 'Lungime dolii (endova)',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      helpText: 'Lăsați 0 — se calculează automat din forma acoperișului.',
      section: 'Avansat',
    },
    {
      key: 'ridgeLengthM',
      label: 'Lungime coamă',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      helpText: 'Lăsați 0 — se estimează din amprenta clădirii. Folosit și pentru parazăpadă.',
      section: 'Avansat',
    },
    {
      key: 'gutterLengthM',
      label: 'Lungime jgheaburi',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      helpText: 'Suma laturilor unde se montează jgheaburi (cca. perimetrul clădirii).',
      section: 'Avansat',
    },
    {
      key: 'wallIntersectionLengthM',
      label: 'Lungime priză la perete',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      helpText: 'Pentru case alipite sau anexe — zona unde acoperișul se sprijină pe perete.',
      section: 'Avansat',
    },
    {
      key: 'chimneyCount',
      label: 'Număr coșuri de fum',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      helpText: 'Lăsați 0 — se ia automat din plan dacă există puncte „Coș de fum”.',
      section: 'Avansat',
    },
    {
      key: 'soffitLengthM',
      label: 'Lungime streașină (podsoară)',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      helpText: 'Lungimea totală a streașinii unde se aplică podsoara. Lăsați 0 — se estimează din perimetrul clădirii.',
      section: 'Avansat',
    },
    {
      key: 'skylightCount',
      label: 'Număr ferestre Velux',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      helpText: 'Numărul de ferestre de mansardă. Prețul include rama, etanșarea și instalarea per bucată.',
      section: 'Avansat',
    },
    {
      key: 'gableArea',
      label: 'Suprafață fronton',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Suprafață totală a fronturilor (peretele triunghiular de sub coame). Pentru o casă în două ape: 2 × (lățime × înălțime fronton / 2).',
      section: 'Avansat',
    },
    {
      key: 'roofDripEdgeLengthM',
      label: 'Lungime picurător streașină',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      helpText: 'Lungime totală a picurătorului — egală cu jgheaburile. Lăsați 0 — se preia automat din `Lungime jgheaburi`.',
      section: 'Avansat',
    },
    {
      key: 'roofOverhangM',
      label: 'Surplombă standard',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0.4,
      validation: { min: 0, max: 1.5 },
      helpText: 'Streașina/surplomba se adaugă la dimensiunile acoperișului pentru calculul ariei și perimetrului.',
      section: 'General',
    },
    {
      key: 'coveringType',
      label: 'Tip învelitoare',
      type: 'select',
      options: ['metal_tile', 'ceramic_tile', 'bituminous_shingle', 'standing_seam', 'ondulin', 'other'],
      required: true,
      defaultValue: 'metal_tile',
      section: 'Învelitoare',
    },
    {
      key: 'membraneType',
      label: 'Tip membrană',
      type: 'select',
      options: ['standard', 'anticondens', 'diffusion', 'superdiffusion', 'premium'],
      required: false,
      defaultValue: 'anticondens',
      section: 'Structură',
    },
    {
      key: 'insulationThicknessMm',
      label: 'Grosime izolație',
      type: 'select',
      options: ['100', '150', '200', '250'],
      required: false,
      defaultValue: '150',
      dependentOnKey: 'insulationRequired',
      section: 'Structură',
    },
    {
      key: 'buildingHeightM',
      label: 'Înălțime clădire',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 6,
      validation: { min: 0, max: 30 },
      section: 'General',
    },
    {
      key: 'storyCount',
      label: 'Număr etaje',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 1,
      validation: { min: 1, max: 6 },
      section: 'General',
    },
    {
      key: 'scaffoldingRequired',
      label: 'Schelă necesară',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Pregătire',
    },
    {
      key: 'snowGuardLengthM',
      label: 'Lungime parazăpadă',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      section: 'Învelitoare',
    },
    {
      key: 'snowGuardRows',
      label: 'Număr rânduri parazăpadă',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 1,
      validation: { min: 1, max: 4 },
      section: 'Învelitoare',
    },
  ],
  diagnosticQuestions: [],
  defaultStages: [
    { code: 'demontare', name: 'Demontare & evacuare', kind: 'LABOR', defaultLaborHours: 8, durationDays: 2, checklist: ['Demontare învelitoare veche', 'Evacuare deșeuri'], optional: true, moduleKey: 'demolition' },
    { code: 'schela', name: 'Schelă & siguranță', kind: 'MIXED', defaultLaborHours: 4, durationDays: 1, checklist: ['Montaj schelă', 'Asigurare acces'], optional: true, moduleKey: 'scaffolding' },
    { code: 'structura', name: 'Structură căprior & astereală', kind: 'MIXED', defaultLaborHours: 16, durationDays: 4, checklist: ['Montaj căpriori', 'Tratament antiseptic lemn', 'Montaj astereală'], moduleKey: 'timber_structure' },
    { code: 'membrana', name: 'Membrană & folie anticondens', kind: 'MIXED', defaultLaborHours: 8, durationDays: 2, checklist: ['Montaj folie', 'Fixare rigle contra-șipci'], moduleKey: 'membrane' },
    { code: 'izolare', name: 'Izolație termică', kind: 'MIXED', defaultLaborHours: 10, durationDays: 2, checklist: ['Montaj vată/polistiren', 'Folie barieră de vapori'], optional: true, moduleKey: 'insulation' },
    { code: 'invelitoare', name: 'Montaj învelitoare', kind: 'MIXED', defaultLaborHours: 20, durationDays: 5, checklist: ['Montaj tablă/țiglă', 'Instalare coame'], moduleKey: 'covering' },
    { code: 'accesorii', name: 'Dolii, coame, coșuri', kind: 'MIXED', defaultLaborHours: 8, durationDays: 2, checklist: ['Etanșare dolii', 'Priză perete', 'Parazăpadă'], moduleKey: 'valleys' },
    { code: 'scurgere', name: 'Jgheaburi & burlane', kind: 'MIXED', defaultLaborHours: 6, durationDays: 1, checklist: ['Instalare cârlige', 'Montaj burlane'], moduleKey: 'gutters' },
    { code: 'streasina', name: 'Streașină / podsoară', kind: 'MIXED', defaultLaborHours: 6, durationDays: 1, checklist: ['Montaj scânduri / PVC', 'Profile finisaj'], optional: true, moduleKey: 'soffit' },
    { code: 'lucarne', name: 'Ferestre mansardă (Velux)', kind: 'MIXED', defaultLaborHours: 5, durationDays: 1, checklist: ['Decupare zonă', 'Montaj cadru Velux', 'Etanșare membrană'], optional: true, moduleKey: 'skylights' },
    { code: 'fronton', name: 'Finisare fronton', kind: 'MIXED', defaultLaborHours: 6, durationDays: 1, checklist: ['Montaj suport', 'Aplicare tablă / lemn', 'Etanșare margini'], optional: true, moduleKey: 'gable' },
    { code: 'picurator_streasina', name: 'Picurător streașină', kind: 'MIXED', defaultLaborHours: 3, durationDays: 1, checklist: ['Montaj profil pe astereală', 'Etanșare îmbinări'], optional: true, moduleKey: 'roof_drip_edge' },
    { code: 'verificare', name: 'Verificare & predare', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Test etanșeitate', 'Predare client'], moduleKey: 'membrane' },
  ],
  pricingRules: withQtyExplanations([
    { stageCode: 'demontare', description: 'Demontare acoperiș vechi', unit: 'm²', qtyKey: 'oldRoofRemovalArea', unitPrice: 38, kind: 'labor', moduleKey: 'demolition', enabledWhen: { anyQtyKeys: ['oldRoofRemovalArea'] } },
    { stageCode: 'demontare', description: 'Evacuare deșeuri acoperiș vechi', unit: 'm²', qtyKey: 'wasteRemovalArea', unitPrice: 18, kind: 'labor', moduleKey: 'demolition', enabledWhen: { anyQtyKeys: ['wasteRemovalArea'] } },
    { stageCode: 'schela', description: 'Schelă perimetrală', unit: 'm', qtyKey: 'scaffoldingLengthM', unitPrice: 85, kind: 'labor', moduleKey: 'scaffolding', enabledWhen: { moduleEnabled: 'scaffolding', anyQtyKeys: ['scaffoldingLengthM'] } },
    { stageCode: 'structura', description: 'Cherestea structură (căpriori, astereală)', unit: 'm³', qtyKey: 'timberVolumeM3', unitPrice: 5800, kind: 'material', moduleKey: 'timber_structure' },
    { stageCode: 'structura', description: 'Lucrări structură căpriori', unit: 'm²', qtyKey: 'roofAreaLabor', unitPrice: 135, kind: 'labor', moduleKey: 'timber_structure' },
    { stageCode: 'membrana', description: 'Membrană & folie', unit: 'm²', qtyKey: 'membraneAreaQty', unitPrice: 35, wastePct: 10, kind: 'material', moduleKey: 'membrane', materialUnitPriceMultiplierKey: 'membraneMaterialMultiplier' },
    { stageCode: 'membrana', description: 'Lucrări montaj membrană', unit: 'm²', qtyKey: 'roofAreaLabor', unitPrice: 50, kind: 'labor', moduleKey: 'membrane' },
    { stageCode: 'membrana', description: 'Covor impermeabil sub dolie', unit: 'm', qtyKey: 'valleyLengthM', unitPrice: 65, kind: 'material', moduleKey: 'valleys', enabledWhen: { anyQtyKeys: ['valleyLengthM'] } },
    { stageCode: 'izolare', description: 'Izolație termică acoperiș', unit: 'm²', qtyKey: 'insulationArea', unitPrice: 95, wastePct: 5, kind: 'material', moduleKey: 'insulation', materialUnitPriceMultiplierKey: 'insulationMaterialMultiplier', enabledWhen: { moduleEnabled: 'insulation', anyQtyKeys: ['insulationArea'] } },
    { stageCode: 'izolare', description: 'Lucrări montaj izolație', unit: 'm²', qtyKey: 'insulationArea', unitPrice: 55, kind: 'labor', moduleKey: 'insulation', enabledWhen: { moduleEnabled: 'insulation', anyQtyKeys: ['insulationArea'] } },
    { stageCode: 'izolare', description: 'Barieră de vapori (folie)', unit: 'm²', qtyKey: 'insulationArea', unitPrice: 28, wastePct: 8, kind: 'material', moduleKey: 'insulation', enabledWhen: { moduleEnabled: 'insulation', anyQtyKeys: ['insulationArea'] } },
    { stageCode: 'izolare', description: 'Lucrări barieră de vapori', unit: 'm²', qtyKey: 'insulationArea', unitPrice: 30, kind: 'labor', moduleKey: 'insulation', enabledWhen: { moduleEnabled: 'insulation', anyQtyKeys: ['insulationArea'] } },
    { stageCode: 'invelitoare', description: 'Învelitoare acoperiș (material)', unit: 'm²', qtyKey: 'coveringAreaQty', unitPrice: 245, wastePct: 12, kind: 'material', moduleKey: 'covering', materialUnitPriceMultiplierKey: 'coveringMaterialMultiplier' },
    { stageCode: 'invelitoare', description: 'Lucrări montaj învelitoare', unit: 'm²', qtyKey: 'roofAreaLabor', unitPrice: 135, kind: 'labor', moduleKey: 'covering', laborUnitPriceMultiplierKey: 'coveringLaborMultiplier' },
    { stageCode: 'invelitoare', description: 'Coames metalice (ridge caps)', unit: 'm', qtyKey: 'ridgeLengthM', unitPrice: 95, wastePct: 5, kind: 'material', moduleKey: 'covering', enabledWhen: { anyQtyKeys: ['ridgeLengthM'] } },
    { stageCode: 'invelitoare', description: 'Lucrări montaj coame', unit: 'm', qtyKey: 'ridgeLengthM', unitPrice: 60, kind: 'labor', moduleKey: 'covering', enabledWhen: { anyQtyKeys: ['ridgeLengthM'] } },
    { stageCode: 'accesorii', description: 'Elemente dolii metalice', unit: 'm', qtyKey: 'valleyLengthM', unitPrice: 140, kind: 'material', moduleKey: 'valleys', enabledWhen: { anyQtyKeys: ['valleyLengthM'] } },
    { stageCode: 'accesorii', description: 'Lucrări montaj & etanșare dolii', unit: 'm', qtyKey: 'valleyLengthM', unitPrice: 120, kind: 'labor', moduleKey: 'valleys', enabledWhen: { anyQtyKeys: ['valleyLengthM'] } },
    { stageCode: 'accesorii', description: 'Profile priză la perete', unit: 'm', qtyKey: 'wallIntersectionLengthM', unitPrice: 85, kind: 'material', moduleKey: 'wall_flashing', enabledWhen: { anyQtyKeys: ['wallIntersectionLengthM'] } },
    { stageCode: 'accesorii', description: 'Lucrări priză & etanșare perete', unit: 'm', qtyKey: 'wallIntersectionLengthM', unitPrice: 95, kind: 'labor', moduleKey: 'wall_flashing', enabledWhen: { anyQtyKeys: ['wallIntersectionLengthM'] } },
    { stageCode: 'accesorii', description: 'Etanșare coș de fum', unit: 'buc', qtyKey: 'chimneyCount', unitPrice: 650, kind: 'labor', moduleKey: 'valleys', enabledWhen: { anyQtyKeys: ['chimneyCount'] } },
    { stageCode: 'accesorii', description: 'Parazăpadă', unit: 'm', qtyKey: 'snowGuardTotalM', unitPrice: 75, kind: 'material', moduleKey: 'snow_guards', enabledWhen: { moduleEnabled: 'snow_guards', anyQtyKeys: ['snowGuardTotalM'] } },
    { stageCode: 'scurgere', description: 'Jgheaburi metalice', unit: 'm', qtyKey: 'gutterLengthM', unitPrice: 110, kind: 'material', moduleKey: 'gutters' },
    { stageCode: 'scurgere', description: 'Lucrări montaj jgheaburi', unit: 'm', qtyKey: 'gutterLengthM', unitPrice: 75, kind: 'labor', moduleKey: 'gutters' },
    { stageCode: 'streasina', description: 'Scânduri / PVC podsoară', unit: 'm', qtyKey: 'soffitLengthM', unitPrice: 180, wastePct: 8, kind: 'material', moduleKey: 'soffit', enabledWhen: { moduleEnabled: 'soffit', anyQtyKeys: ['soffitLengthM'] } },
    { stageCode: 'streasina', description: 'Lucrări montaj podsoară', unit: 'm', qtyKey: 'soffitLengthM', unitPrice: 90, kind: 'labor', moduleKey: 'soffit', enabledWhen: { moduleEnabled: 'soffit', anyQtyKeys: ['soffitLengthM'] } },
    { stageCode: 'lucarne', description: 'Ferestre Velux (material per bucată)', unit: 'buc', qtyKey: 'skylightCount', unitPrice: 3500, kind: 'material', moduleKey: 'skylights', enabledWhen: { moduleEnabled: 'skylights', anyQtyKeys: ['skylightCount'] } },
    { stageCode: 'lucarne', description: 'Lucrări montaj Velux', unit: 'buc', qtyKey: 'skylightCount', unitPrice: 1500, kind: 'labor', moduleKey: 'skylights', enabledWhen: { moduleEnabled: 'skylights', anyQtyKeys: ['skylightCount'] } },
    { stageCode: 'fronton', description: 'Material fronton (tablă/lemn)', unit: 'm²', qtyKey: 'gableArea', unitPrice: 145, wastePct: 10, kind: 'material', moduleKey: 'gable', enabledWhen: { moduleEnabled: 'gable', anyQtyKeys: ['gableArea'] } },
    { stageCode: 'fronton', description: 'Lucrări montaj fronton', unit: 'm²', qtyKey: 'gableArea', unitPrice: 85, kind: 'labor', moduleKey: 'gable', enabledWhen: { moduleEnabled: 'gable', anyQtyKeys: ['gableArea'] } },
    { stageCode: 'picurator_streasina', description: 'Profil picurător (material)', unit: 'm', qtyKey: 'roofDripEdgeLengthM', unitPrice: 45, wastePct: 5, kind: 'material', moduleKey: 'roof_drip_edge', enabledWhen: { moduleEnabled: 'roof_drip_edge', anyQtyKeys: ['roofDripEdgeLengthM'] } },
    { stageCode: 'picurator_streasina', description: 'Lucrări montaj picurător', unit: 'm', qtyKey: 'roofDripEdgeLengthM', unitPrice: 30, kind: 'labor', moduleKey: 'roof_drip_edge', enabledWhen: { moduleEnabled: 'roof_drip_edge', anyQtyKeys: ['roofDripEdgeLengthM'] } },
    { stageCode: 'verificare', description: 'Verificare etanșeitate & predare', unit: 'm²', qtyKey: 'roofArea', unitPrice: 8, kind: 'labor', moduleKey: 'membrane' },
  ]),
});
