import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

export const acoperisBlueprint: EstimateBlueprintConfig = baseConfig({
  planPointTypes: [
    { type: 'roof_plane', label: 'Suprafață acoperiș', color: '#f97316' },
    { type: 'chimney', label: 'Coș de fum', color: '#7c2d12' },
    { type: 'gutter', label: 'Jgheaburi & scurgeri', color: '#fed7aa' },
  ],
  workModules: [
    {
      key: 'demolition',
      label: 'Demontare acoperiș vechi',
      defaultEnabled: false,
      stageCodes: ['demontare'],
      fieldKeys: ['oldRoofRemoval'],
      requiresQtyKeys: ['oldRoofRemovalArea'],
    },
    {
      key: 'timber_structure',
      label: 'Structură lemn (căpriori)',
      defaultEnabled: true,
      stageCodes: ['structura'],
      fieldKeys: ['timberType', 'baseArea', 'roofShape'],
    },
    {
      key: 'membrane',
      label: 'Membrană & folie',
      defaultEnabled: true,
      stageCodes: ['membrana'],
      fieldKeys: ['roofSlope'],
    },
    {
      key: 'insulation',
      label: 'Izolație termică',
      defaultEnabled: false,
      stageCodes: ['izolare'],
      fieldKeys: ['insulationRequired'],
      requiresQtyKeys: ['insulationArea'],
    },
    {
      key: 'covering',
      label: 'Învelitoare (tablă/țiglă)',
      defaultEnabled: true,
      stageCodes: ['invelitoare'],
      fieldKeys: ['roofCoveringType'],
    },
    {
      key: 'valleys',
      label: 'Dolii (endova)',
      defaultEnabled: true,
      stageCodes: ['accesorii', 'membrana', 'invelitoare'],
      fieldKeys: ['valleyLengthM'],
      requiresQtyKeys: ['valleyLengthM'],
    },
    {
      key: 'wall_flashing',
      label: 'Priză la perete',
      defaultEnabled: true,
      stageCodes: ['accesorii', 'invelitoare'],
      fieldKeys: ['wallIntersectionLengthM'],
      requiresQtyKeys: ['wallIntersectionLengthM'],
    },
    {
      key: 'gutters',
      label: 'Jgheaburi & scurgere',
      defaultEnabled: true,
      stageCodes: ['scurgere'],
      fieldKeys: ['gutterLengthM'],
    },
    {
      key: 'snow_guards',
      label: 'Parazăpadă',
      defaultEnabled: false,
      stageCodes: ['accesorii'],
      fieldKeys: [],
      requiresQtyKeys: ['snowGuardLengthM'],
    },
  ],
  customFields: [
    {
      key: 'baseArea',
      label: 'Suprafață la sol',
      type: 'number',
      unit: 'm²',
      required: true,
      validation: { min: 5 },
      helpText: 'Amprenta clădirii la sol.',
      section: 'General',
    },
    {
      key: 'roofSlope',
      label: 'Panta acoperișului',
      type: 'number',
      unit: 'grade',
      required: false,
      defaultValue: 30,
      validation: { min: 0, max: 75 },
      warningRules: [{ when: 'roofSlope > 60', message: 'Pantă foarte abruptă — verificare manuală recomandată.' }],
      section: 'General',
    },
    {
      key: 'roofShape',
      label: 'Formă acoperiș',
      type: 'select',
      options: ['rectangle', 'l-shape', 't-shape', 'u-shape', 'complex'],
      required: false,
      defaultValue: 'rectangle',
      section: 'General',
    },
    {
      key: 'roofCoveringType',
      label: 'Tip învelitoare',
      type: 'select',
      options: ['metal_tile', 'ceramic_tile', 'bitumen', 'standing_seam'],
      required: false,
      section: 'Învelitoare',
    },
    {
      key: 'valleyLengthM',
      label: 'Lungime dolii / îmbinări',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      section: 'Accesorii',
    },
    {
      key: 'ridgeLengthM',
      label: 'Lungime coamă',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      section: 'Accesorii',
    },
    {
      key: 'gutterLengthM',
      label: 'Lungime jgheaburi',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      section: 'Scurgere',
    },
    {
      key: 'wallIntersectionLengthM',
      label: 'Lungime priză la perete',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      section: 'Accesorii',
    },
    {
      key: 'chimneyCount',
      label: 'Număr coșuri de fum',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Accesorii',
    },
    {
      key: 'timberType',
      label: 'Tip cherestea structură',
      type: 'select',
      options: ['Molid Clasa A', 'Pin Tratativ', 'Fag Uscat'],
      required: true,
      section: 'Structură',
    },
    {
      key: 'oldRoofRemoval',
      label: 'Demontare acoperiș vechi',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Demontare',
    },
    {
      key: 'insulationRequired',
      label: 'Izolație termică inclusă',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Izolație',
    },
  ],
  diagnosticQuestions: [
    { key: 'baseArea', label: 'Suprafață la sol (m²)', type: 'number' },
    { key: 'gutterLengthM', label: 'Lungime jgheaburi (m)', type: 'number' },
  ],
  defaultStages: [
    { code: 'demontare', name: 'Demontare & evacuare', kind: 'LABOR', defaultLaborHours: 8, durationDays: 2, checklist: ['Demontare învelitoare veche', 'Evacuare deșeuri'], optional: true, moduleKey: 'demolition' },
    { code: 'structura', name: 'Structură căprior & astereală', kind: 'MIXED', defaultLaborHours: 16, durationDays: 4, checklist: ['Montaj căpriori', 'Tratament antiseptic lemn', 'Montaj astereală'], moduleKey: 'timber_structure' },
    { code: 'membrana', name: 'Membrană & folie anticondens', kind: 'MIXED', defaultLaborHours: 8, durationDays: 2, checklist: ['Montaj folie', 'Fixare rigle contra-șipci'], moduleKey: 'membrane' },
    { code: 'izolare', name: 'Izolație termică', kind: 'MIXED', defaultLaborHours: 10, durationDays: 2, checklist: ['Montaj vată/polistiren', 'Folie barieră de vapori'], optional: true, moduleKey: 'insulation' },
    { code: 'invelitoare', name: 'Montaj învelitoare', kind: 'MIXED', defaultLaborHours: 20, durationDays: 5, checklist: ['Montaj tablă/țiglă', 'Instalare coame'], moduleKey: 'covering' },
    { code: 'accesorii', name: 'Dolii, coame, coșuri', kind: 'MIXED', defaultLaborHours: 8, durationDays: 2, checklist: ['Etanșare dolii', 'Priză perete', 'Parazăpadă'], moduleKey: 'valleys' },
    { code: 'scurgere', name: 'Jgheaburi & burlane', kind: 'MIXED', defaultLaborHours: 6, durationDays: 1, checklist: ['Instalare cârlige', 'Montaj burlane'], moduleKey: 'gutters' },
    { code: 'verificare', name: 'Verificare & predare', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Test etanșeitate', 'Predare client'], moduleKey: 'membrane' },
  ],
  pricingRules: [
    { stageCode: 'demontare', description: 'Demontare acoperiș vechi', unit: 'm²', qtyKey: 'oldRoofRemovalArea', unitPrice: 38, kind: 'labor', moduleKey: 'demolition', enabledWhen: { anyQtyKeys: ['oldRoofRemovalArea'] } },
    { stageCode: 'structura', description: 'Cherestea structură (căpriori, astereală)', unit: 'm³', qtyKey: 'timberVolumeM3', unitPrice: 5800, kind: 'material', moduleKey: 'timber_structure' },
    { stageCode: 'structura', description: 'Manoperă structură căpriori', unit: 'm²', qtyKey: 'roofAreaLabor', unitPrice: 135, kind: 'labor', moduleKey: 'timber_structure' },
    { stageCode: 'membrana', description: 'Membrană anticondens', unit: 'm²', qtyKey: 'roofArea', unitPrice: 35, wastePct: 10, kind: 'material', moduleKey: 'membrane' },
    { stageCode: 'membrana', description: 'Manoperă montaj membrană', unit: 'm²', qtyKey: 'roofAreaLabor', unitPrice: 50, kind: 'labor', moduleKey: 'membrane' },
    { stageCode: 'membrana', description: 'Covor impermeabil sub dolie', unit: 'm', qtyKey: 'valleyLengthM', unitPrice: 65, kind: 'material', moduleKey: 'valleys', enabledWhen: { anyQtyKeys: ['valleyLengthM'] } },
    { stageCode: 'izolare', description: 'Izolație termică acoperiș', unit: 'm²', qtyKey: 'insulationArea', unitPrice: 95, wastePct: 5, kind: 'material', moduleKey: 'insulation', enabledWhen: { moduleEnabled: 'insulation', anyQtyKeys: ['insulationArea'] } },
    { stageCode: 'izolare', description: 'Manoperă montaj izolație', unit: 'm²', qtyKey: 'insulationArea', unitPrice: 55, kind: 'labor', moduleKey: 'insulation', enabledWhen: { moduleEnabled: 'insulation', anyQtyKeys: ['insulationArea'] } },
    { stageCode: 'invelitoare', description: 'Tablă metalică / țiglă (material)', unit: 'm²', qtyKey: 'roofArea', unitPrice: 245, wastePct: 12, kind: 'material', moduleKey: 'covering' },
    { stageCode: 'invelitoare', description: 'Manoperă montaj învelitoare', unit: 'm²', qtyKey: 'roofAreaLabor', unitPrice: 135, kind: 'labor', moduleKey: 'covering' },
    { stageCode: 'accesorii', description: 'Elemente dolii metalice', unit: 'm', qtyKey: 'valleyLengthM', unitPrice: 140, kind: 'material', moduleKey: 'valleys', enabledWhen: { anyQtyKeys: ['valleyLengthM'] } },
    { stageCode: 'accesorii', description: 'Manoperă montaj & etanșare dolii', unit: 'm', qtyKey: 'valleyLengthM', unitPrice: 120, kind: 'labor', moduleKey: 'valleys', enabledWhen: { anyQtyKeys: ['valleyLengthM'] } },
    { stageCode: 'accesorii', description: 'Profile priză la perete', unit: 'm', qtyKey: 'wallIntersectionLengthM', unitPrice: 85, kind: 'material', moduleKey: 'wall_flashing', enabledWhen: { anyQtyKeys: ['wallIntersectionLengthM'] } },
    { stageCode: 'accesorii', description: 'Manoperă priză & etanșare perete', unit: 'm', qtyKey: 'wallIntersectionLengthM', unitPrice: 95, kind: 'labor', moduleKey: 'wall_flashing', enabledWhen: { anyQtyKeys: ['wallIntersectionLengthM'] } },
    { stageCode: 'accesorii', description: 'Etanșare coș de fum', unit: 'buc', qtyKey: 'chimneyCount', unitPrice: 650, kind: 'labor', moduleKey: 'valleys', enabledWhen: { anyQtyKeys: ['chimneyCount'] } },
    { stageCode: 'accesorii', description: 'Parazăpadă', unit: 'm', qtyKey: 'snowGuardLengthM', unitPrice: 75, kind: 'material', moduleKey: 'snow_guards', enabledWhen: { moduleEnabled: 'snow_guards', anyQtyKeys: ['snowGuardLengthM'] } },
    { stageCode: 'scurgere', description: 'Jgheaburi metalice', unit: 'm', qtyKey: 'gutterLengthM', unitPrice: 110, kind: 'material', moduleKey: 'gutters' },
    { stageCode: 'scurgere', description: 'Manoperă montaj jgheaburi', unit: 'm', qtyKey: 'gutterLengthM', unitPrice: 75, kind: 'labor', moduleKey: 'gutters' },
    { stageCode: 'verificare', description: 'Verificare etanșeitate & predare', unit: 'm²', qtyKey: 'roofArea', unitPrice: 8, kind: 'labor', moduleKey: 'membrane' },
  ],
});
