import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

export const cleaningBlueprint: EstimateBlueprintConfig = baseConfig({
  wizardSteps: ['object', 'diagnostic', 'stages', 'review'],
  urgencyImpact: { urgent: 1.2, emergency: 1.4 },
  planPointTypes: [
    { type: 'room', label: 'Cameră', color: '#22c55e' },
    { type: 'window_clean', label: 'Geamuri', color: '#15803d' },
    { type: 'deep_clean', label: 'Curățare profundă', color: '#166534' },
  ],
  workModules: [
    {
      key: 'standard_cleaning',
      label: 'Curățenie standard',
      helpText: 'Curățare obișnuită — desprăfuire, aspirare, spălare pardoseli, suprafețe.',
      defaultEnabled: true,
      stageCodes: ['uscata', 'umeda'],
      fieldKeys: ['cleaningType', 'cleanArea', 'furniturePresent'],
    },
    {
      key: 'deep_cleaning',
      label: 'Curățenie profundă',
      helpText: 'În plus față de standard: degresare hote, mașini, ușițe, ferestre interioare, cabine duș. Activați pentru locuințe neglijate.',
      defaultEnabled: false,
      stageCodes: ['umeda', 'special'],
      fieldKeys: ['cleaningType'],
    },
    {
      key: 'windows',
      label: 'Geamuri',
      helpText: 'Spălare geamuri din ambele părți (interior + exterior) + rame.',
      defaultEnabled: true,
      stageCodes: ['geamuri'],
      fieldKeys: ['windowCount'],
      requiresQtyKeys: ['windowCleanCount'],
    },
    {
      key: 'kitchen',
      label: 'Bucătărie (curățenie profundă)',
      helpText: 'Degresare aragaz, hota, cuptor, suprafețe sub aparate. Activați împreună cu cmâmpul „Curățenie profundă bucătărie”.',
      defaultEnabled: true,
      stageCodes: ['bucatarie_bai'],
      fieldKeys: ['kitchenDeepClean'],
      requiresQtyKeys: ['kitchenDeepCleanUnits'],
    },
    {
      key: 'bathrooms',
      label: 'Grupuri sanitare',
      helpText: 'Detartrare, dezinfectare, polișare oglinzi și suprafețe.',
      defaultEnabled: true,
      stageCodes: ['bucatarie_bai'],
      fieldKeys: ['bathroomCount'],
      requiresQtyKeys: ['bathroomCleanUnits'],
    },
    {
      key: 'post_construction',
      label: 'Curățenie post-șantier',
      helpText: 'Înlăturarea prafului de construcții, urmelor de adeziv/vopsea. Activați împreună cu „Tip curățenie = post-șantier”.',
      defaultEnabled: false,
      stageCodes: ['special'],
      fieldKeys: ['cleaningType', 'afterRepairDustLevel'],
      requiresQtyKeys: ['postConstructionAreaLabor'],
    },
    {
      key: 'trash_removal',
      label: 'Evacuare gunoi',
      helpText: 'Strângerea și evacuarea sacilor cu deșeuri. Activați împreună cu câmpul „Evacuare gunoi”.',
      defaultEnabled: false,
      stageCodes: ['special'],
      fieldKeys: ['trashRemoval'],
      requiresQtyKeys: ['trashRemovalUnits'],
    },
  ],
  customFields: [
    {
      key: 'cleanArea',
      label: 'Suprafață totală',
      type: 'number',
      unit: 'm²',
      required: true,
      validation: { min: 1 },
      helpText: 'Suprafața totală care trebuie curățată (inclusiv toate camerele).',
      placeholder: 'ex. 60',
      section: 'General',
    },
    {
      key: 'cleaningType',
      label: 'Tip curățenie',
      type: 'select',
      options: ['standard', 'deep', 'post_construction', 'move_out'],
      required: false,
      defaultValue: 'standard',
      helpText:
        'Standard ×1.0 (locuință utilizată zilnic). Profundă ×1.35. Mutare ×1.25 (înainte/după mutat). Post-șantier ×1.65 (după reparații).',
      section: 'General',
    },
    {
      key: 'windowCount',
      label: 'Număr geamuri',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      helpText: 'Numărul total de geamuri care trebuie spălate. Lăsați 0 dacă nu sunt incluse.',
      section: 'General',
    },
    {
      key: 'bathroomCount',
      label: 'Număr băi',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      helpText: 'Câte băi și grupuri sanitare se curăță separat.',
      section: 'General',
    },
    {
      key: 'furniturePresent',
      label: 'Mobilier prezent',
      type: 'boolean',
      required: false,
      defaultValue: false,
      helpText: 'Bifați dacă locuința este mobilată. Adaugă +10% la costul lucrărilor (mobila îngreunează accesul).',
      section: 'Avansat',
    },
    {
      key: 'kitchenDeepClean',
      label: 'Curățenie profundă bucătărie',
      type: 'boolean',
      required: false,
      defaultValue: false,
      helpText: 'Include degresare aragaz, hota, cuptor (interior), interior dulapuri.',
      section: 'Avansat',
    },
    {
      key: 'trashRemoval',
      label: 'Evacuare gunoi / deșeuri',
      type: 'boolean',
      required: false,
      defaultValue: false,
      helpText: 'Activează automat modulul „Evacuare gunoi”. Se calculează ≈ 1 sac per 50 m².',
      section: 'Avansat',
    },
    {
      key: 'afterRepairDustLevel',
      label: 'Nivel praf după reparații',
      type: 'select',
      options: ['low', 'medium', 'high'],
      required: false,
      defaultValue: 'low',
      helpText:
        'Relevant doar pentru curățenie post-șantier. Scăzut ×1.0. Mediu ×1.15 (reparații minore). Ridicat ×1.35 (construcție / renovare completă).',
      section: 'Avansat',
    },
  ],
  diagnosticQuestions: [],
  defaultStages: [
    { code: 'inspectie', name: 'Inspecție & plan zone', kind: 'LABOR', defaultLaborHours: 1, durationDays: 1, checklist: ['Inventar zone', 'Lista priorități'], moduleKey: 'standard_cleaning' },
    { code: 'uscata', name: 'Curățare uscată & desprăfuire', kind: 'LABOR', defaultLaborHours: 3, durationDays: 1, checklist: ['Aspirare tavane', 'Desprăfuire mobilier'], moduleKey: 'standard_cleaning' },
    { code: 'umeda', name: 'Curățare umedă', kind: 'MIXED', defaultLaborHours: 5, durationDays: 1, checklist: ['Spălare pardoseli', 'Igienizare suprafețe'], moduleKey: 'standard_cleaning' },
    { code: 'bucatarie_bai', name: 'Bucătărie & băi', kind: 'MIXED', defaultLaborHours: 3, durationDays: 1, checklist: ['Degresare bucătărie', 'Sanitare'], moduleKey: 'bathrooms' },
    { code: 'geamuri', name: 'Spălare geamuri', kind: 'LABOR', defaultLaborHours: 3, durationDays: 1, checklist: ['Rame & sticlă'], moduleKey: 'windows' },
    { code: 'special', name: 'Curățenie specială', kind: 'MIXED', defaultLaborHours: 4, durationDays: 1, checklist: ['Praf post-șantier', 'Evacuare gunoi'], moduleKey: 'post_construction' },
    { code: 'predare', name: 'Verificare & predare', kind: 'LABOR', defaultLaborHours: 1, durationDays: 1, checklist: ['Walkthrough client'], moduleKey: 'standard_cleaning' },
  ],
  pricingRules: [
    { stageCode: 'inspectie', description: 'Inspecție & plan curățenie', unit: 'ore', qtyKey: 'inspectionHours', unitPrice: 120, kind: 'labor', moduleKey: 'standard_cleaning' },
    // F: standard rule now gated by moduleEnabled — prevents double-charge when only deep_cleaning is active.
    { stageCode: 'uscata', description: 'Curățare uscată (lucrări)', unit: 'm²', qtyKey: 'dryCleanAreaLabor', unitPrice: 18, kind: 'labor', moduleKey: 'standard_cleaning', enabledWhen: { moduleEnabled: 'standard_cleaning', anyQtyKeys: ['standardCleanAreaLabor'] } },
    { stageCode: 'umeda', description: 'Detergenți & consumabile', unit: 'buc', qtyKey: 'chemistryUnits', unitPrice: 45, kind: 'material', moduleKey: 'standard_cleaning', enabledWhen: { moduleEnabled: 'standard_cleaning' } },
    { stageCode: 'umeda', description: 'Lucrări curățenie standard', unit: 'm²', qtyKey: 'standardCleanAreaLabor', unitPrice: 30, kind: 'labor', moduleKey: 'standard_cleaning', enabledWhen: { moduleEnabled: 'standard_cleaning', anyQtyKeys: ['standardCleanAreaLabor'] } },
    { stageCode: 'umeda', description: 'Lucrări curățenie profundă', unit: 'm²', qtyKey: 'cleanAreaLabor', unitPrice: 42, kind: 'labor', moduleKey: 'deep_cleaning', enabledWhen: { moduleEnabled: 'deep_cleaning', anyQtyKeys: ['cleanAreaLabor'] } },
    { stageCode: 'bucatarie_bai', description: 'Curățenie profundă bucătărie', unit: 'buc', qtyKey: 'kitchenDeepCleanUnits', unitPrice: 280, kind: 'labor', moduleKey: 'kitchen', enabledWhen: { moduleEnabled: 'kitchen', anyQtyKeys: ['kitchenDeepCleanUnits'] } },
    { stageCode: 'bucatarie_bai', description: 'Curățenie grup sanitar', unit: 'buc', qtyKey: 'bathroomCleanUnits', unitPrice: 180, kind: 'labor', moduleKey: 'bathrooms', enabledWhen: { anyQtyKeys: ['bathroomCleanUnits'] } },
    { stageCode: 'geamuri', description: 'Spălare geamuri', unit: 'buc', qtyKey: 'windowCleanCount', unitPrice: 50, kind: 'labor', moduleKey: 'windows', enabledWhen: { anyQtyKeys: ['windowCleanCount'] } },
    { stageCode: 'special', description: 'Curățenie post-șantier', unit: 'm²', qtyKey: 'postConstructionAreaLabor', unitPrice: 55, kind: 'labor', moduleKey: 'post_construction', enabledWhen: { moduleEnabled: 'post_construction', anyQtyKeys: ['postConstructionAreaLabor'] } },
    { stageCode: 'special', description: 'Evacuare gunoi/deșeuri', unit: 'buc', qtyKey: 'trashRemovalUnits', unitPrice: 65, kind: 'labor', moduleKey: 'trash_removal', enabledWhen: { moduleEnabled: 'trash_removal', anyQtyKeys: ['trashRemovalUnits'] } },
    { stageCode: 'predare', description: 'Verificare finală & predare', unit: 'm²', qtyKey: 'cleanArea', unitPrice: 5, kind: 'labor', moduleKey: 'standard_cleaning' },
  ],
});
