import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

export const cleaningBlueprint: EstimateBlueprintConfig = baseConfig({
  planPointTypes: [
    { type: 'room', label: 'Cameră', color: '#22c55e' },
    { type: 'window_clean', label: 'Geamuri', color: '#15803d' },
    { type: 'deep_clean', label: 'Curățare profundă', color: '#166534' },
  ],
  workModules: [
    {
      key: 'standard_cleaning',
      label: 'Curățenie standard',
      defaultEnabled: true,
      stageCodes: ['uscata', 'umeda'],
      fieldKeys: ['cleaningType', 'cleanArea', 'floorType', 'furniturePresent'],
    },
    {
      key: 'deep_cleaning',
      label: 'Curățenie profundă',
      defaultEnabled: false,
      stageCodes: ['umeda', 'special'],
      fieldKeys: ['cleaningType'],
    },
    {
      key: 'windows',
      label: 'Geamuri',
      defaultEnabled: true,
      stageCodes: ['geamuri'],
      fieldKeys: ['windowCount'],
      requiresQtyKeys: ['windowCleanCount'],
    },
    {
      key: 'kitchen',
      label: 'Bucătărie',
      defaultEnabled: true,
      stageCodes: ['bucatarie_bai'],
      fieldKeys: ['kitchenDeepClean'],
      requiresQtyKeys: ['kitchenDeepCleanUnits'],
    },
    {
      key: 'bathrooms',
      label: 'Grupuri sanitare',
      defaultEnabled: true,
      stageCodes: ['bucatarie_bai'],
      fieldKeys: ['bathroomCount'],
      requiresQtyKeys: ['bathroomCleanUnits'],
    },
    {
      key: 'post_construction',
      label: 'Curățenie post-șantier',
      defaultEnabled: false,
      stageCodes: ['special'],
      fieldKeys: ['cleaningType', 'afterRepairDustLevel'],
      requiresQtyKeys: ['postConstructionAreaLabor'],
    },
    {
      key: 'trash_removal',
      label: 'Evacuare gunoi',
      defaultEnabled: false,
      stageCodes: ['special'],
      fieldKeys: ['trashRemoval'],
      requiresQtyKeys: ['trashRemovalUnits'],
    },
  ],
  customFields: [
    {
      key: 'cleanArea',
      label: 'Suprafață totală',
      type: 'number',
      unit: 'm²',
      required: true,
      validation: { min: 1 },
      section: 'General',
    },
    {
      key: 'windowCount',
      label: 'Număr geamuri',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Geamuri',
    },
    {
      key: 'bathroomCount',
      label: 'Număr băi',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Sanitare',
    },
    {
      key: 'kitchenDeepClean',
      label: 'Curățenie profundă bucătărie',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Bucătărie',
    },
    {
      key: 'cleaningType',
      label: 'Tip curățenie',
      type: 'select',
      options: ['standard', 'deep', 'post_construction', 'move_out'],
      required: false,
      defaultValue: 'standard',
      section: 'General',
    },
    {
      key: 'furniturePresent',
      label: 'Mobilier prezent',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'General',
    },
    {
      key: 'trashRemoval',
      label: 'Evacuare gunoi/deșeuri',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Special',
    },
    {
      key: 'floorType',
      label: 'Tip pardoseală',
      type: 'select',
      options: ['tile', 'wood', 'carpet', 'mixed'],
      required: false,
      defaultValue: 'mixed',
      section: 'General',
    },
    {
      key: 'afterRepairDustLevel',
      label: 'Nivel praf după reparații',
      type: 'select',
      options: ['low', 'medium', 'high'],
      required: false,
      defaultValue: 'low',
      section: 'Special',
    },
  ],
  diagnosticQuestions: [
    { key: 'cleanArea', label: 'Suprafață totală (m²)', type: 'number' },
    { key: 'windowCount', label: 'Număr geamuri', type: 'number' },
  ],
  defaultStages: [
    { code: 'inspectie', name: 'Inspecție & plan zone', kind: 'LABOR', defaultLaborHours: 1, durationDays: 1, checklist: ['Inventar zone', 'Lista priorități'], moduleKey: 'standard_cleaning' },
    { code: 'uscata', name: 'Curățare uscată & desprăfuire', kind: 'LABOR', defaultLaborHours: 3, durationDays: 1, checklist: ['Aspirare tavane', 'Desprăfuire mobilier'], moduleKey: 'standard_cleaning' },
    { code: 'umeda', name: 'Curățare umedă', kind: 'MIXED', defaultLaborHours: 5, durationDays: 1, checklist: ['Spălare pardoseli', 'Igienizare suprafețe'], moduleKey: 'standard_cleaning' },
    { code: 'bucatarie_bai', name: 'Bucătărie & băi', kind: 'MIXED', defaultLaborHours: 3, durationDays: 1, checklist: ['Degresare bucătărie', 'Sanitare'], moduleKey: 'bathrooms' },
    { code: 'geamuri', name: 'Spălare geamuri', kind: 'LABOR', defaultLaborHours: 3, durationDays: 1, checklist: ['Rame & sticlă'], moduleKey: 'windows' },
    { code: 'special', name: 'Curățenie specială', kind: 'MIXED', defaultLaborHours: 4, durationDays: 1, checklist: ['Praf post-șantier', 'Evacuare gunoi'], moduleKey: 'post_construction' },
    { code: 'predare', name: 'Verificare & predare', kind: 'LABOR', defaultLaborHours: 1, durationDays: 1, checklist: ['Walkthrough client'], moduleKey: 'standard_cleaning' },
  ],
  pricingRules: [
    { stageCode: 'inspectie', description: 'Inspecție & plan curățenie', unit: 'ore', qtyKey: 'inspectionHours', unitPrice: 120, kind: 'labor', moduleKey: 'standard_cleaning' },
    { stageCode: 'uscata', description: 'Curățare uscată (manoperă)', unit: 'm²', qtyKey: 'dryCleanAreaLabor', unitPrice: 18, kind: 'labor', moduleKey: 'standard_cleaning', enabledWhen: { anyQtyKeys: ['standardCleanAreaLabor'] } },
    { stageCode: 'umeda', description: 'Detergenți & consumabile', unit: 'buc', qtyKey: 'chemistryUnits', unitPrice: 45, kind: 'material', moduleKey: 'standard_cleaning' },
    { stageCode: 'umeda', description: 'Manoperă curățenie standard', unit: 'm²', qtyKey: 'standardCleanAreaLabor', unitPrice: 30, kind: 'labor', moduleKey: 'standard_cleaning', enabledWhen: { anyQtyKeys: ['standardCleanAreaLabor'] } },
    { stageCode: 'umeda', description: 'Manoperă curățenie profundă', unit: 'm²', qtyKey: 'cleanAreaLabor', unitPrice: 42, kind: 'labor', moduleKey: 'deep_cleaning', enabledWhen: { moduleEnabled: 'deep_cleaning', anyQtyKeys: ['cleanAreaLabor'] } },
    { stageCode: 'bucatarie_bai', description: 'Curățenie profundă bucătărie', unit: 'buc', qtyKey: 'kitchenDeepCleanUnits', unitPrice: 280, kind: 'labor', moduleKey: 'kitchen', enabledWhen: { moduleEnabled: 'kitchen', anyQtyKeys: ['kitchenDeepCleanUnits'] } },
    { stageCode: 'bucatarie_bai', description: 'Curățenie grup sanitar', unit: 'buc', qtyKey: 'bathroomCleanUnits', unitPrice: 180, kind: 'labor', moduleKey: 'bathrooms', enabledWhen: { anyQtyKeys: ['bathroomCleanUnits'] } },
    { stageCode: 'geamuri', description: 'Spălare geamuri', unit: 'buc', qtyKey: 'windowCleanCount', unitPrice: 50, kind: 'labor', moduleKey: 'windows', enabledWhen: { anyQtyKeys: ['windowCleanCount'] } },
    { stageCode: 'special', description: 'Curățenie post-șantier', unit: 'm²', qtyKey: 'postConstructionAreaLabor', unitPrice: 55, kind: 'labor', moduleKey: 'post_construction', enabledWhen: { moduleEnabled: 'post_construction', anyQtyKeys: ['postConstructionAreaLabor'] } },
    { stageCode: 'special', description: 'Evacuare gunoi/deșeuri', unit: 'buc', qtyKey: 'trashRemovalUnits', unitPrice: 65, kind: 'labor', moduleKey: 'trash_removal', enabledWhen: { moduleEnabled: 'trash_removal', anyQtyKeys: ['trashRemovalUnits'] } },
    { stageCode: 'predare', description: 'Verificare finală & predare', unit: 'm²', qtyKey: 'cleanArea', unitPrice: 5, kind: 'labor', moduleKey: 'standard_cleaning' },
  ],
});
