import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

export const climaBlueprint: EstimateBlueprintConfig = baseConfig({
    wizardSteps: ['object', 'plan', 'diagnostic', 'stages', 'review'],
    accessDifficultyImpact: { easy: 1.0, medium: 1.05, difficult: 1.15 },
    urgencyImpact: { urgent: 1.2, emergency: 1.5 },
    planPointTypes: [
      { type: 'indoor', label: 'Unitate interior (Split)', color: '#0ea5e9' },
      { type: 'outdoor', label: 'Unitate exterior', color: '#0284c7' },
      { type: 'route', label: 'Traseu frigorific', color: '#38bdf8' },
    ],
    workModules: [
      {
        key: 'route',
        label: 'Traseu frigorific',
        helpText: 'Conducte de cupru + cablu între unitatea interioară și cea exterioară. Peste 5 m se taxează ca traseu suplimentar.',
        defaultEnabled: true,
        stageCodes: ['inspectie', 'traseu', 'vacuum'],
        fieldKeys: ['routeLengthM', 'wallCoreDrillingCount'],
        section: 'Traseu & drenaj',
      },
      {
        key: 'indoor_outdoor_units',
        label: 'Unități interior / exterior',
        helpText: 'Montajul unităților split. Activați „echipament inclus" dacă oferta conține și aparatele.',
        defaultEnabled: true,
        stageCodes: ['montaj', 'testare'],
        fieldKeys: ['acUnits', 'indoorUnitCount', 'outdoorUnitCount', 'equipmentIncluded'],
        section: 'Echipamente',
      },
      {
        key: 'drain',
        label: 'Drenaj condens',
        helpText: 'Tub de evacuare a condensului de la unitatea interioară. Dacă lungimea lipsește, se folosește lungimea traseului.',
        defaultEnabled: false,
        stageCodes: ['traseu'],
        fieldKeys: ['drainLengthM'],
        section: 'Traseu & drenaj',
      },
      {
        key: 'pump',
        label: 'Pompă condens',
        helpText: 'Pompă pentru evacuarea forțată a condensului când nu există pantă naturală spre exterior.',
        defaultEnabled: false,
        stageCodes: ['traseu'],
        fieldKeys: ['requiresPump'],
        requiresQtyKeys: ['pumpCount'],
        section: 'Traseu & drenaj',
      },
      {
        key: 'height_work',
        label: 'Lucrări la înălțime',
        helpText: 'Montaj la peste 3 m (schelă / nacelă) — crește manopera.',
        defaultEnabled: false,
        stageCodes: ['montaj'],
        fieldKeys: ['heightWork'],
        section: 'Montaj',
      },
      {
        key: 'maintenance',
        label: 'Pachet mentenanță',
        helpText: 'Contract anual de service (curățare filtre, verificare presiune agent).',
        defaultEnabled: false,
        stageCodes: ['mentenanta'],
        fieldKeys: ['maintenancePackage'],
        requiresQtyKeys: ['maintenanceCount'],
        section: 'Service',
      },
    ],
    customFields: [
      {
        key: 'acUnits',
        label: 'Număr unități split',
        type: 'number',
        unit: 'buc',
        required: true,
        defaultValue: 1,
        validation: { min: 1, max: 20 },
        helpText: 'Numărul de aparate de aer condiționat de instalat.',
        placeholder: 'ex. 2',
        section: 'General',
      },
      {
        key: 'routeLengthM',
        label: 'Lungime traseu frigorific',
        type: 'number',
        unit: 'm',
        required: true,
        defaultValue: 5,
        validation: { min: 2 },
        helpText: 'Lungimea totală a conductelor. Peste 5 m se calculează ca traseu suplimentar + dozare freon.',
        placeholder: 'ex. 5',
        warningRules: [
          { when: 'routeLengthM > 5', message: 'Traseu peste 5 m — se adaugă automat traseu suplimentar și dozare freon.' },
        ],
        section: 'General',
      },
      {
        key: 'indoorUnitCount',
        label: 'Unități interior',
        type: 'number',
        unit: 'buc',
        required: false,
        defaultValue: 0,
        helpText: 'Gol = egal cu numărul de split-uri.',
        section: 'Avansat',
      },
      {
        key: 'outdoorUnitCount',
        label: 'Unități exterior',
        type: 'number',
        unit: 'buc',
        required: false,
        defaultValue: 0,
        helpText: 'Gol = egal cu numărul de split-uri (1 pentru multi-split).',
        section: 'Avansat',
      },
      {
        key: 'drainLengthM',
        label: 'Lungime drenaj condens',
        type: 'number',
        unit: 'm',
        required: false,
        defaultValue: 0,
        helpText: 'Gol = se folosește lungimea traseului.',
        section: 'Avansat',
      },
      {
        key: 'wallCoreDrillingCount',
        label: 'Găuri penetrare perete',
        type: 'number',
        unit: 'buc',
        required: false,
        defaultValue: 0,
        helpText: 'Gol = câte una per split.',
        section: 'Avansat',
      },
      {
        key: 'heightWork',
        label: 'Lucrări la înălțime (>3m)',
        type: 'boolean',
        required: false,
        defaultValue: false,
        helpText: 'Montaj exterior la înălțime — crește manopera.',
        warningRules: [
          { when: "heightWork === 'true'", message: 'Lucrări la înălțime — manopera de montaj crește automat cu +25%.' },
        ],
        section: 'Avansat',
      },
      {
        key: 'requiresPump',
        label: 'Pompă condens',
        type: 'boolean',
        required: false,
        defaultValue: false,
        helpText: 'Activați dacă nu există pantă naturală pentru scurgerea condensului.',
        section: 'Avansat',
      },
      {
        key: 'equipmentIncluded',
        label: 'Echipament inclus în ofertă',
        type: 'boolean',
        required: false,
        defaultValue: false,
        helpText: 'Activați dacă oferta conține și aparatele (nu doar montajul).',
        section: 'Avansat',
      },
      {
        key: 'maintenancePackage',
        label: 'Pachet mentenanță anual',
        type: 'boolean',
        required: false,
        defaultValue: false,
        helpText: 'Adaugă un contract anual de service.',
        section: 'Avansat',
      },
    ],
    diagnosticQuestions: [],
    defaultStages: [
      { code: 'inspectie', name: 'Inspecție locație & traseu', kind: 'LABOR', defaultLaborHours: 1, durationDays: 1, checklist: ['Traseu verificat', 'Acces exterior confirmat'], moduleKey: 'route' },
      { code: 'traseu', name: 'Pregătire traseu & drenaj', kind: 'MIXED', defaultLaborHours: 4, durationDays: 1, checklist: ['Găurire perete exterior', 'Tub drenaj montat'], moduleKey: 'route' },
      { code: 'montaj', name: 'Instalare echipamente', kind: 'MIXED', defaultLaborHours: 6, durationDays: 1, checklist: ['Split interior fixat', 'Suport exterior montat'], moduleKey: 'indoor_outdoor_units' },
      { code: 'vacuum', name: 'Vacuum & etanșare', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Vacuum verificat', 'Agent etanș'], moduleKey: 'route' },
      { code: 'testare', name: 'Testare & predare', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Temperatură OK', 'Fără scurgeri agent'], moduleKey: 'indoor_outdoor_units' },
      { code: 'mentenanta', name: 'Pachet mentenanță', kind: 'LABOR', defaultLaborHours: 1, durationDays: 1, checklist: ['Contract service semnat'], optional: true, moduleKey: 'maintenance' },
    ],
    pricingRules: [
      { stageCode: 'inspectie', description: 'Inspecție & plan montaj', unit: 'ore', qtyKey: 'inspectionHours', unitPrice: 180, kind: 'labor', moduleKey: 'route' },
      { stageCode: 'traseu', description: 'Traseu standard (până la 5 m) — material', unit: 'm', qtyKey: 'routeStandardLengthM', unitPrice: 140, wastePct: 5, kind: 'material', moduleKey: 'route' },
      { stageCode: 'traseu', description: 'Traseu standard — lucrări', unit: 'm', qtyKey: 'routeStandardLengthM', unitPrice: 80, kind: 'labor', moduleKey: 'route' },
      { stageCode: 'traseu', description: 'Traseu suplimentar (>5 m) — material', unit: 'm', qtyKey: 'routeExtraLengthM', unitPrice: 165, wastePct: 5, kind: 'material', moduleKey: 'route', enabledWhen: { anyQtyKeys: ['routeExtraLengthM'] } },
      { stageCode: 'traseu', description: 'Traseu suplimentar — lucrări', unit: 'm', qtyKey: 'routeExtraLengthM', unitPrice: 95, kind: 'labor', moduleKey: 'route', enabledWhen: { anyQtyKeys: ['routeExtraLengthM'] } },
      { stageCode: 'traseu', description: 'Dozare freon traseu lung', unit: 'buc', qtyKey: 'freonRechargeQty', unitPrice: 220, kind: 'material', moduleKey: 'route', enabledWhen: { anyQtyKeys: ['freonRechargeQty'] } },
      { stageCode: 'traseu', description: 'Găurire perete (core drilling)', unit: 'buc', qtyKey: 'coreDrillingQty', unitPrice: 350, kind: 'labor', moduleKey: 'route' },
      { stageCode: 'traseu', description: 'Tub drenaj condens', unit: 'm', qtyKey: 'drainLengthM', unitPrice: 35, kind: 'material', moduleKey: 'drain' },
      { stageCode: 'traseu', description: 'Lucrări drenaj condens', unit: 'm', qtyKey: 'drainLengthM', unitPrice: 45, kind: 'labor', moduleKey: 'drain' },
      { stageCode: 'traseu', description: 'Pompă condens', unit: 'buc', qtyKey: 'pumpCount', unitPrice: 420, kind: 'material', moduleKey: 'pump', enabledWhen: { moduleEnabled: 'pump', anyQtyKeys: ['pumpCount'] } },
      { stageCode: 'traseu', description: 'Montaj pompă condens', unit: 'buc', qtyKey: 'pumpCount', unitPrice: 180, kind: 'labor', moduleKey: 'pump', enabledWhen: { moduleEnabled: 'pump', anyQtyKeys: ['pumpCount'] } },
      { stageCode: 'montaj', description: 'Lucrări instalare split AC', unit: 'buc', qtyKey: 'acUnits', unitPrice: 1200, kind: 'labor', moduleKey: 'indoor_outdoor_units', laborUnitPriceMultiplierKey: 'heightMultiplier' },
      { stageCode: 'montaj', description: 'Unitate interior (material)', unit: 'buc', qtyKey: 'indoorEquipmentCount', unitPrice: 3200, kind: 'material', moduleKey: 'indoor_outdoor_units', enabledWhen: { anyQtyKeys: ['indoorEquipmentCount'] } },
      { stageCode: 'montaj', description: 'Unitate exterior (material)', unit: 'buc', qtyKey: 'outdoorEquipmentCount', unitPrice: 4500, kind: 'material', moduleKey: 'indoor_outdoor_units', enabledWhen: { anyQtyKeys: ['outdoorEquipmentCount'] } },
      { stageCode: 'vacuum', description: 'Vacuum & test etanșeitate', unit: 'buc', qtyKey: 'acUnits', unitPrice: 280, kind: 'labor', moduleKey: 'route' },
      { stageCode: 'testare', description: 'Punere în funcțiune & predare', unit: 'buc', qtyKey: 'acUnits', unitPrice: 220, kind: 'labor', moduleKey: 'indoor_outdoor_units' },
      { stageCode: 'mentenanta', description: 'Pachet mentenanță anual', unit: 'buc', qtyKey: 'maintenanceCount', unitPrice: 450, kind: 'labor', moduleKey: 'maintenance', enabledWhen: { moduleEnabled: 'maintenance', anyQtyKeys: ['maintenanceCount'] } },
    ],
});
