import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

/** Estimările de construcție sunt preliminare (MVP) — vezi deriveConstructiiMeasurements.preliminaryEstimate. */
export const constructiiBlueprint: EstimateBlueprintConfig = baseConfig({
  siteTypes: [
    { value: 'house', label: 'Casă individuală' },
    { value: 'duplex', label: 'Duplex / vilă' },
    { value: 'commercial', label: 'Clădire comercială' },
    { value: 'annex', label: 'Anexă / depozit' },
  ],
  planPointTypes: [
    { type: 'foundation', label: 'Fundație beton', color: '#4b5563' },
    { type: 'brick_wall', label: 'Zidărie cărămidă', color: '#991b1b' },
    { type: 'slab', label: 'Placă beton armat', color: '#374151' },
    { type: 'column', label: 'Stâlp susținere', color: '#1f2937' },
  ],
  workModules: [
    {
      key: 'project',
      label: 'Proiect & organizare șantier',
      defaultEnabled: true,
      stageCodes: ['proiect'],
      fieldKeys: ['builtArea', 'storyCount', 'projectDocumentation'],
    },
    {
      key: 'excavation',
      label: 'Terasament & săpături',
      defaultEnabled: true,
      stageCodes: ['terasament'],
      fieldKeys: ['excavationVolumeM3'],
      requiresQtyKeys: ['excavationVolumeM3'],
    },
    {
      key: 'foundation',
      label: 'Fundație & beton',
      defaultEnabled: true,
      stageCodes: ['fundatie'],
      fieldKeys: ['foundationType', 'concreteVolumeM3', 'rebarKg'],
      requiresQtyKeys: ['foundationConcreteM3'],
    },
    {
      key: 'waterproofing',
      label: 'Hidroizolație fundație',
      defaultEnabled: true,
      stageCodes: ['hidroizolare'],
      fieldKeys: [],
      requiresQtyKeys: ['waterproofingArea'],
    },
    {
      key: 'structure',
      label: 'Structură pereți & stâlpi',
      defaultEnabled: true,
      stageCodes: ['structura'],
      fieldKeys: ['wallMaterial', 'masonryVolumeM3'],
      requiresQtyKeys: ['masonryVolumeM3'],
    },
    {
      key: 'slab',
      label: 'Plăci beton',
      defaultEnabled: true,
      stageCodes: ['placa'],
      fieldKeys: ['slabType', 'concreteVolumeM3'],
      requiresQtyKeys: ['slabAreaTotal'],
    },
    {
      key: 'stairs',
      label: 'Scări interioare',
      defaultEnabled: false,
      stageCodes: ['scari'],
      fieldKeys: ['storyCount'],
      requiresQtyKeys: ['stairFlightCount'],
    },
    {
      key: 'roof',
      label: 'Acoperiș',
      defaultEnabled: false,
      stageCodes: ['acoperis'],
      fieldKeys: ['roofIncluded'],
      requiresQtyKeys: ['roofIncludedArea'],
    },
    {
      key: 'utilities',
      label: 'Utilități brute',
      defaultEnabled: false,
      stageCodes: ['utilitati'],
      fieldKeys: ['utilitiesIncluded'],
      requiresQtyKeys: ['utilitiesUnits'],
    },
  ],
  customFields: [
    {
      key: 'builtArea',
      label: 'Suprafață construită',
      type: 'number',
      unit: 'm²',
      required: true,
      validation: { min: 10 },
      helpText: 'Estimare preliminară — necesită proiect tehnic pentru preț final.',
      section: 'General',
    },
    {
      key: 'storyCount',
      label: 'Număr niveluri',
      type: 'number',
      unit: 'buc',
      required: true,
      defaultValue: 1,
      validation: { min: 1, max: 4 },
      warningRules: [{ when: 'storyCount > 2', message: 'Clădire cu peste 2 niveluri — verificare manuală obligatorie.' }],
      section: 'General',
    },
    {
      key: 'foundationType',
      label: 'Tip fundație',
      type: 'select',
      options: ['strip', 'slab', 'pile', 'isolated'],
      required: false,
      defaultValue: 'strip',
      warningRules: [{ when: "foundationType === 'pile'", message: 'Fundație pe piloți — estimare preliminară, necesită studiu geotehnic.' }],
      section: 'Fundație',
    },
    {
      key: 'wallMaterial',
      label: 'Material pereți',
      type: 'select',
      options: ['brick', 'bca', 'concrete', 'wood_frame'],
      required: false,
      defaultValue: 'bca',
      section: 'Structură',
    },
    {
      key: 'slabType',
      label: 'Tip placă beton',
      type: 'select',
      options: ['monolithic', 'prefab', 'wood'],
      required: false,
      defaultValue: 'monolithic',
      section: 'Structură',
    },
    {
      key: 'excavationVolumeM3',
      label: 'Volum săpătură',
      type: 'number',
      unit: 'm³',
      required: false,
      defaultValue: 0,
      helpText: 'Opțional — altfel se estimează 0,45 m³/m².',
      section: 'Terasament',
    },
    {
      key: 'concreteVolumeM3',
      label: 'Volum beton total',
      type: 'number',
      unit: 'm³',
      required: false,
      defaultValue: 0,
      section: 'Beton',
    },
    {
      key: 'rebarKg',
      label: 'Armătură oțel',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      helpText: 'Introduceți kg total sau lăsați calcul automat (90 kg/m³ beton).',
      section: 'Beton',
    },
    {
      key: 'masonryVolumeM3',
      label: 'Volum zidărie',
      type: 'number',
      unit: 'm³',
      required: false,
      defaultValue: 0,
      section: 'Structură',
    },
    {
      key: 'roofIncluded',
      label: 'Include acoperiș',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Acoperiș',
    },
    {
      key: 'utilitiesIncluded',
      label: 'Include utilități brute',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Utilități',
    },
    {
      key: 'projectDocumentation',
      label: 'Documentație proiect',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Proiect',
    },
  ],
  diagnosticQuestions: [
    { key: 'builtArea', label: 'Suprafață construită (m²)', type: 'number' },
    { key: 'storyCount', label: 'Număr niveluri clădire', type: 'number' },
    { key: 'foundationType', label: 'Tip fundație', type: 'select', options: ['strip', 'slab', 'pile', 'isolated'] },
  ],
  defaultStages: [
    { code: 'proiect', name: 'Proiect & organizare șantier', kind: 'LABOR', defaultLaborHours: 16, durationDays: 3, checklist: ['Plan șantier', 'Autorizații'], moduleKey: 'project' },
    { code: 'terasament', name: 'Terasament & săpături', kind: 'MIXED', defaultLaborHours: 24, durationDays: 4, checklist: ['Decopertare', 'Săpătură'], moduleKey: 'excavation' },
    { code: 'fundatie', name: 'Fundație, armare & beton', kind: 'MIXED', defaultLaborHours: 32, durationDays: 6, checklist: ['Cofrare', 'Armătură', 'Turnare beton'], moduleKey: 'foundation' },
    { code: 'hidroizolare', name: 'Hidroizolație fundație', kind: 'MIXED', defaultLaborHours: 8, durationDays: 2, checklist: ['Bitum', 'Membrană'], moduleKey: 'waterproofing' },
    { code: 'structura', name: 'Pereți, stâlpi & zidărie', kind: 'MIXED', defaultLaborHours: 40, durationDays: 10, checklist: ['Zidărie', 'Stâlpi', 'Grinzi'], moduleKey: 'structure' },
    { code: 'placa', name: 'Plăci beton armat', kind: 'MIXED', defaultLaborHours: 24, durationDays: 5, checklist: ['Cofrare placă', 'Armare', 'Turnare'], moduleKey: 'slab' },
    { code: 'scari', name: 'Scări interioare', kind: 'MIXED', defaultLaborHours: 16, durationDays: 3, checklist: ['Cofrare trepte', 'Finisare'], optional: true, moduleKey: 'stairs' },
    { code: 'acoperis', name: 'Acoperiș', kind: 'MIXED', defaultLaborHours: 20, durationDays: 5, checklist: ['Structură acoperiș', 'Învelitoare'], optional: true, moduleKey: 'roof' },
    { code: 'utilitati', name: 'Utilități brute', kind: 'MIXED', defaultLaborHours: 12, durationDays: 3, checklist: ['Apă', 'Canal', 'Electric'], optional: true, moduleKey: 'utilities' },
    { code: 'predare', name: 'Predare șantier & control', kind: 'LABOR', defaultLaborHours: 4, durationDays: 1, checklist: ['Recepție parțială', 'Proces verbal'], moduleKey: 'project' },
  ],
  pricingRules: [
    { stageCode: 'proiect', description: 'Proiectare & organizare șantier', unit: 'ore', qtyKey: 'projectHours', unitPrice: 320, kind: 'labor', moduleKey: 'project' },
    { stageCode: 'proiect', description: 'Documentație proiect tehnic', unit: 'buc', qtyKey: 'projectDocumentationUnits', unitPrice: 8500, kind: 'labor', moduleKey: 'project', enabledWhen: { anyQtyKeys: ['projectDocumentationUnits'] } },
    { stageCode: 'terasament', description: 'Terasament & săpătură mecanizată', unit: 'm³', qtyKey: 'excavationVolumeM3', unitPrice: 95, kind: 'labor', moduleKey: 'excavation', enabledWhen: { anyQtyKeys: ['excavationVolumeM3'] } },
    { stageCode: 'fundatie', description: 'Beton armat fundație', unit: 'm³', qtyKey: 'foundationConcreteM3', unitPrice: 1650, kind: 'material', moduleKey: 'foundation', enabledWhen: { anyQtyKeys: ['foundationConcreteM3'] } },
    { stageCode: 'fundatie', description: 'Armătură oțel fundație & structură', unit: 'buc', qtyKey: 'rebarKg', unitPrice: 18, kind: 'material', moduleKey: 'foundation', enabledWhen: { anyQtyKeys: ['rebarKg'] } },
    { stageCode: 'fundatie', description: 'Manoperă cofrare & turnare beton', unit: 'm³', qtyKey: 'concreteVolumeM3', unitPrice: 480, kind: 'labor', moduleKey: 'foundation', enabledWhen: { anyQtyKeys: ['concreteVolumeM3'] } },
    { stageCode: 'hidroizolare', description: 'Hidroizolație fundație', unit: 'm²', qtyKey: 'waterproofingArea', unitPrice: 85, kind: 'material', moduleKey: 'waterproofing', enabledWhen: { anyQtyKeys: ['waterproofingArea'] } },
    { stageCode: 'structura', description: 'Zidărie structurală', unit: 'm³', qtyKey: 'masonryVolumeM3', unitPrice: 520, kind: 'labor', moduleKey: 'structure', enabledWhen: { anyQtyKeys: ['masonryVolumeM3'] } },
    { stageCode: 'placa', description: 'Placă beton armat (manoperă + beton)', unit: 'm²', qtyKey: 'slabAreaTotal', unitPrice: 420, kind: 'labor', moduleKey: 'slab', enabledWhen: { anyQtyKeys: ['slabAreaTotal'] } },
    { stageCode: 'scari', description: 'Construcție scară interioară', unit: 'buc', qtyKey: 'stairFlightCount', unitPrice: 6500, kind: 'labor', moduleKey: 'stairs', enabledWhen: { anyQtyKeys: ['stairFlightCount'] } },
    { stageCode: 'acoperis', description: 'Structură & învelitoare acoperiș', unit: 'm²', qtyKey: 'roofIncludedArea', unitPrice: 380, kind: 'labor', moduleKey: 'roof', enabledWhen: { moduleEnabled: 'roof', anyQtyKeys: ['roofIncludedArea'] } },
    { stageCode: 'utilitati', description: 'Trasee utilități brute (apă/canal/electric)', unit: 'buc', qtyKey: 'utilitiesUnits', unitPrice: 4500, kind: 'labor', moduleKey: 'utilities', enabledWhen: { moduleEnabled: 'utilities', anyQtyKeys: ['utilitiesUnits'] } },
    { stageCode: 'predare', description: 'Predare șantier & control calitate', unit: 'buc', qtyKey: 'handoverUnits', unitPrice: 1200, kind: 'labor', moduleKey: 'project' },
  ],
});
