import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

export const elektrikaBlueprint: EstimateBlueprintConfig = baseConfig({
    wizardSteps: ['object', 'diagnostic', 'stages', 'review'],
    accessDifficultyImpact: { easy: 1.0, medium: 1.05, difficult: 1.15 },
    urgencyImpact: { urgent: 1.25, emergency: 1.8 },
    planPointTypes: [
      { type: 'socket', label: 'Priză', color: '#f59e0b' },
      { type: 'switch', label: 'Întrerupător', color: '#eab308' },
      { type: 'light', label: 'Lumină', color: '#fbbf24' },
      { type: 'panel', label: 'Tablou electric', color: '#ef4444' },
    ],
    workModules: [
      {
        key: 'project',
        label: 'Proiect & scheme',
        defaultEnabled: true,
        stageCodes: ['proiect'],
        fieldKeys: ['roomCount', 'groundingRequired'],
      },
      {
        key: 'chasing',
        label: 'Ștrobire & găuri',
        defaultEnabled: true,
        stageCodes: ['demontare', 'trasee'],
        fieldKeys: ['wallChasingM', 'wallMaterial', 'cableReplace'],
      },
      {
        key: 'cabling',
        label: 'Cablare',
        defaultEnabled: true,
        stageCodes: ['cablare'],
        fieldKeys: ['cableReplace', 'dedicatedLinesCount'],
      },
      {
        key: 'panel',
        label: 'Tablou electric',
        defaultEnabled: true,
        stageCodes: ['tablou'],
        fieldKeys: ['newPanel', 'panelModules', 'voltageStabilizer'],
      },
      {
        key: 'devices',
        label: 'Aparataj (prize, întrerupătoare, lumini)',
        defaultEnabled: true,
        stageCodes: ['aparataj'],
        fieldKeys: ['socketCount', 'switchCount', 'lightPointCount'],
      },
      {
        key: 'low_voltage',
        label: 'Slabă tensiune',
        defaultEnabled: false,
        stageCodes: ['cablare'],
        fieldKeys: ['dedicatedLinesCount'],
        requiresQtyKeys: ['lowVoltageLineCount'],
      },
      {
        key: 'smart_home',
        label: 'Smart home',
        defaultEnabled: false,
        stageCodes: ['aparataj'],
        fieldKeys: ['smartHomeRequired'],
        requiresQtyKeys: ['smartHomeCount'],
      },
      {
        key: 'testing',
        label: 'Testare & predare',
        defaultEnabled: true,
        stageCodes: ['testare'],
        fieldKeys: [],
      },
    ],
    customFields: [
      {
        key: 'newPanel',
        label: 'Tablou electric nou',
        type: 'boolean',
        required: false,
        defaultValue: false,
        section: 'Tablou',
      },
      {
        key: 'cableReplace',
        label: 'Înlocuire cabluri',
        type: 'boolean',
        required: false,
        defaultValue: false,
        section: 'Cablare',
      },
      {
        key: 'roomCount',
        label: 'Număr camere',
        type: 'number',
        unit: 'buc',
        required: true,
        defaultValue: 1,
        validation: { min: 1, max: 30 },
        helpText: 'Include living, dormitoare, bucătărie, hol.',
        section: 'General',
      },
      {
        key: 'socketCount',
        label: 'Număr prize',
        type: 'number',
        unit: 'buc',
        required: false,
        defaultValue: 0,
        section: 'Aparataj',
      },
      {
        key: 'switchCount',
        label: 'Număr întrerupătoare',
        type: 'number',
        unit: 'buc',
        required: false,
        defaultValue: 0,
        section: 'Aparataj',
      },
      {
        key: 'lightPointCount',
        label: 'Puncte lumini',
        type: 'number',
        unit: 'buc',
        required: false,
        defaultValue: 0,
        section: 'Aparataj',
      },
      {
        key: 'dedicatedLinesCount',
        label: 'Linii dedicate (plită, boiler, AC)',
        type: 'number',
        unit: 'buc',
        required: false,
        defaultValue: 0,
        section: 'Cablare',
      },
      {
        key: 'wallChasingM',
        label: 'Ștrobire pereți',
        type: 'number',
        unit: 'm',
        required: false,
        defaultValue: 0,
        section: 'Ștrobire',
      },
      {
        key: 'wallMaterial',
        label: 'Material pereți',
        type: 'select',
        options: ['gips', 'bca', 'caramida', 'beton'],
        required: false,
        defaultValue: 'gips',
        helpText: 'Betonul crește semnificativ manopera la ștrobire.',
        section: 'Ștrobire',
      },
      {
        key: 'panelModules',
        label: 'Module tablou (automate/RCD)',
        type: 'number',
        unit: 'buc',
        required: false,
        defaultValue: 12,
        validation: { min: 4, max: 48 },
        section: 'Tablou',
      },
      {
        key: 'smartHomeRequired',
        label: 'Integrare smart home',
        type: 'boolean',
        required: false,
        defaultValue: false,
        section: 'Smart home',
      },
      {
        key: 'voltageStabilizer',
        label: 'Stabilizator de tensiune / Стабилизатор напряжения',
        type: 'boolean',
        required: false,
        defaultValue: false,
        section: 'Tablou',
      },
      {
        key: 'groundingRequired',
        label: 'Instalare/Verificare împământare / Устройство/Проверка заземления',
        type: 'boolean',
        required: false,
        defaultValue: false,
        section: 'General',
      },
    ],
    diagnosticQuestions: [
      { key: 'roomCount', label: 'Număr camere', type: 'number' },
    ],
    defaultStages: [
      { code: 'proiect', name: 'Proiect & traseu', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Plan aprobat', 'Grupuri definite'], moduleKey: 'project' },
      { code: 'demontare', name: 'Demontare instalație veche', kind: 'LABOR', defaultLaborHours: 3, durationDays: 1, checklist: ['Alimentare oprită', 'Etichetare circuite'], optional: true, moduleKey: 'chasing' },
      { code: 'trasee', name: 'Ștrobire & doze', kind: 'LABOR', defaultLaborHours: 5, durationDays: 1, checklist: ['Trasee marcate', 'Doze montate'], moduleKey: 'chasing' },
      { code: 'cablare', name: 'Cablare', kind: 'MIXED', defaultLaborHours: 8, durationDays: 2, checklist: ['Secțiuni corecte', 'Etichetare cabluri'], moduleKey: 'cabling' },
      { code: 'tablou', name: 'Montaj tablou', kind: 'MIXED', defaultLaborHours: 3, durationDays: 1, checklist: ['Protecții montate', 'Legare PE'], moduleKey: 'panel' },
      { code: 'aparataj', name: 'Montaj aparataj', kind: 'MIXED', defaultLaborHours: 4, durationDays: 1, checklist: ['Prize montate', 'Întrerupătoare testate'], moduleKey: 'devices' },
      { code: 'testare', name: 'Testare & predare', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Test RCD', 'Etichete linii'], moduleKey: 'testing' },
    ],
    pricingRules: [
      { stageCode: 'proiect', description: 'Proiectare scheme electrice', unit: 'ore', qtyKey: 'projectHours', unitPrice: 200, kind: 'labor', moduleKey: 'project' },
      { stageCode: 'demontare', description: 'Demontare cabluri vechi', unit: 'ore', qtyKey: 'demolitionHours', unitPrice: 160, kind: 'labor', moduleKey: 'chasing', enabledWhen: { anyQtyKeys: ['demolitionHours'] } },
      { stageCode: 'trasee', description: 'Ștrobire pereți (cost ajustat material)', unit: 'm', qtyKey: 'wallChasingCostM', unitPrice: 95, kind: 'labor', moduleKey: 'chasing', enabledWhen: { moduleEnabled: 'chasing', anyQtyKeys: ['wallChasingCostM'] } },
      { stageCode: 'cablare', description: 'Cablu + tub', unit: 'm', qtyKey: 'cableLengthM', unitPrice: 45, wastePct: 10, kind: 'material', moduleKey: 'cabling' },
      { stageCode: 'cablare', description: 'Manoperă cablare (ajustată material)', unit: 'm', qtyKey: 'cableLengthMLabor', unitPrice: 35, kind: 'labor', moduleKey: 'cabling' },
      { stageCode: 'cablare', description: 'Linii dedicate (plită, boiler, AC)', unit: 'buc', qtyKey: 'lowVoltageLineCount', unitPrice: 380, kind: 'labor', moduleKey: 'low_voltage', enabledWhen: { moduleEnabled: 'low_voltage', anyQtyKeys: ['lowVoltageLineCount'] } },
      { stageCode: 'tablou', description: 'Tablou electric (material)', unit: 'buc', qtyKey: 'panelCount', unitPrice: 1800, kind: 'material', moduleKey: 'panel', enabledWhen: { anyQtyKeys: ['panelCount'] } },
      { stageCode: 'tablou', description: 'Manoperă montaj tablou', unit: 'buc', qtyKey: 'panelCount', unitPrice: 650, kind: 'labor', moduleKey: 'panel', enabledWhen: { anyQtyKeys: ['panelCount'] } },
      { stageCode: 'tablou', description: 'Module automate / RCD', unit: 'buc', qtyKey: 'panelModules', unitPrice: 85, kind: 'material', moduleKey: 'panel' },
      { stageCode: 'aparataj', description: 'Punct electric (priză/întrerupător/lumină)', unit: 'buc', qtyKey: 'electricPointsLabor', unitPrice: 220, kind: 'labor', moduleKey: 'devices' },
      { stageCode: 'aparataj', description: 'Integrare smart home', unit: 'buc', qtyKey: 'smartHomeCount', unitPrice: 1200, kind: 'labor', moduleKey: 'smart_home', enabledWhen: { moduleEnabled: 'smart_home', anyQtyKeys: ['smartHomeCount'] } },
      { stageCode: 'testare', description: 'Test RCD & predare', unit: 'buc', qtyKey: 'testingPointCount', unitPrice: 45, kind: 'labor', moduleKey: 'testing' },
    ],
});
