import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

export const fatadeBlueprint: EstimateBlueprintConfig = baseConfig({
  accessDifficultyImpact: { easy: 1.0, medium: 1.15, difficult: 1.25 },
  urgencyImpact: { urgent: 1.15, emergency: 1.3 },
  planPointTypes: [
    { type: 'wall_facade', label: 'Perete fațadă', color: '#ea580c' },
    { type: 'window_slope', label: 'Glaf ferestre', color: '#c2410c' },
    { type: 'scaffolding', label: 'Schelă fațadă', color: '#9a3412' },
  ],
  workModules: [
    {
      key: 'scaffolding',
      label: 'Schelă & siguranță',
      helpText: 'Montaj schelă metalică pentru lucru la înălțime.',
      defaultEnabled: true,
      stageCodes: ['schela'],
      fieldKeys: ['scaffoldingArea'],
    },
    {
      key: 'facade_demolition',
      label: 'Demontare tencuială veche',
      helpText: 'Înlăturarea tencuielii vechi de pe fațadă înainte de aplicarea sistemului termoizolant. Activați pentru reabilitări de fațade existente.',
      defaultEnabled: false,
      stageCodes: ['demolare_tencuiala'],
      fieldKeys: ['oldPlasterArea'],
      requiresQtyKeys: ['oldPlasterArea'],
    },
    {
      key: 'preparation',
      label: 'Pregătire fațadă',
      helpText: 'Curățare suport, reparații locale, grunduire înainte de izolație.',
      defaultEnabled: true,
      stageCodes: ['pregatire'],
      fieldKeys: [],
    },
    {
      key: 'repairs',
      label: 'Reparații locale (fisuri, găuri)',
      helpText: 'Plombări locale ale fisurilor, găurilor și zonelor degradate cu plastură de ciment înainte de aplicarea izolației.',
      defaultEnabled: false,
      stageCodes: ['reparatii'],
      fieldKeys: ['repairArea'],
      requiresQtyKeys: ['repairArea'],
    },
    {
      key: 'insulation',
      label: 'Izolație termică',
      helpText: 'Sistem termoizolant cu polistiren și plasă armată.',
      defaultEnabled: true,
      stageCodes: ['izolatie'],
      fieldKeys: ['insulationThicknessCm'],
    },
    {
      key: 'mesh',
      label: 'Plasă & armare',
      helpText: 'Plasă din fibră de sticlă și masă de șpaclu peste izolație.',
      defaultEnabled: true,
      stageCodes: ['armare'],
      fieldKeys: [],
    },
    {
      key: 'slopes',
      label: 'Glafuri & colțare',
      helpText: 'Profile de colț, glafuri ferestre, picurător.',
      defaultEnabled: true,
      stageCodes: ['glafuri_coltari'],
      fieldKeys: ['windowSlopeLengthM'],
      requiresQtyKeys: ['windowSlopeLengthM'],
    },
    {
      key: 'decorative_plaster',
      label: 'Tencuială decorativă',
      helpText:
        'Strat final structurat (baramin / silicat) peste izolație. Pentru culoare finală activați și «Vopsire fațadă».',
      defaultEnabled: true,
      stageCodes: ['decorativa'],
      fieldKeys: ['decorativePlasterArea'],
    },
    {
      key: 'painting',
      label: 'Vopsire fațadă',
      helpText:
        'Vopsea peste tencuiala decorativă sau direct pe fațadă. Dacă suprafața decorativă = 0 m², se vopsește toată fațada.',
      defaultEnabled: true,
      stageCodes: ['decorativa'],
      fieldKeys: [],
    },
    {
      key: 'plinth',
      label: 'Soclu (cokol)',
      helpText: 'Partea inferioară a fațadei, sub nivelul ferestrelor — finisată separat cu XPS.',
      defaultEnabled: false,
      stageCodes: ['soclu'],
      fieldKeys: ['basePlinthArea'],
      requiresQtyKeys: ['basePlinthArea'],
    },
    {
      key: 'window_sills',
      label: 'Glafuri exterioare (pervaze)',
      helpText: 'Glaful metalic / piatră de sub fereastră, exterior — separat de glafurile vinkăl (verticale).',
      defaultEnabled: false,
      stageCodes: ['glafuri_exterioare'],
      fieldKeys: ['exteriorSillLengthM'],
      requiresQtyKeys: ['exteriorSillLengthM'],
    },
    {
      key: 'facade_drip_edge',
      label: 'Picurător fațadă (profil de sus)',
      helpText: 'Profil metalic în partea de sus a fațadei care împiedică apa să curgă înapoi pe perete. Tipic = perimetrul clădirii.',
      defaultEnabled: false,
      stageCodes: ['picurator'],
      fieldKeys: ['facadeDripEdgeLengthM'],
      requiresQtyKeys: ['facadeDripEdgeLengthM'],
    },
  ],
  customFields: [
    {
      key: 'facadeArea',
      label: 'Suprafață fațadă',
      type: 'number',
      unit: 'm²',
      required: true,
      validation: { min: 1 },
      helpText: 'Suma pereților exteriori minus ferestrele și ușile.',
      placeholder: 'ex. 120',
      section: 'General',
    },
    {
      key: 'buildingHeightM',
      label: 'Înălțime clădire',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      helpText: 'Peste 9 m se aplică automat coeficient de înălțime 1.2× la costul lucrărilor.',
      placeholder: 'ex. 6',
      section: 'General',
    },
    {
      key: 'insulationThicknessCm',
      label: 'Grosime izolație termică (cm)',
      type: 'number',
      required: false,
      defaultValue: 10,
      validation: { min: 1, max: 30 },
      helpText: 'Standard recomandat pentru Moldova: 10 cm polistiren.',
      warningRules: [
        {
          when: 'insulationThicknessCm < 5',
          message: 'Grosime sub 5 cm — performanța termică nu va respecta standardele.',
        },
      ],
      section: 'General',
    },
    {
      key: 'scaffoldingArea',
      label: 'Suprafață schelă',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Lăsați 0 — se folosește automat suprafața fațadei.',
      section: 'Avansat',
    },
    {
      key: 'windowSlopeLengthM',
      label: 'Lungime totală glafuri ferestre',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      helpText: 'Suma perimetrelor ferestrelor (≈ 5 m per fereastră standard). Lăsați 0 dacă se calculează din plan.',
      section: 'Avansat',
    },
    {
      key: 'decorativePlasterArea',
      label: 'Suprafață tencuială decorativă',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: '0 = toată fațada se vopsește direct, fără tencuială decorativă.',
      section: 'Avansat',
    },
    {
      key: 'basePlinthArea',
      label: 'Suprafață soclu',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Activați modulul "Soclu" și introduceți suprafața (≈ înălțime soclu × perimetru).',
      section: 'Avansat',
    },
    {
      key: 'oldPlasterArea',
      label: 'Suprafață tencuială veche de demontat',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Suprafața totală de tencuială existentă care trebuie înlăturată înainte de izolație. Tipic = suprafața fațadei pentru reabilitări complete.',
      section: 'Avansat',
    },
    {
      key: 'repairArea',
      label: 'Suprafață reparații locale',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Estimare suprafață fisuri, găuri, zone degradate (≈ 5-15% din suprafața totală pentru clădiri vechi).',
      section: 'Avansat',
    },
    {
      key: 'exteriorSillLengthM',
      label: 'Lungime glafuri exterioare (pervaze ferestre)',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      helpText: 'Suma lățimilor ferestrelor unde se montează glaful metalic exterior (~ 1 m per fereastră standard).',
      section: 'Avansat',
    },
    {
      key: 'facadeDripEdgeLengthM',
      label: 'Lungime picurător sus',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      helpText: 'Lungimea profilului picurător de sus = perimetrul clădirii la nivelul cornișei.',
      section: 'Avansat',
    },
    {
      key: 'wallMaterial',
      label: 'Material perete',
      type: 'select',
      options: ['brick', 'bca', 'panel', 'wood_frame'],
      required: false,
      defaultValue: 'brick',
      helpText: 'Influențează numărul de dibluri/m²: cărămidă ×1.0, BCA ×1.33, panou ×0.83, lemn ×0.5.',
      section: 'Avansat',
    },
  ],
  diagnosticQuestions: [],
  defaultStages: [
    { code: 'schela', name: 'Montaj schelă metalică', kind: 'LABOR', defaultLaborHours: 6, durationDays: 1, checklist: ['Instalare baze schelă', 'Ancorare în pereți', 'Plase protecție'], moduleKey: 'scaffolding' },
    { code: 'demolare_tencuiala', name: 'Demontare tencuială veche', kind: 'LABOR', defaultLaborHours: 12, durationDays: 2, checklist: ['Înlăturare mecanică tencuială', 'Curățare suport până la cărămidă', 'Evacuare moloz'], optional: true, moduleKey: 'facade_demolition' },
    { code: 'reparatii', name: 'Reparații locale', kind: 'MIXED', defaultLaborHours: 4, durationDays: 1, checklist: ['Plombare fisuri', 'Astupare găuri', 'Nivelare zone degradate'], optional: true, moduleKey: 'repairs' },
    { code: 'pregatire', name: 'Curățare & grunduire', kind: 'LABOR', defaultLaborHours: 6, durationDays: 1, checklist: ['Curățare suport', 'Reparații locale', 'Grund'], moduleKey: 'preparation' },
    { code: 'izolatie', name: 'Montaj izolație & dibluri', kind: 'MIXED', defaultLaborHours: 18, durationDays: 4, checklist: ['Aplicare adeziv', 'Lipire plăci', 'Dibluire mecanică'], moduleKey: 'insulation' },
    { code: 'armare', name: 'Plasă fibră & masă armare', kind: 'MIXED', defaultLaborHours: 12, durationDays: 3, checklist: ['Montaj colțare', 'Aplicare masă șpaclu', 'Înglobare plasă'], moduleKey: 'mesh' },
    { code: 'glafuri_coltari', name: 'Glafuri, colțare, picurător', kind: 'MIXED', defaultLaborHours: 6, durationDays: 2, checklist: ['Profile colț', 'Glafuri ferestre', 'Picurător'], moduleKey: 'slopes' },
    { code: 'decorativa', name: 'Tencuială decorativă / vopsire', kind: 'MIXED', defaultLaborHours: 10, durationDays: 2, checklist: ['Tencuială structurată', 'Strat final'], moduleKey: 'decorative_plaster' },
    { code: 'soclu', name: 'Soclu XPS / tencuială', kind: 'MIXED', defaultLaborHours: 5, durationDays: 1, checklist: ['Placare XPS soclu', 'Tencuială soclu'], optional: true, moduleKey: 'plinth' },
    { code: 'glafuri_exterioare', name: 'Glafuri exterioare ferestre', kind: 'MIXED', defaultLaborHours: 4, durationDays: 1, checklist: ['Montaj glaf metalic / piatră', 'Etanșare margini'], optional: true, moduleKey: 'window_sills' },
    { code: 'picurator', name: 'Picurător profil de sus', kind: 'MIXED', defaultLaborHours: 3, durationDays: 1, checklist: ['Montaj profil picurător', 'Etanșare îmbinări'], optional: true, moduleKey: 'facade_drip_edge' },
    { code: 'predare', name: 'Predare & recepție', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Verificare calitate', 'Predare client'], moduleKey: 'preparation' },
  ],
  pricingRules: [
    { stageCode: 'schela', description: 'Montaj schelă metalică (linie separată)', unit: 'm²', qtyKey: 'scaffoldingArea', unitPrice: 42, kind: 'labor', moduleKey: 'scaffolding' },
    { stageCode: 'schela', description: 'Închiriere schelă (lunar estimat)', unit: 'm²', qtyKey: 'scaffoldingArea', unitPrice: 18, kind: 'material', moduleKey: 'scaffolding' },
    { stageCode: 'demolare_tencuiala', description: 'Lucrări demontare tencuială veche', unit: 'm²', qtyKey: 'oldPlasterArea', unitPrice: 35, kind: 'labor', moduleKey: 'facade_demolition', enabledWhen: { moduleEnabled: 'facade_demolition', anyQtyKeys: ['oldPlasterArea'] } },
    { stageCode: 'demolare_tencuiala', description: 'Evacuare moloz (saci/transport)', unit: 'm²', qtyKey: 'oldPlasterArea', unitPrice: 12, kind: 'material', moduleKey: 'facade_demolition', enabledWhen: { moduleEnabled: 'facade_demolition', anyQtyKeys: ['oldPlasterArea'] } },
    { stageCode: 'reparatii', description: 'Plastură ciment & adeziv (material)', unit: 'm²', qtyKey: 'repairArea', unitPrice: 45, wastePct: 8, kind: 'material', moduleKey: 'repairs', enabledWhen: { moduleEnabled: 'repairs', anyQtyKeys: ['repairArea'] } },
    { stageCode: 'reparatii', description: 'Lucrări reparații locale', unit: 'm²', qtyKey: 'repairArea', unitPrice: 120, kind: 'labor', moduleKey: 'repairs', enabledWhen: { moduleEnabled: 'repairs', anyQtyKeys: ['repairArea'] } },
    { stageCode: 'pregatire', description: 'Grund & pregătire suport', unit: 'm²', qtyKey: 'preparationAreaLabor', unitPrice: 22, kind: 'labor', moduleKey: 'preparation' },
    { stageCode: 'izolatie', description: 'Izolație termică (material)', unit: 'm³', qtyKey: 'insulationVolumeM3', unitPrice: 420, wastePct: 5, kind: 'material', moduleKey: 'insulation' },
    { stageCode: 'izolatie', description: 'Lucrări montaj izolație', unit: 'm²', qtyKey: 'facadeAreaLabor', unitPrice: 130, kind: 'labor', moduleKey: 'insulation' },
    { stageCode: 'izolatie', description: 'Dibluri mecanice fațadă', unit: 'buc', qtyKey: 'dowelQty', unitPrice: 2.5, kind: 'material', moduleKey: 'insulation' },
    { stageCode: 'armare', description: 'Plasă fibră de sticlă', unit: 'm²', qtyKey: 'meshArea', unitPrice: 28, wastePct: 8, kind: 'material', moduleKey: 'mesh' },
    { stageCode: 'armare', description: 'Lucrări armare & masă adeziv', unit: 'm²', qtyKey: 'meshAreaLabor', unitPrice: 65, kind: 'labor', moduleKey: 'mesh' },
    { stageCode: 'glafuri_coltari', description: 'Profile colț & glafuri', unit: 'm', qtyKey: 'windowSlopeLengthM', unitPrice: 85, kind: 'material', moduleKey: 'slopes', enabledWhen: { anyQtyKeys: ['windowSlopeLengthM'] } },
    { stageCode: 'glafuri_coltari', description: 'Lucrări glafuri & colțare', unit: 'm', qtyKey: 'windowSlopeLengthM', unitPrice: 55, kind: 'labor', moduleKey: 'slopes', enabledWhen: { anyQtyKeys: ['windowSlopeLengthM'] } },
    { stageCode: 'decorativa', description: 'Tencuială decorativă (material)', unit: 'm²', qtyKey: 'decorativePlasterArea', unitPrice: 38, wastePct: 10, kind: 'material', moduleKey: 'decorative_plaster', enabledWhen: { anyQtyKeys: ['decorativePlasterArea'] } },
    { stageCode: 'decorativa', description: 'Lucrări tencuială decorativă', unit: 'm²', qtyKey: 'decorativePlasterAreaLabor', unitPrice: 90, kind: 'labor', moduleKey: 'decorative_plaster', enabledWhen: { anyQtyKeys: ['decorativePlasterArea'] } },
    { stageCode: 'decorativa', description: 'Vopsea fațadă (material)', unit: 'm²', qtyKey: 'paintingArea', unitPrice: 25, wastePct: 8, kind: 'material', moduleKey: 'painting' },
    { stageCode: 'decorativa', description: 'Lucrări vopsire fațadă', unit: 'm²', qtyKey: 'paintingAreaLabor', unitPrice: 35, kind: 'labor', moduleKey: 'painting' },
    { stageCode: 'soclu', description: 'XPS soclu (material)', unit: 'm²', qtyKey: 'basePlinthArea', unitPrice: 95, kind: 'material', moduleKey: 'plinth', enabledWhen: { anyQtyKeys: ['basePlinthArea'] } },
    { stageCode: 'soclu', description: 'Lucrări soclu', unit: 'm²', qtyKey: 'basePlinthAreaLabor', unitPrice: 75, kind: 'labor', moduleKey: 'plinth', enabledWhen: { anyQtyKeys: ['basePlinthArea'] } },
    { stageCode: 'glafuri_exterioare', description: 'Glaf exterior (material)', unit: 'm', qtyKey: 'exteriorSillLengthM', unitPrice: 95, wastePct: 5, kind: 'material', moduleKey: 'window_sills', enabledWhen: { moduleEnabled: 'window_sills', anyQtyKeys: ['exteriorSillLengthM'] } },
    { stageCode: 'glafuri_exterioare', description: 'Lucrări montaj glaf exterior', unit: 'm', qtyKey: 'exteriorSillLengthM', unitPrice: 55, kind: 'labor', moduleKey: 'window_sills', enabledWhen: { moduleEnabled: 'window_sills', anyQtyKeys: ['exteriorSillLengthM'] } },
    { stageCode: 'picurator', description: 'Profil picurător (material)', unit: 'm', qtyKey: 'facadeDripEdgeLengthM', unitPrice: 30, wastePct: 5, kind: 'material', moduleKey: 'facade_drip_edge', enabledWhen: { moduleEnabled: 'facade_drip_edge', anyQtyKeys: ['facadeDripEdgeLengthM'] } },
    { stageCode: 'picurator', description: 'Lucrări montaj picurător', unit: 'm', qtyKey: 'facadeDripEdgeLengthM', unitPrice: 25, kind: 'labor', moduleKey: 'facade_drip_edge', enabledWhen: { moduleEnabled: 'facade_drip_edge', anyQtyKeys: ['facadeDripEdgeLengthM'] } },
    { stageCode: 'predare', description: 'Recepție & predare lucrare', unit: 'm²', qtyKey: 'facadeArea', unitPrice: 5, kind: 'labor', moduleKey: 'preparation' },
  ],
});
