import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

export const fatadeBlueprint: EstimateBlueprintConfig = baseConfig({
  planPointTypes: [
    { type: 'wall_facade', label: 'Perete fațadă', color: '#ea580c' },
    { type: 'window_slope', label: 'Glaf ferestre', color: '#c2410c' },
    { type: 'scaffolding', label: 'Schelă fațadă', color: '#9a3412' },
  ],
  workModules: [
    {
      key: 'scaffolding',
      label: 'Schelă & siguranță',
      defaultEnabled: true,
      stageCodes: ['schela'],
      fieldKeys: ['scaffoldingArea', 'buildingHeightM'],
    },
    {
      key: 'preparation',
      label: 'Pregătire fațadă',
      defaultEnabled: true,
      stageCodes: ['pregatire'],
      fieldKeys: ['surfaceCondition'],
    },
    {
      key: 'insulation',
      label: 'Izolație termică',
      defaultEnabled: true,
      stageCodes: ['izolatie'],
      fieldKeys: ['insulationThicknessCm', 'insulationType'],
    },
    {
      key: 'mesh',
      label: 'Plasă & armare',
      defaultEnabled: true,
      stageCodes: ['armare'],
      fieldKeys: [],
    },
    {
      key: 'slopes',
      label: 'Glafuri & colțare',
      defaultEnabled: true,
      stageCodes: ['glafuri_coltari'],
      fieldKeys: ['windowSlopeLengthM'],
      requiresQtyKeys: ['windowSlopeLengthM'],
    },
    {
      key: 'decorative_plaster',
      label: 'Tencuială decorativă',
      defaultEnabled: true,
      stageCodes: ['decorativa'],
      fieldKeys: ['decorativePlasterArea'],
    },
    {
      key: 'painting',
      label: 'Vopsire fațadă',
      defaultEnabled: false,
      stageCodes: ['decorativa'],
      fieldKeys: [],
    },
    {
      key: 'plinth',
      label: 'Soclu / cokol',
      defaultEnabled: false,
      stageCodes: ['soclu'],
      fieldKeys: ['basePlinthArea'],
      requiresQtyKeys: ['basePlinthArea'],
    },
  ],
  customFields: [
    {
      key: 'facadeArea',
      label: 'Suprafață fațadă',
      type: 'number',
      unit: 'm²',
      required: true,
      validation: { min: 1 },
      section: 'General',
    },
    {
      key: 'scaffoldingArea',
      label: 'Suprafață schelă',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Dacă lipsește, se folosește suprafața fațadei.',
      section: 'Schelă',
    },
    {
      key: 'insulationThicknessCm',
      label: 'Grosime izolație',
      type: 'number',
      required: false,
      defaultValue: 10,
      validation: { min: 1, max: 30 },
      warningRules: [
        {
          when: 'insulationThicknessCm < 5',
          message: 'Grosime sub 5 cm — verificați conformitatea termică.',
        },
      ],
      section: 'Izolație',
    },
    {
      key: 'insulationType',
      label: 'Tip izolație',
      type: 'select',
      options: ['polistiren', 'vata_bazaltica', 'xps'],
      required: false,
      defaultValue: 'polistiren',
      section: 'Izolație',
    },
    {
      key: 'windowSlopeLengthM',
      label: 'Lungime glafuri ferestre',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      section: 'Detalii',
    },
    {
      key: 'decorativePlasterArea',
      label: 'Suprafață tencuială decorativă',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Lăsat 0 = se folosește suprafața fațadei la vopsire.',
      section: 'Finisaj',
    },
    {
      key: 'basePlinthArea',
      label: 'Suprafață soclu',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      section: 'Soclu',
    },
    {
      key: 'buildingHeightM',
      label: 'Înălțime clădire',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      helpText: 'Peste 9 m se aplică coeficient 1.2 la manoperă.',
      section: 'General',
    },
    {
      key: 'surfaceCondition',
      label: 'Stare suprafață',
      type: 'select',
      options: ['new', 'old', 'damaged'],
      required: false,
      defaultValue: 'new',
      section: 'Pregătire',
    },
  ],
  diagnosticQuestions: [
    { key: 'facadeArea', label: 'Suprafață fațadă (m²)', type: 'number' },
    { key: 'scaffoldingArea', label: 'Suprafață schelă (m²)', type: 'number' },
  ],
  defaultStages: [
    { code: 'schela', name: 'Montaj schelă metalică', kind: 'LABOR', defaultLaborHours: 6, durationDays: 1, checklist: ['Instalare baze schelă', 'Ancorare în pereți', 'Plase protecție'], moduleKey: 'scaffolding' },
    { code: 'pregatire', name: 'Curățare & grunduire', kind: 'LABOR', defaultLaborHours: 6, durationDays: 1, checklist: ['Curățare suport', 'Reparații locale', 'Grund'], moduleKey: 'preparation' },
    { code: 'izolatie', name: 'Montaj izolație & dibeuri', kind: 'MIXED', defaultLaborHours: 18, durationDays: 4, checklist: ['Aplicare adeziv', 'Lipire plăci', 'Dibluire mecanică'], moduleKey: 'insulation' },
    { code: 'armare', name: 'Plasă fibră & masă armare', kind: 'MIXED', defaultLaborHours: 12, durationDays: 3, checklist: ['Montaj colțare', 'Aplicare masă șpaclu', 'Înglobare plasă'], moduleKey: 'mesh' },
    { code: 'glafuri_coltari', name: 'Glafuri, colțare, picurător', kind: 'MIXED', defaultLaborHours: 6, durationDays: 2, checklist: ['Profile colț', 'Glafuri ferestre', 'Picurător'], moduleKey: 'slopes' },
    { code: 'decorativa', name: 'Tencuială decorativă / vopsire', kind: 'MIXED', defaultLaborHours: 10, durationDays: 2, checklist: ['Tencuială structurată', 'Strat final'], moduleKey: 'decorative_plaster' },
    { code: 'soclu', name: 'Soclu XPS / tencuială', kind: 'MIXED', defaultLaborHours: 5, durationDays: 1, checklist: ['Placare XPS soclu', 'Tencuială soclu'], optional: true, moduleKey: 'plinth' },
    { code: 'predare', name: 'Predare & recepție', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Verificare calitate', 'Predare client'], moduleKey: 'preparation' },
  ],
  pricingRules: [
    { stageCode: 'schela', description: 'Montaj schelă metalică (linie separată)', unit: 'm²', qtyKey: 'scaffoldingArea', unitPrice: 42, kind: 'labor', moduleKey: 'scaffolding' },
    { stageCode: 'schela', description: 'Închiriere schelă (lunar estimat)', unit: 'm²', qtyKey: 'scaffoldingArea', unitPrice: 18, kind: 'material', moduleKey: 'scaffolding' },
    { stageCode: 'pregatire', description: 'Grund & pregătire suport', unit: 'm²', qtyKey: 'preparationAreaLabor', unitPrice: 22, kind: 'labor', moduleKey: 'preparation' },
    { stageCode: 'izolatie', description: 'Izolație termică (material)', unit: 'm³', qtyKey: 'insulationVolumeM3', unitPrice: 420, wastePct: 5, kind: 'material', moduleKey: 'insulation' },
    { stageCode: 'izolatie', description: 'Manoperă montaj izolație', unit: 'm²', qtyKey: 'facadeAreaLabor', unitPrice: 130, kind: 'labor', moduleKey: 'insulation' },
    { stageCode: 'izolatie', description: 'Dibeuri mecanice fațadă', unit: 'buc', qtyKey: 'dowelQty', unitPrice: 2.5, kind: 'material', moduleKey: 'insulation' },
    { stageCode: 'armare', description: 'Plasă fibră de sticlă', unit: 'm²', qtyKey: 'meshArea', unitPrice: 28, wastePct: 8, kind: 'material', moduleKey: 'mesh' },
    { stageCode: 'armare', description: 'Manoperă armare & masă adeziv', unit: 'm²', qtyKey: 'meshAreaLabor', unitPrice: 65, kind: 'labor', moduleKey: 'mesh' },
    { stageCode: 'glafuri_coltari', description: 'Profile colț & glafuri', unit: 'm', qtyKey: 'windowSlopeLengthM', unitPrice: 85, kind: 'material', moduleKey: 'slopes', enabledWhen: { anyQtyKeys: ['windowSlopeLengthM'] } },
    { stageCode: 'glafuri_coltari', description: 'Manoperă glafuri & colțare', unit: 'm', qtyKey: 'windowSlopeLengthM', unitPrice: 55, kind: 'labor', moduleKey: 'slopes', enabledWhen: { anyQtyKeys: ['windowSlopeLengthM'] } },
    { stageCode: 'decorativa', description: 'Tencuială decorativă (material)', unit: 'm²', qtyKey: 'decorativePlasterArea', unitPrice: 38, wastePct: 10, kind: 'material', moduleKey: 'decorative_plaster', enabledWhen: { anyQtyKeys: ['decorativePlasterArea'] } },
    { stageCode: 'decorativa', description: 'Manoperă tencuială decorativă', unit: 'm²', qtyKey: 'decorativePlasterAreaLabor', unitPrice: 90, kind: 'labor', moduleKey: 'decorative_plaster', enabledWhen: { anyQtyKeys: ['decorativePlasterArea'] } },
    { stageCode: 'decorativa', description: 'Vopsea fațadă (material)', unit: 'm²', qtyKey: 'paintingArea', unitPrice: 25, wastePct: 8, kind: 'material', moduleKey: 'painting' },
    { stageCode: 'decorativa', description: 'Manoperă vopsire fațadă', unit: 'm²', qtyKey: 'paintingAreaLabor', unitPrice: 35, kind: 'labor', moduleKey: 'painting' },
    { stageCode: 'soclu', description: 'XPS soclu (material)', unit: 'm²', qtyKey: 'basePlinthArea', unitPrice: 95, kind: 'material', moduleKey: 'plinth', enabledWhen: { anyQtyKeys: ['basePlinthArea'] } },
    { stageCode: 'soclu', description: 'Manoperă soclu', unit: 'm²', qtyKey: 'basePlinthAreaLabor', unitPrice: 75, kind: 'labor', moduleKey: 'plinth', enabledWhen: { anyQtyKeys: ['basePlinthArea'] } },
    { stageCode: 'predare', description: 'Recepție & predare lucrare', unit: 'm²', qtyKey: 'facadeArea', unitPrice: 5, kind: 'labor', moduleKey: 'preparation' },
  ],
});
