import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

/** Servicii hardware: reparație, asamblare, diagnostic, upgrade. Fără plan 2D. */
export const itHardwareBlueprint: EstimateBlueprintConfig = baseConfig({
  wizardSteps: ['object', 'diagnostic', 'stages', 'review'],
  urgencyImpact: { urgent: 1.15, emergency: 1.3 },
  siteTypes: [
    { value: 'office', label: 'Birou / Oficiu' },
    { value: 'enterprise', label: 'Companie / Enterprise' },
    { value: 'residential', label: 'Rezidențial / Acasă' },
    { value: 'remote', label: 'Remote / Asistență la distanță' },
  ],
  planPointTypes: [],
  workModules: [
    {
      key: 'diagnostic_hw',
      label: 'Diagnostic hardware',
      defaultEnabled: true,
      stageCodes: ['diagnostic'],
      fieldKeys: ['deviceCount', 'deviceType'],
      helpText: 'Identificare și evaluare defecțiuni componente hardware.',
    },
    {
      key: 'repair',
      label: 'Reparație componente',
      defaultEnabled: false,
      stageCodes: ['reparatie'],
      fieldKeys: ['simpleRepairCount', 'mediumRepairCount', 'complexRepairCount'],
      requiresQtyKeys: ['repairCount'],
      helpText: 'Reparație placă de bază, sursă, componente defecte.',
    },
    {
      key: 'assembly',
      label: 'Asamblare PC / stație',
      defaultEnabled: false,
      stageCodes: ['asamblare'],
      fieldKeys: ['assemblyCount'],
      requiresQtyKeys: ['assemblyCount'],
      helpText: 'Asamblare computer de la zero, alegere componente, testare.',
    },
    {
      key: 'upgrade',
      label: 'Upgrade componente',
      defaultEnabled: false,
      stageCodes: ['upgrade'],
      fieldKeys: ['upgradeCount'],
      requiresQtyKeys: ['upgradeCount'],
      helpText: 'Înlocuire RAM, SSD, GPU, PSU, cooler etc.',
    },
    {
      key: 'cleaning_hw',
      label: 'Curățare & mentenanță',
      defaultEnabled: false,
      stageCodes: ['mentenanta'],
      fieldKeys: ['cleaningHwCount'],
      requiresQtyKeys: ['cleaningHwCount'],
      helpText: 'Curățare praf, înlocuire pastă termică, verificare ventilație.',
    },
    {
      key: 'os_install',
      label: 'Instalare SO & drivere',
      defaultEnabled: false,
      stageCodes: ['instalare'],
      fieldKeys: ['osInstallCount', 'osType'],
      requiresQtyKeys: ['osInstallCount'],
      helpText: 'Instalare Windows/Linux, drivere, configurare BIOS/UEFI.',
    },
    {
      key: 'data_recovery',
      label: 'Recuperare date',
      defaultEnabled: false,
      stageCodes: ['recuperare'],
      fieldKeys: ['logicRecoveryCount', 'physicalRecoveryCount', 'severeRecoveryCount'],
      requiresQtyKeys: ['dataRecoveryCount'],
      helpText: 'Recuperare date de pe HDD/SSD defecte sau șterse accidental.',
    },
    {
      key: 'peripheral',
      label: 'Periferice & rețea locală',
      defaultEnabled: false,
      stageCodes: ['periferice'],
      fieldKeys: ['peripheralCount', 'peripheralType'],
      requiresQtyKeys: ['peripheralCount'],
      helpText: 'Configurare imprimante, routere, switch-uri, UPS.',
    },
  ],
  customFields: [
    {
      key: 'deviceCount',
      label: 'Număr dispozitive de diagnosticat',
      type: 'number',
      unit: 'buc',
      required: true,
      defaultValue: 1,
      validation: { min: 1 },
      section: 'Dispozitive',
    },
    {
      key: 'deviceType',
      label: 'Tip dispozitiv principal',
      type: 'select',
      options: ['Desktop / PC', 'Laptop', 'Server', 'Stație de lucru', 'All-in-One', 'NAS / Storage'],
      required: true,
      defaultValue: 'Desktop / PC',
      section: 'Dispozitive',
    },
    {
      key: 'simpleRepairCount',
      label: 'Reparații simple (condensatoare, PCB)',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Reparație',
    },
    {
      key: 'mediumRepairCount',
      label: 'Reparații medii (reballing, chip BGA, VRM)',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Reparație',
    },
    {
      key: 'complexRepairCount',
      label: 'Reparații complexe (placă stratificată, micro-lipituri)',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Reparație',
    },
    {
      key: 'assemblyCount',
      label: 'PC-uri de asamblat',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Asamblare',
    },
    {
      key: 'upgradeCount',
      label: 'Componente de upgrade',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Upgrade',
    },
    {
      key: 'cleaningHwCount',
      label: 'Dispozitive de curățat',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Mentenanță',
    },
    {
      key: 'osInstallCount',
      label: 'Sisteme de instalat',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Software',
    },
    {
      key: 'osType',
      label: 'Sistem de operare',
      type: 'select',
      options: ['Windows 10/11', 'Windows Server', 'Linux (Ubuntu/Debian)', 'Linux (RHEL/CentOS)', 'macOS'],
      required: false,
      defaultValue: 'Windows 10/11',
      section: 'Software',
    },
    {
      key: 'logicRecoveryCount',
      label: 'Recuperare logică (fișiere șterse, format)',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Recuperare',
    },
    {
      key: 'physicalRecoveryCount',
      label: 'Recuperare fizică ușoară (sectoare defecte)',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Recuperare',
    },
    {
      key: 'severeRecoveryCount',
      label: 'Recuperare fizică gravă (clean room / capete citire)',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Recuperare',
    },
    {
      key: 'peripheralCount',
      label: 'Periferice',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Periferice',
    },
    {
      key: 'peripheralType',
      label: 'Tip periferic',
      type: 'select',
      options: ['Imprimantă / multifuncțional', 'Router / switch', 'UPS', 'Scanner', 'Alt dispozitiv'],
      required: false,
      defaultValue: 'Imprimantă / multifuncțional',
      section: 'Periferice',
    },
    {
      key: 'warrantyMonths',
      label: 'Garanție (luni)',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 3,
      validation: { min: 1, max: 24 },
      section: 'General',
    },
  ],
  diagnosticQuestions: [
    { key: 'deviceCount', label: 'Număr dispozitive', type: 'number' },
    { key: 'deviceType', label: 'Tip dispozitiv principal', type: 'select', options: ['Desktop / PC', 'Laptop', 'Server', 'Stație de lucru', 'All-in-One', 'NAS / Storage'] },
    { key: 'urgency', label: 'Nivel urgență', type: 'select', options: ['Normal', 'Urgent', 'Critic'] },
  ],
  defaultStages: [
    { code: 'diagnostic', name: 'Diagnostic inițial', kind: 'LABOR', defaultLaborHours: 1, durationDays: 1, checklist: ['Verificare vizuală', 'Test componentă', 'Raport diagnostic'], moduleKey: 'diagnostic_hw' },
    { code: 'reparatie', name: 'Reparație componente', kind: 'LABOR', defaultLaborHours: 3, durationDays: 2, checklist: ['Reparație', 'Test funcționare'], optional: true, moduleKey: 'repair' },
    { code: 'asamblare', name: 'Asamblare PC', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Alegere componente', 'Asamblare', 'Testare'], optional: true, moduleKey: 'assembly' },
    { code: 'upgrade', name: 'Upgrade componente', kind: 'MATERIAL', defaultLaborHours: 1, durationDays: 1, checklist: ['Înlocuire', 'Test compatibilitate'], optional: true, moduleKey: 'upgrade' },
    { code: 'mentenanta', name: 'Curățare & mentenanță', kind: 'LABOR', defaultLaborHours: 1, durationDays: 1, checklist: ['Curățare praf', 'Pastă termică', 'Verificare ventilație'], optional: true, moduleKey: 'cleaning_hw' },
    { code: 'instalare', name: 'Instalare SO & drivere', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Backup date', 'Instalare SO', 'Drivere', 'Actualizări'], optional: true, moduleKey: 'os_install' },
    { code: 'recuperare', name: 'Recuperare date', kind: 'LABOR', defaultLaborHours: 4, durationDays: 2, checklist: ['Analiza dispozitiv', 'Recuperare', 'Verificare integritate'], optional: true, moduleKey: 'data_recovery' },
    { code: 'periferice', name: 'Configurare periferice', kind: 'LABOR', defaultLaborHours: 1, durationDays: 1, checklist: ['Instalare', 'Configurare', 'Test'], optional: true, moduleKey: 'peripheral' },
  ],
  pricingRules: [
    // Diagnostic
    { stageCode: 'diagnostic', description: 'Diagnostic hardware per dispozitiv', unit: 'buc', qtyKey: 'deviceCount', unitPrice: 150, kind: 'labor', moduleKey: 'diagnostic_hw' },

    // Reparație
    { stageCode: 'reparatie', description: 'Reparație simplă (condensator / PCB)', unit: 'buc', qtyKey: 'simpleRepairCount', unitPrice: 250, kind: 'labor', moduleKey: 'repair', enabledWhen: { moduleEnabled: 'repair', anyQtyKeys: ['simpleRepairCount'] } },
    { stageCode: 'reparatie', description: 'Reparație medie (BGA / VRM)', unit: 'buc', qtyKey: 'mediumRepairCount', unitPrice: 600, kind: 'labor', moduleKey: 'repair', enabledWhen: { moduleEnabled: 'repair', anyQtyKeys: ['mediumRepairCount'] } },
    { stageCode: 'reparatie', description: 'Reparație complexă (stratificație)', unit: 'buc', qtyKey: 'complexRepairCount', unitPrice: 1200, kind: 'labor', moduleKey: 'repair', enabledWhen: { moduleEnabled: 'repair', anyQtyKeys: ['complexRepairCount'] } },
    { stageCode: 'reparatie', description: 'Componente/materiale reparație', unit: 'buc', qtyKey: 'repairCount', unitPrice: 200, wastePct: 15, kind: 'material', moduleKey: 'repair', enabledWhen: { moduleEnabled: 'repair', anyQtyKeys: ['repairCount'] } },

    // Asamblare
    { stageCode: 'asamblare', description: 'Asamblare PC (lucrări)', unit: 'buc', qtyKey: 'assemblyCount', unitPrice: 350, kind: 'labor', moduleKey: 'assembly', enabledWhen: { moduleEnabled: 'assembly', anyQtyKeys: ['assemblyCount'] } },

    // Upgrade
    { stageCode: 'upgrade', description: 'Upgrade componentă (lucrări)', unit: 'buc', qtyKey: 'upgradeCount', unitPrice: 180, kind: 'labor', moduleKey: 'upgrade', enabledWhen: { moduleEnabled: 'upgrade', anyQtyKeys: ['upgradeCount'] } },
    { stageCode: 'upgrade', description: 'Componente upgrade (material)', unit: 'buc', qtyKey: 'upgradeCount', unitPrice: 600, wastePct: 10, kind: 'material', moduleKey: 'upgrade', enabledWhen: { moduleEnabled: 'upgrade', anyQtyKeys: ['upgradeCount'] } },

    // Curățare
    { stageCode: 'mentenanta', description: 'Curățare & pastă termică (per dispozitiv)', unit: 'buc', qtyKey: 'cleaningHwCount', unitPrice: 120, kind: 'labor', moduleKey: 'cleaning_hw', enabledWhen: { moduleEnabled: 'cleaning_hw', anyQtyKeys: ['cleaningHwCount'] } },
    { stageCode: 'mentenanta', description: 'Materiale curățare (pastă, spray)', unit: 'buc', qtyKey: 'cleaningHwCount', unitPrice: 25, wastePct: 30, kind: 'material', moduleKey: 'cleaning_hw', enabledWhen: { moduleEnabled: 'cleaning_hw', anyQtyKeys: ['cleaningHwCount'] } },

    // Instalare SO
    { stageCode: 'instalare', description: 'Instalare SO & config BIOS (lucrări)', unit: 'buc', qtyKey: 'osInstallCount', unitPrice: 200, kind: 'labor', moduleKey: 'os_install', enabledWhen: { moduleEnabled: 'os_install', anyQtyKeys: ['osInstallCount'] } },
    { stageCode: 'instalare', description: 'Licență SO (dacă necesar)', unit: 'buc', qtyKey: 'osLicenseCount', unitPrice: 450, kind: 'material', moduleKey: 'os_install', enabledWhen: { moduleEnabled: 'os_install', anyQtyKeys: ['osLicenseCount'] } },

    // Recuperare date
    { stageCode: 'recuperare', description: 'Recuperare logică', unit: 'buc', qtyKey: 'logicRecoveryCount', unitPrice: 500, kind: 'labor', moduleKey: 'data_recovery', enabledWhen: { moduleEnabled: 'data_recovery', anyQtyKeys: ['logicRecoveryCount'] } },
    { stageCode: 'recuperare', description: 'Recuperare fizică ușoară', unit: 'buc', qtyKey: 'physicalRecoveryCount', unitPrice: 1500, kind: 'labor', moduleKey: 'data_recovery', enabledWhen: { moduleEnabled: 'data_recovery', anyQtyKeys: ['physicalRecoveryCount'] } },
    { stageCode: 'recuperare', description: 'Recuperare fizică gravă (clean room)', unit: 'buc', qtyKey: 'severeRecoveryCount', unitPrice: 3500, kind: 'labor', moduleKey: 'data_recovery', enabledWhen: { moduleEnabled: 'data_recovery', anyQtyKeys: ['severeRecoveryCount'] } },

    // Periferice
    { stageCode: 'periferice', description: 'Configurare periferic', unit: 'buc', qtyKey: 'peripheralCount', unitPrice: 100, kind: 'labor', moduleKey: 'peripheral', enabledWhen: { moduleEnabled: 'peripheral', anyQtyKeys: ['peripheralCount'] } },
  ],
  defaultLaborRate: 250,
  defaultMarginPct: 20,
});