import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

/** Wizard pentru rețele, cablare structurată, CCTV și infrastructură server. Fără web design/development. */
export const itNetworksBlueprint: EstimateBlueprintConfig = baseConfig({
  wizardSteps: ['object', 'diagnostic', 'stages', 'review'],
  urgencyImpact: { urgent: 1.2, emergency: 1.5 },
  siteTypes: [
    { value: 'office', label: 'Birou / Oficiu' },
    { value: 'enterprise', label: 'Companie / Enterprise' },
    { value: 'residential', label: 'Rezidențial / Smart Home' },
  ],
  planPointTypes: [
    { type: 'ethernet', label: 'Port rețea RJ45', color: '#6366f1' },
    { type: 'ap', label: 'Access Point Wi-Fi', color: '#4f46e5' },
    { type: 'camera', label: 'Cameră IP', color: '#4338ca' },
    { type: 'rack', label: 'Rack / switch', color: '#3730a3' },
  ],
  workModules: [
    {
      key: 'site_survey',
      label: 'Audit & inspectare locație',
      defaultEnabled: false,
      stageCodes: ['analiza'],
      fieldKeys: ['siteSurveyRequired', 'documentationRequired'],
    },
    {
      key: 'network_cabling',
      label: 'Cablare structurată',
      defaultEnabled: true,
      stageCodes: ['infrastructura'],
      fieldKeys: ['networkPoints', 'avgCableLengthPerPort', 'apCount'],
      requiresQtyKeys: ['networkPoints'],
    },
    {
      key: 'cameras',
      label: 'Camere IP / NVR',
      defaultEnabled: false,
      stageCodes: ['securitate'],
      fieldKeys: ['cameraCount'],
      requiresQtyKeys: ['cameraCount'],
    },
    {
      key: 'servers',
      label: 'Servere & stații (configurare)',
      defaultEnabled: false,
      stageCodes: ['infrastructura'],
      fieldKeys: ['serversToConfigure', 'workstationsToConfigure'],
    },
    {
      key: 'security',
      label: 'Securitate & firewall',
      defaultEnabled: false,
      stageCodes: ['securitate'],
      fieldKeys: [],
    },
    {
      key: 'hardware_components',
      label: 'Componente hardware (montaj fizic)',
      defaultEnabled: false,
      stageCodes: ['hardware'],
      fieldKeys: ['serversToAssemble', 'workstationsToAssemble', 'rackUnits'],
    },
    {
      key: 'migration',
      label: 'Migrare date',
      defaultEnabled: false,
      stageCodes: ['migrare'],
      fieldKeys: ['migrationRequired'],
      requiresQtyKeys: ['migrationUnits'],
    },
    {
      key: 'commissioning',
      label: 'Punere în funcțiune & testare',
      defaultEnabled: false,
      stageCodes: ['testare'],
      fieldKeys: ['commissioningRequired'],
    },
    {
      key: 'sla',
      label: 'SLA / suport',
      defaultEnabled: false,
      stageCodes: ['suport'],
      fieldKeys: ['slaRequired'],
      requiresQtyKeys: ['slaUnits'],
    },
  ],
  customFields: [
    {
      key: 'networkPoints',
      label: 'Porturi rețea (RJ45)',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Rețea',
    },
    {
      key: 'avgCableLengthPerPort',
      label: 'Lungime cablu per port (m)',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 20,
      helpText: 'Lungime medie cablu UTP per port. Default: 20 m.',
      section: 'Rețea',
    },
    {
      key: 'apCount',
      label: 'Access Points Wi-Fi',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Rețea',
    },
    {
      key: 'cameraCount',
      label: 'Camere IP',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Securitate',
    },
    {
      key: 'serversToConfigure',
      label: 'Servere de configurat',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Infrastructură',
    },
    {
      key: 'workstationsToConfigure',
      label: 'Stații de lucru de configurat',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Infrastructură',
    },
    {
      key: 'serversToAssemble',
      label: 'Servere de asamblat fizic',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Hardware',
    },
    {
      key: 'workstationsToAssemble',
      label: 'Stații de lucru de asamblat fizic',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Hardware',
    },
    {
      key: 'rackUnits',
      label: 'Unități rack (U)',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Hardware',
    },
    {
      key: 'siteSurveyRequired',
      label: 'Audit și inspecție prealabilă',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'General',
    },
    {
      key: 'commissioningRequired',
      label: 'Punere în funcțiune extinsă',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'General',
    },
    {
      key: 'documentationRequired',
      label: 'Documentație și protocoale testare',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Suport',
    },
    {
      key: 'migrationRequired',
      label: 'Migrare date necesară',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Migrare',
    },
    {
      key: 'slaRequired',
      label: 'SLA / suport inclus',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Suport',
    },
  ],
  diagnosticQuestions: [
    { key: 'networkPoints', label: 'Porturi rețea (RJ45)', type: 'number' },
    { key: 'cameraCount', label: 'Camere IP', type: 'number' },
  ],
  defaultStages: [
    { code: 'analiza', name: 'Analiză & inspectare locație', kind: 'LABOR', defaultLaborHours: 8, durationDays: 2, checklist: ['Audit teren', 'Plan amplasare'], optional: true, moduleKey: 'site_survey' },
    { code: 'infrastructura', name: 'Infrastructură & rețea', kind: 'MIXED', defaultLaborHours: 12, durationDays: 3, checklist: ['Cablare', 'Montare prize', 'Wi-Fi', 'Configurare echipamente'], moduleKey: 'network_cabling' },
    { code: 'securitate', name: 'Configurare securitate', kind: 'LABOR', defaultLaborHours: 8, durationDays: 2, checklist: ['Configurare firewall', 'Securizare porturi'], optional: true, moduleKey: 'security' },
    { code: 'hardware', name: 'Montaj componente hardware', kind: 'MIXED', defaultLaborHours: 8, durationDays: 2, checklist: ['Asamblare rack', 'Ghidaje cabluri'], optional: true, moduleKey: 'hardware_components' },
    { code: 'migrare', name: 'Migrare date rețea', kind: 'LABOR', defaultLaborHours: 8, durationDays: 2, checklist: ['Securizare date', 'Migrare configurări'], optional: true, moduleKey: 'migration' },
    { code: 'testare', name: 'Punere în funcțiune & testare', kind: 'LABOR', defaultLaborHours: 8, durationDays: 2, checklist: ['Testare continuitate', 'Masurare pierderi semnal', 'Protocoale predare'], optional: true, moduleKey: 'commissioning' },
    { code: 'instruire', name: 'Instruire & predare proiect', kind: 'LABOR', defaultLaborHours: 4, durationDays: 1, checklist: ['Training personal', 'Instrucțiuni utilizare'], optional: true, moduleKey: 'site_survey' },
    { code: 'suport', name: 'SLA & suport rețea', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Predare documentație SLA'], optional: true, moduleKey: 'sla' },
  ],
  pricingRules: [
    { stageCode: 'analiza', description: 'Inspectare și auditare rețea (manoperă)', unit: 'ore', qtyKey: 'analysisHours', unitPrice: 350, kind: 'labor', moduleKey: 'site_survey', enabledWhen: { moduleEnabled: 'site_survey' } },
    { stageCode: 'infrastructura', description: 'Cablare structurată Cat6 (manoperă/port)', unit: 'buc', qtyKey: 'networkPoints', unitPrice: 110, kind: 'labor', moduleKey: 'network_cabling', enabledWhen: { anyQtyKeys: ['networkPoints'] } },
    { stageCode: 'infrastructura', description: 'Cablu UTP Cat6 (material)', unit: 'm', qtyKey: 'networkCableM', unitPrice: 15, wastePct: 20, kind: 'material', moduleKey: 'network_cabling', enabledWhen: { anyQtyKeys: ['networkCableM'] } },
    { stageCode: 'infrastructura', description: 'Montaj Access Point Wi-Fi', unit: 'buc', qtyKey: 'apCount', unitPrice: 280, kind: 'labor', moduleKey: 'network_cabling', enabledWhen: { anyQtyKeys: ['apCount'] } },
    { stageCode: 'infrastructura', description: 'Configurare server (software)', unit: 'buc', qtyKey: 'serversToConfigure', unitPrice: 3500, kind: 'labor', moduleKey: 'servers', enabledWhen: { anyQtyKeys: ['serversToConfigure'] } },
    { stageCode: 'infrastructura', description: 'Configurare stație de lucru', unit: 'buc', qtyKey: 'workstationsToConfigure', unitPrice: 450, kind: 'labor', moduleKey: 'servers', enabledWhen: { anyQtyKeys: ['workstationsToConfigure'] } },
    { stageCode: 'securitate', description: 'SSL, firewall & securitate rețea', unit: 'buc', qtyKey: 'projectUnits', unitPrice: 2500, kind: 'labor', moduleKey: 'security', enabledWhen: { moduleEnabled: 'security' } },
    { stageCode: 'securitate', description: 'Montaj cameră IP', unit: 'buc', qtyKey: 'cameraCount', unitPrice: 380, kind: 'labor', moduleKey: 'cameras', enabledWhen: { anyQtyKeys: ['cameraCount'] } },
    { stageCode: 'hardware', description: 'Asamblare fizică server / PC', unit: 'buc', qtyKey: 'serversToAssemble', unitPrice: 600, kind: 'labor', moduleKey: 'hardware_components', enabledWhen: { moduleEnabled: 'hardware_components', anyQtyKeys: ['serversToAssemble'] } },
    { stageCode: 'hardware', description: 'Reparare / diagnostic hardware stație', unit: 'buc', qtyKey: 'workstationsToAssemble', unitPrice: 350, kind: 'labor', moduleKey: 'hardware_components', enabledWhen: { moduleEnabled: 'hardware_components', anyQtyKeys: ['workstationsToAssemble'] } },
    { stageCode: 'hardware', description: 'Organizare și aranjare rack', unit: 'buc', qtyKey: 'rackUnits', unitPrice: 120, kind: 'labor', moduleKey: 'hardware_components', enabledWhen: { moduleEnabled: 'hardware_components', anyQtyKeys: ['rackUnits'] } },
    { stageCode: 'migrare', description: 'Migrare date sisteme', unit: 'buc', qtyKey: 'migrationUnits', unitPrice: 4500, kind: 'labor', moduleKey: 'migration', enabledWhen: { moduleEnabled: 'migration', anyQtyKeys: ['migrationUnits'] } },
    { stageCode: 'testare', description: 'Punere în funcțiune & testare rețea', unit: 'ore', qtyKey: 'testingHours', unitPrice: 300, kind: 'labor', moduleKey: 'commissioning', enabledWhen: { moduleEnabled: 'commissioning' } },
    { stageCode: 'instruire', description: 'Instruire personal & predare documentație', unit: 'ore', qtyKey: 'trainingHours', unitPrice: 250, kind: 'labor', moduleKey: 'site_survey', enabledWhen: { moduleEnabled: 'site_survey' } },
    { stageCode: 'suport', description: 'Abonament lunar SLA / suport', unit: 'buc', qtyKey: 'slaUnits', unitPrice: 3500, kind: 'labor', moduleKey: 'sla', enabledWhen: { moduleEnabled: 'sla', anyQtyKeys: ['slaUnits'] } },
  ],
  defaultLaborRate: 350,
  defaultMarginPct: 15,
});
