import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

/** Wizard fără plan 2D implicit — pasul plan se activează când itDirection = network (vezi planWizardEnabled). */
export const itNetworksBlueprint: EstimateBlueprintConfig = baseConfig({
  wizardSteps: ['object', 'diagnostic', 'stages', 'review'],
  urgencyImpact: { urgent: 1.2, emergency: 1.5 },
  siteTypes: [
    { value: 'office', label: 'Birou / Oficiu' },
    { value: 'enterprise', label: 'Companie / Enterprise' },
    { value: 'startup', label: 'Startup / Proiect Nou' },
    { value: 'ecommerce', label: 'Magazin Online' },
    { value: 'residential', label: 'Rezidențial / Smart Home' },
  ],
  planPointTypes: [
    { type: 'ethernet', label: 'Port rețea RJ45', color: '#6366f1' },
    { type: 'ap', label: 'Access Point Wi-Fi', color: '#4f46e5' },
    { type: 'camera', label: 'Cameră IP', color: '#4338ca' },
    { type: 'rack', label: 'Rack / switch', color: '#3730a3' },
  ],
  workModules: [
    {
      key: 'audit',
      label: 'Audit & specificații',
      defaultEnabled: true,
      stageCodes: ['analiza'],
      fieldKeys: ['projectScope', 'itDirection'],
    },
    {
      key: 'web_design',
      label: 'Design UI/UX',
      defaultEnabled: true,
      stageCodes: ['design'],
      fieldKeys: ['pagesCount', 'customDesign'],
    },
    {
      key: 'frontend',
      label: 'Dezvoltare frontend',
      defaultEnabled: true,
      stageCodes: ['dezvoltare'],
      fieldKeys: ['pagesCount', 'multilingual'],
    },
    {
      key: 'backend',
      label: 'Backend & API',
      defaultEnabled: false,
      stageCodes: ['backend_dev'],
      fieldKeys: ['backendComplexity'],
      requiresQtyKeys: ['hasBackendCount'],
    },
    {
      key: 'cms',
      label: 'CMS',
      defaultEnabled: false,
      stageCodes: ['cms_dev'],
      fieldKeys: ['hasCMS'],
      requiresQtyKeys: ['hasCmsCount'],
    },
    {
      key: 'ecommerce',
      label: 'E-commerce',
      defaultEnabled: false,
      stageCodes: ['ecommerce_dev'],
      fieldKeys: ['hasEcommerce'],
      requiresQtyKeys: ['hasEcommerceCount'],
    },
    {
      key: 'network_cabling',
      label: 'Cablare structurată',
      defaultEnabled: false,
      stageCodes: ['infrastructura'],
      fieldKeys: ['networkPoints', 'rackUnits', 'itDirection'],
      requiresQtyKeys: ['networkPoints'],
    },
    {
      key: 'cameras',
      label: 'Camere IP / NVR',
      defaultEnabled: false,
      stageCodes: ['infrastructura', 'securitate'],
      fieldKeys: ['cameraCount'],
      requiresQtyKeys: ['cameraCount'],
    },
    {
      key: 'servers',
      label: 'Servere & stații',
      defaultEnabled: false,
      stageCodes: ['infrastructura'],
      fieldKeys: ['serverCount', 'workstationCount', 'rackUnits'],
    },
    {
      key: 'security',
      label: 'Securitate & hardening',
      defaultEnabled: true,
      stageCodes: ['securitate'],
      fieldKeys: [],
    },
    {
      key: 'migration',
      label: 'Migrare date',
      defaultEnabled: false,
      stageCodes: ['migrare'],
      fieldKeys: ['migrationRequired'],
      requiresQtyKeys: ['migrationUnits'],
    },
    {
      key: 'hardware_components',
      label: 'Componente hardware',
      defaultEnabled: false,
      stageCodes: ['hardware'],
      fieldKeys: ['serverCount', 'workstationCount', 'rackUnits'],
      helpText: 'Asamblare, reparare și configurare componente fizice',
    },
    {
      key: 'sla',
      label: 'SLA / suport',
      defaultEnabled: false,
      stageCodes: ['suport'],
      fieldKeys: ['slaRequired'],
      requiresQtyKeys: ['slaUnits'],
    },
  ],
  customFields: [
    {
      key: 'itDirection',
      label: 'Direcție principală',
      type: 'select',
      options: ['web', 'security', 'hardware', 'network', 'full_stack'],
      required: false,
      defaultValue: 'web',
      helpText: 'Plan 2D disponibil doar pentru direcția network / cablare.',
      section: 'General',
    },
    {
      key: 'projectScope',
      label: 'Complexitate proiect',
      type: 'select',
      options: [
        'Mic (1-5 pagini / 1-2 zile)',
        'Mediu (6-20 pagini / 1-2 săptămâni)',
        'Enterprise (20+ pagini / 1+ lună)',
      ],
      required: true,
      section: 'General',
    },
    {
      key: 'pagesCount',
      label: 'Număr pagini / ecrane',
      type: 'number',
      unit: 'buc',
      required: true,
      validation: { min: 1 },
      helpText: 'Obligatoriu dacă sunt incluse module de design sau frontend.',
      warningRules: [
        {
          when: 'pagesCount = 0',
          message: 'Numărul de pagini este 0 — modulele de design și frontend nu vor genera costuri.',
        },
      ],
      section: 'Web',
      directionKeys: ['web', 'full_stack'],
    },
    {
      key: 'designPagesCount',
      label: 'Pagini cu design personalizat',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      helpText: 'Subset din Număr pagini care primesc design premium. Dacă 0, se folosește Număr pagini.',
      section: 'Web',
      directionKeys: ['web', 'full_stack'],
    },
    {
      key: 'frontendPagesCount',
      label: 'Pagini cu funcționalitate complexă (SPA)',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      helpText: 'Subset din Număr pagini care au componente interactive complexe. Dacă 0, se folosește Număr pagini.',
      section: 'Web',
      directionKeys: ['web', 'full_stack'],
    },
    {
      key: 'backendComplexity',
      label: 'Complexitate backend',
      type: 'select',
      options: ['Fără backend', 'Simplu (autentificare + baza date)', 'Mediu (API REST + 3rd party)', 'Complex (microservicii / real-time)'],
      required: false,
      defaultValue: 'Fără backend',
      section: 'Web',
      directionKeys: ['web', 'full_stack'],
    },
    {
      key: 'hasCMS',
      label: 'CMS',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Web',
      directionKeys: ['web', 'full_stack'],
    },
    {
      key: 'hasEcommerce',
      label: 'E-commerce / plăți online',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Web',
      directionKeys: ['web', 'full_stack'],
    },
    {
      key: 'cameraCount',
      label: 'Camere IP',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Securitate',
      directionKeys: ['security', 'network', 'full_stack'],
    },
    {
      key: 'networkPoints',
      label: 'Porturi rețea (RJ45)',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Rețea',
      directionKeys: ['network', 'full_stack'],
    },
    {
      key: 'avgCableLengthPerPort',
      label: 'Lungime cablu per port (m)',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 20,
      helpText: 'Lungime medie cablu UTP per port. Default: 20 m.',
      section: 'Rețea',
      directionKeys: ['network', 'full_stack'],
    },
    {
      key: 'apCount',
      label: 'Access Points Wi-Fi',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Rețea',
      directionKeys: ['network', 'full_stack'],
    },
    {
      key: 'serverCount',
      label: 'Servere',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Infrastructură',
      directionKeys: ['hardware', 'network', 'full_stack'],
    },
    {
      key: 'workstationCount',
      label: 'Stații de lucru',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Infrastructură',
      directionKeys: ['hardware', 'network', 'full_stack'],
    },
    {
      key: 'rackUnits',
      label: 'Unități rack (U)',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Infrastructură',
      directionKeys: ['hardware', 'network', 'full_stack'],
    },
    {
      key: 'slaRequired',
      label: 'SLA / suport inclus',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Suport',
    },
    {
      key: 'documentationRequired',
      label: 'Documentație extinsă',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Suport',
    },
    {
      key: 'migrationRequired',
      label: 'Migrare date necesară',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Migrare',
    },
    {
      key: 'multilingual',
      label: 'Suport multilingv (RO/RU/EN) / Мультиязычность',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Web',
      directionKeys: ['web', 'full_stack'],
    },
    {
      key: 'customDesign',
      label: 'Design UI/UX Premium personalizat / Индивидуальный дизайн',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Web',
      directionKeys: ['web', 'full_stack'],
    },
  ],
  diagnosticQuestions: [
    { key: 'itDirection', label: 'Direcție principală servicii IT', type: 'select', options: ['web', 'security', 'hardware', 'network', 'full_stack'] },
    { key: 'projectScope', label: 'Complexitate proiect', type: 'select', options: ['Mic (1-5 pagini / 1-2 zile)', 'Mediu (6-20 pagini / 1-2 săptămâni)', 'Enterprise (20+ pagini / 1+ lună)'] },
    { key: 'pagesCount', label: 'Număr pagini / ecrane (Web)', type: 'number' },
  ],
  defaultStages: [
    { code: 'analiza', name: 'Analiză & specificații tehnice', kind: 'LABOR', defaultLaborHours: 8, durationDays: 2, checklist: ['Audit cerințe', 'TOR / arhitectură'], moduleKey: 'audit' },
    { code: 'design', name: 'Design UI/UX', kind: 'LABOR', defaultLaborHours: 16, durationDays: 3, checklist: ['Wireframes', 'Mockup-uri'], moduleKey: 'web_design' },
    { code: 'dezvoltare', name: 'Dezvoltare frontend', kind: 'LABOR', defaultLaborHours: 40, durationDays: 10, checklist: ['Componente UI', 'Responsive design', 'Integrare API'], moduleKey: 'frontend' },
    { code: 'backend_dev', name: 'Dezvoltare backend & API', kind: 'LABOR', defaultLaborHours: 24, durationDays: 6, checklist: ['Arhitectură API', 'Bază de date', 'Autentificare'], optional: true, moduleKey: 'backend' },
    { code: 'cms_dev', name: 'Integrare CMS', kind: 'LABOR', defaultLaborHours: 16, durationDays: 3, checklist: ['Instalare CMS', 'Configurare module', 'Template personalizat'], optional: true, moduleKey: 'cms' },
    { code: 'ecommerce_dev', name: 'Modul e-commerce', kind: 'LABOR', defaultLaborHours: 20, durationDays: 4, checklist: ['Catalog produse', 'Coș cumpărături', 'Gateway plăți'], optional: true, moduleKey: 'ecommerce' },
    { code: 'infrastructura', name: 'Infrastructură & rețea', kind: 'MIXED', defaultLaborHours: 12, durationDays: 3, checklist: ['Cablare', 'Wi-Fi', 'Servere'], moduleKey: 'network_cabling' },
    { code: 'securitate', name: 'Securitate & hardening', kind: 'LABOR', defaultLaborHours: 8, durationDays: 2, checklist: ['SSL', 'Firewall', 'Backup'], moduleKey: 'security' },
    { code: 'hardware', name: 'Componente hardware', kind: 'MIXED', defaultLaborHours: 8, durationDays: 2, checklist: ['Asamblare', 'Reparare', 'Configurare'], optional: true, moduleKey: 'hardware_components' },
    { code: 'migrare', name: 'Migrare date', kind: 'LABOR', defaultLaborHours: 8, durationDays: 2, checklist: ['Backup', 'Migrare', 'Validare'], optional: true, moduleKey: 'migration' },
    { code: 'testare', name: 'Testare QA & lansare', kind: 'LABOR', defaultLaborHours: 8, durationDays: 2, checklist: ['QA', 'Deploy producție'], moduleKey: 'audit' },
    { code: 'instruire', name: 'Instruire & documentație', kind: 'LABOR', defaultLaborHours: 4, durationDays: 1, checklist: ['Training', 'Documentație'], moduleKey: 'audit' },
    { code: 'suport', name: 'SLA & suport', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Contract SLA'], optional: true, moduleKey: 'sla' },
  ],
  pricingRules: [
    { stageCode: 'analiza', description: 'Audit & elaborare specificații (TOR)', unit: 'ore', qtyKey: 'analysisHours', unitPrice: 350, kind: 'labor', moduleKey: 'audit' },
    { stageCode: 'design', description: 'Design UI/UX per pagină', unit: 'buc', qtyKey: 'designPageCount', unitPrice: 800, kind: 'labor', moduleKey: 'web_design', enabledWhen: { anyQtyKeys: ['designPageCount'] } },
    { stageCode: 'dezvoltare', description: 'Dezvoltare frontend per pagină', unit: 'buc', qtyKey: 'frontendPageCount', unitPrice: 1500, kind: 'labor', moduleKey: 'frontend', enabledWhen: { anyQtyKeys: ['frontendPageCount'] } },
    { stageCode: 'backend_dev', description: 'Dezvoltare backend & API', unit: 'buc', qtyKey: 'hasBackendCount', unitPrice: 8000, kind: 'labor', moduleKey: 'backend', enabledWhen: { moduleEnabled: 'backend', anyQtyKeys: ['hasBackendCount'] } },
    { stageCode: 'cms_dev', description: 'Integrare CMS', unit: 'buc', qtyKey: 'hasCmsCount', unitPrice: 5000, kind: 'labor', moduleKey: 'cms', enabledWhen: { moduleEnabled: 'cms', anyQtyKeys: ['hasCmsCount'] } },
    { stageCode: 'ecommerce_dev', description: 'Modul e-commerce & plăți', unit: 'buc', qtyKey: 'hasEcommerceCount', unitPrice: 12000, kind: 'labor', moduleKey: 'ecommerce', enabledWhen: { moduleEnabled: 'ecommerce', anyQtyKeys: ['hasEcommerceCount'] } },
    { stageCode: 'infrastructura', description: 'Cablare structurată Cat6 (manoperă/port)', unit: 'buc', qtyKey: 'networkPoints', unitPrice: 110, kind: 'labor', moduleKey: 'network_cabling', enabledWhen: { anyQtyKeys: ['networkPoints'] } },
    { stageCode: 'infrastructura', description: 'Cablu UTP Cat6 (material)', unit: 'm', qtyKey: 'networkCableM', unitPrice: 15, wastePct: 20, kind: 'material', moduleKey: 'network_cabling', enabledWhen: { anyQtyKeys: ['networkCableM'] } },
    { stageCode: 'infrastructura', description: 'Montaj Access Point Wi-Fi', unit: 'buc', qtyKey: 'apCount', unitPrice: 280, kind: 'labor', moduleKey: 'network_cabling', enabledWhen: { anyQtyKeys: ['apCount'] } },
    { stageCode: 'infrastructura', description: 'Configurare server', unit: 'buc', qtyKey: 'serverCount', unitPrice: 3500, kind: 'labor', moduleKey: 'servers', enabledWhen: { anyQtyKeys: ['serverCount'] } },
    { stageCode: 'infrastructura', description: 'Configurare stație de lucru', unit: 'buc', qtyKey: 'workstationCount', unitPrice: 450, kind: 'labor', moduleKey: 'servers', enabledWhen: { anyQtyKeys: ['workstationCount'] } },
    { stageCode: 'securitate', description: 'SSL, firewall & hardening', unit: 'buc', qtyKey: 'projectUnits', unitPrice: 2500, kind: 'labor', moduleKey: 'security' },
    { stageCode: 'securitate', description: 'Montaj cameră IP', unit: 'buc', qtyKey: 'cameraCount', unitPrice: 380, kind: 'labor', moduleKey: 'cameras', enabledWhen: { anyQtyKeys: ['cameraCount'] } },
    { stageCode: 'hardware', description: 'Asamblare PC / server', unit: 'buc', qtyKey: 'serverCount', unitPrice: 600, kind: 'labor', moduleKey: 'hardware_components', enabledWhen: { moduleEnabled: 'hardware_components', anyQtyKeys: ['serverCount'] } },
    { stageCode: 'hardware', description: 'Reparare / diagnostic stație', unit: 'buc', qtyKey: 'workstationCount', unitPrice: 350, kind: 'labor', moduleKey: 'hardware_components', enabledWhen: { moduleEnabled: 'hardware_components', anyQtyKeys: ['workstationCount'] } },
    { stageCode: 'hardware', description: 'Organizare rack', unit: 'buc', qtyKey: 'rackUnits', unitPrice: 120, kind: 'labor', moduleKey: 'hardware_components', enabledWhen: { moduleEnabled: 'hardware_components', anyQtyKeys: ['rackUnits'] } },
    { stageCode: 'migrare', description: 'Migrare date & validare', unit: 'buc', qtyKey: 'migrationUnits', unitPrice: 4500, kind: 'labor', moduleKey: 'migration', enabledWhen: { moduleEnabled: 'migration', anyQtyKeys: ['migrationUnits'] } },
    { stageCode: 'testare', description: 'QA testing & deployment', unit: 'ore', qtyKey: 'testingHours', unitPrice: 300, kind: 'labor', moduleKey: 'audit' },
    { stageCode: 'instruire', description: 'Training & documentație', unit: 'ore', qtyKey: 'trainingHours', unitPrice: 250, kind: 'labor', moduleKey: 'audit' },
    { stageCode: 'suport', description: 'Pachet SLA / suport', unit: 'buc', qtyKey: 'slaUnits', unitPrice: 3500, kind: 'labor', moduleKey: 'sla', enabledWhen: { moduleEnabled: 'sla', anyQtyKeys: ['slaUnits'] } },
  ],
});
