import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

/** Servicii Web și Aplicații: design, frontend, backend, CMS, e-commerce. Fără plan 2D. */
export const itWebBlueprint: EstimateBlueprintConfig = baseConfig({
  wizardSteps: ['object', 'diagnostic', 'stages', 'review'],
  urgencyImpact: { urgent: 1.2, emergency: 1.5 },
  siteTypes: [
    { value: 'startup', label: 'Startup / Proiect Nou' },
    { value: 'ecommerce', label: 'Magazin Online' },
    { value: 'enterprise', label: 'Companie / Enterprise' },
  ],
  planPointTypes: [],
  workModules: [
    {
      key: 'audit',
      label: 'Audit & specificații',
      defaultEnabled: true,
      stageCodes: ['analiza'],
      fieldKeys: ['projectScope'],
    },
    {
      key: 'web_design',
      label: 'Design UI/UX',
      defaultEnabled: true,
      stageCodes: ['design'],
      fieldKeys: ['pagesCount', 'customDesign', 'designPagesCount'],
    },
    {
      key: 'frontend',
      label: 'Dezvoltare frontend',
      defaultEnabled: true,
      stageCodes: ['dezvoltare'],
      fieldKeys: ['pagesCount', 'frontendPagesCount', 'multilingual'],
    },
    {
      key: 'backend',
      label: 'Backend & API',
      defaultEnabled: false,
      stageCodes: ['backend_dev'],
      fieldKeys: ['backendComplexity'],
      requiresQtyKeys: ['hasBackendCount'],
    },
    {
      key: 'cms',
      label: 'CMS',
      defaultEnabled: false,
      stageCodes: ['cms_dev'],
      fieldKeys: ['hasCMS'],
      requiresQtyKeys: ['hasCmsCount'],
    },
    {
      key: 'ecommerce',
      label: 'E-commerce',
      defaultEnabled: false,
      stageCodes: ['ecommerce_dev'],
      fieldKeys: ['hasEcommerce'],
      requiresQtyKeys: ['hasEcommerceCount'],
    },
    {
      key: 'security',
      label: 'Securitate & hardening',
      defaultEnabled: true,
      stageCodes: ['securitate'],
      fieldKeys: [],
    },
    {
      key: 'migration',
      label: 'Migrare date',
      defaultEnabled: false,
      stageCodes: ['migrare'],
      fieldKeys: ['migrationRequired'],
      requiresQtyKeys: ['migrationUnits'],
    },
    {
      key: 'sla',
      label: 'SLA / suport',
      defaultEnabled: false,
      stageCodes: ['suport'],
      fieldKeys: ['slaRequired'],
      requiresQtyKeys: ['slaUnits'],
    },
  ],
  customFields: [
    {
      key: 'projectScope',
      label: 'Complexitate proiect',
      type: 'select',
      options: [
        'Mic (1-5 pagini / 1-2 zile)',
        'Mediu (6-20 pagini / 1-2 săptămâni)',
        'Enterprise (20+ pagini / 1+ lună)',
      ],
      required: true,
      section: 'General',
    },
    {
      key: 'pagesCount',
      label: 'Număr pagini / ecrane',
      type: 'number',
      unit: 'buc',
      required: true,
      validation: { min: 1 },
      defaultValue: 1,
      helpText: 'Obligatoriu dacă sunt incluse module de design sau frontend.',
      warningRules: [
        {
          when: 'pagesCount = 0',
          message: 'Numărul de pagini este 0 — modulele de design și frontend nu vor genera costuri.',
        },
      ],
      section: 'Web',
    },
    {
      key: 'designPagesCount',
      label: 'Pagini cu design personalizat',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      helpText: 'Subset din Număr pagini care primesc design premium. Dacă 0, se folosește Număr pagini.',
      section: 'Web',
    },
    {
      key: 'frontendPagesCount',
      label: 'Pagini cu funcționalitate complexă (SPA)',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      helpText: 'Subset din Număr pagini care au componente interactive complexe. Dacă 0, se folosește Număr pagini.',
      section: 'Web',
    },
    {
      key: 'backendComplexity',
      label: 'Complexitate backend',
      type: 'select',
      options: ['Fără backend', 'Simplu (autentificare + baza date)', 'Mediu (API REST + 3rd party)', 'Complex (microservicii / real-time)'],
      required: false,
      defaultValue: 'Fără backend',
      section: 'Web',
    },
    {
      key: 'hasCMS',
      label: 'CMS',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Web',
    },
    {
      key: 'hasEcommerce',
      label: 'E-commerce / plăți online',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Web',
    },
    {
      key: 'documentationRequired',
      label: 'Documentație extinsă',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Suport',
    },
    {
      key: 'migrationRequired',
      label: 'Migrare date necesară',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Migrare',
    },
    {
      key: 'slaRequired',
      label: 'SLA / suport inclus',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Suport',
    },
    {
      key: 'multilingual',
      label: 'Suport multilingv (RO/RU/EN) / Мультиязычность',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Web',
    },
    {
      key: 'customDesign',
      label: 'Design UI/UX Premium personalizat / Индивидуальный дизайн',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Web',
    },
  ],
  diagnosticQuestions: [
    { key: 'projectScope', label: 'Complexitate proiect', type: 'select', options: ['Mic (1-5 pagini / 1-2 zile)', 'Mediu (6-20 pagini / 1-2 săptămâni)', 'Enterprise (20+ pagini / 1+ lună)'] },
    { key: 'pagesCount', label: 'Număr pagini / ecrane (Web)', type: 'number' },
  ],
  defaultStages: [
    { code: 'analiza', name: 'Analiză & specificații tehnice', kind: 'LABOR', defaultLaborHours: 8, durationDays: 2, checklist: ['Audit cerințe', 'TOR / arhitectură'], moduleKey: 'audit' },
    { code: 'design', name: 'Design UI/UX', kind: 'LABOR', defaultLaborHours: 16, durationDays: 3, checklist: ['Wireframes', 'Mockup-uri'], moduleKey: 'web_design' },
    { code: 'dezvoltare', name: 'Dezvoltare frontend', kind: 'LABOR', defaultLaborHours: 40, durationDays: 10, checklist: ['Componente UI', 'Responsive design', 'Integrare API'], moduleKey: 'frontend' },
    { code: 'backend_dev', name: 'Dezvoltare backend & API', kind: 'LABOR', defaultLaborHours: 24, durationDays: 6, checklist: ['Arhitectură API', 'Bază de date', 'Autentificare'], optional: true, moduleKey: 'backend' },
    { code: 'cms_dev', name: 'Integrare CMS', kind: 'LABOR', defaultLaborHours: 16, durationDays: 3, checklist: ['Instalare CMS', 'Configurare module', 'Template personalizat'], optional: true, moduleKey: 'cms' },
    { code: 'ecommerce_dev', name: 'Modul e-commerce', kind: 'LABOR', defaultLaborHours: 20, durationDays: 4, checklist: ['Catalog produse', 'Coș cumpărături', 'Gateway plăți'], optional: true, moduleKey: 'ecommerce' },
    { code: 'securitate', name: 'Securitate & hardening', kind: 'LABOR', defaultLaborHours: 8, durationDays: 2, checklist: ['SSL', 'Firewall', 'Backup'], moduleKey: 'security' },
    { code: 'migrare', name: 'Migrare date', kind: 'LABOR', defaultLaborHours: 8, durationDays: 2, checklist: ['Backup', 'Migrare', 'Validare'], optional: true, moduleKey: 'migration' },
    { code: 'testare', name: 'Testare QA & lansare', kind: 'LABOR', defaultLaborHours: 8, durationDays: 2, checklist: ['QA', 'Deploy producție'], moduleKey: 'audit' },
    { code: 'instruire', name: 'Instruire & documentație', kind: 'LABOR', defaultLaborHours: 4, durationDays: 1, checklist: ['Training', 'Documentație'], moduleKey: 'audit' },
    { code: 'suport', name: 'SLA & suport', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Contract SLA'], optional: true, moduleKey: 'sla' },
  ],
  pricingRules: [
    { stageCode: 'analiza', description: 'Audit & elaborare specificații (TOR)', unit: 'ore', qtyKey: 'analysisHours', unitPrice: 350, kind: 'labor', moduleKey: 'audit' },
    { stageCode: 'design', description: 'Design UI/UX per pagină', unit: 'buc', qtyKey: 'designPageCount', unitPrice: 800, kind: 'labor', moduleKey: 'web_design', enabledWhen: { anyQtyKeys: ['designPageCount'] } },
    { stageCode: 'dezvoltare', description: 'Dezvoltare frontend per pagină', unit: 'buc', qtyKey: 'frontendPageCount', unitPrice: 1500, kind: 'labor', moduleKey: 'frontend', enabledWhen: { anyQtyKeys: ['frontendPageCount'] } },
    { stageCode: 'dezvoltare', description: 'Complexitate suplimentară frontend (SPA)', unit: 'buc', qtyKey: 'spaPageCount', unitPrice: 1500, kind: 'labor', moduleKey: 'frontend', enabledWhen: { anyQtyKeys: ['spaPageCount'] } },
    { stageCode: 'backend_dev', description: 'Dezvoltare backend & API', unit: 'buc', qtyKey: 'hasBackendCount', unitPrice: 8000, kind: 'labor', moduleKey: 'backend', enabledWhen: { moduleEnabled: 'backend', anyQtyKeys: ['hasBackendCount'] } },
    { stageCode: 'cms_dev', description: 'Integrare CMS', unit: 'buc', qtyKey: 'hasCmsCount', unitPrice: 5000, kind: 'labor', moduleKey: 'cms', enabledWhen: { moduleEnabled: 'cms', anyQtyKeys: ['hasCmsCount'] } },
    { stageCode: 'ecommerce_dev', description: 'Modul e-commerce & plăți', unit: 'buc', qtyKey: 'hasEcommerceCount', unitPrice: 12000, kind: 'labor', moduleKey: 'ecommerce', enabledWhen: { moduleEnabled: 'ecommerce', anyQtyKeys: ['hasEcommerceCount'] } },
    { stageCode: 'securitate', description: 'SSL, firewall & hardening', unit: 'buc', qtyKey: 'projectUnits', unitPrice: 2500, kind: 'labor', moduleKey: 'security' },
    { stageCode: 'migrare', description: 'Migrare date & validare', unit: 'buc', qtyKey: 'migrationUnits', unitPrice: 4500, kind: 'labor', moduleKey: 'migration', enabledWhen: { moduleEnabled: 'migration', anyQtyKeys: ['migrationUnits'] } },
    { stageCode: 'testare', description: 'QA testing & deployment', unit: 'ore', qtyKey: 'testingHours', unitPrice: 300, kind: 'labor', moduleKey: 'audit' },
    { stageCode: 'instruire', description: 'Training & documentație', unit: 'ore', qtyKey: 'trainingHours', unitPrice: 250, kind: 'labor', moduleKey: 'audit' },
    { stageCode: 'suport', description: 'Pachet SLA / suport', unit: 'buc', qtyKey: 'slaUnits', unitPrice: 3500, kind: 'labor', moduleKey: 'sla', enabledWhen: { moduleEnabled: 'sla', anyQtyKeys: ['slaUnits'] } },
  ],
  defaultLaborRate: 300,
  defaultMarginPct: 20,
});
