import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

export const lucrariFinisajBlueprint: EstimateBlueprintConfig = baseConfig({
  wizardSteps: ['object', 'diagnostic', 'stages', 'review'],
  accessDifficultyImpact: { easy: 1.0, medium: 1.05, difficult: 1.15 },
  urgencyImpact: { urgent: 1.15, emergency: 1.35 },
  planPointTypes: [],
  workModules: [
    // ---- Pregătire ----
    {
      key: 'demolition',
      label: 'Demontare & evacuare',
      helpText: 'Demontarea finisajelor vechi (tencuială slabă, gresie, tapet, plinte) și evacuarea molozului. Activați pentru renovări.',
      defaultEnabled: false,
      stageCodes: ['demontare'],
      fieldKeys: ['demolitionArea'],
      requiresQtyKeys: ['demolitionArea'],
      section: 'Pregătire',
    },
    {
      key: 'surface_preparation',
      label: 'Pregătire & amorsare',
      helpText: 'Curățare strat suport și aplicare amorsă pe pereți (tavanul se finisează prin modulele dedicate). Suprafața se calculează automat.',
      defaultEnabled: false,
      stageCodes: ['pregatire'],
      fieldKeys: ['preparationArea'],
      section: 'Pregătire',
    },
    {
      key: 'plaster',
      label: 'Tencuială & nivelare',
      helpText: 'Tencuire și nivelare a pereților bruți (zidărie nouă). Pentru pereți deja tencuiți folosiți doar gletul.',
      defaultEnabled: false,
      stageCodes: ['tencuiala'],
      fieldKeys: ['plasterArea'],
      section: 'Pregătire',
    },
    // ---- Pereți ----
    {
      key: 'partition',
      label: 'Pereți despărțitori gips-carton',
      helpText: 'Perete nou pe schelet metalic, dublu placat + izolație fonică. Se măsoară suprafața peretelui (lungime × înălțime).',
      defaultEnabled: false,
      stageCodes: ['pereti_gk'],
      fieldKeys: ['partitionArea'],
      requiresQtyKeys: ['partitionArea'],
      section: 'Pereți',
    },
    {
      key: 'putty',
      label: 'Glet & șlefuire',
      helpText: 'Glet de finisare (start + finiș) și șlefuire pe pereți (tavanul se finisează prin modulele dedicate). Suprafața se calculează automat.',
      defaultEnabled: false,
      stageCodes: ['glet'],
      fieldKeys: ['puttyArea'],
      section: 'Pereți',
    },
    {
      key: 'paint',
      label: 'Vopsire lavabilă',
      helpText: 'Vopsire pereți cu lavabilă. Suprafața se calculează automat (pereți minus tapet/decorativă).',
      defaultEnabled: false,
      stageCodes: ['vopsire_tapet'],
      fieldKeys: ['paintArea'],
      section: 'Pereți',
    },
    {
      key: 'decorative_plaster',
      label: 'Tencuială decorativă',
      helpText: 'Strat decorativ structurat (venețian, baramin) pe pereți de accent. Înlocuiește vopseaua pe suprafața respectivă.',
      defaultEnabled: false,
      stageCodes: ['vopsire_tapet'],
      fieldKeys: ['decorativePlasterArea'],
      requiresQtyKeys: ['decorativePlasterArea'],
      section: 'Pereți',
    },
    {
      key: 'wallpaper',
      label: 'Tapet',
      helpText: 'Lipire tapet pe pereți. Înlocuiește vopseaua pe suprafața acoperită. Se introduce suprafața de tapetat.',
      defaultEnabled: false,
      stageCodes: ['vopsire_tapet'],
      fieldKeys: ['wallpaperArea'],
      requiresQtyKeys: ['wallpaperArea'],
      section: 'Pereți',
    },
    // ---- Tavane ----
    {
      key: 'ceiling',
      label: 'Finisaj tavan (glet/vopsire)',
      helpText: 'Finisarea tavanului existent (glet + vopsire). Pentru tavan suspendat folosiți „Gips-carton” sau „Tavan tensionat”.',
      defaultEnabled: false,
      stageCodes: ['tavane'],
      fieldKeys: ['ceilingArea'],
      section: 'Tavane',
    },
    {
      key: 'drywall',
      label: 'Tavan/structuri gips-carton',
      helpText: 'Tavan suspendat, casete sau nișe din gips-carton pe schelet metalic. Se introduce suprafața placată.',
      defaultEnabled: false,
      stageCodes: ['tavane'],
      fieldKeys: ['drywallArea'],
      requiresQtyKeys: ['drywallArea'],
      section: 'Tavane',
    },
    {
      key: 'stretch_ceiling',
      label: 'Tavan tensionat (натяжной)',
      helpText: 'Tavan tensionat PVC/textil cu profile perimetrale. Foarte folosit în Moldova. Suprafața = suprafața podelei dacă nu e specificată.',
      defaultEnabled: false,
      stageCodes: ['tavane'],
      fieldKeys: ['stretchCeilingArea'],
      section: 'Tavane',
    },
    // ---- Pardoseală ----
    {
      key: 'waterproofing',
      label: 'Hidroizolație (băi/bucătărie)',
      helpText: 'Hidroizolație sub gresie în zonele umede (baie, bucătărie). Se aplică înainte de placare.',
      defaultEnabled: false,
      stageCodes: ['gresie_faianta'],
      fieldKeys: ['waterproofingArea'],
      requiresQtyKeys: ['waterproofingArea'],
      section: 'Pardoseală',
    },
    {
      key: 'tile',
      label: 'Gresie & faianță',
      helpText: 'Placare cu gresie (pardoseală) și faianță (pereți). Se introduce suprafața totală de placat.',
      defaultEnabled: false,
      stageCodes: ['gresie_faianta'],
      fieldKeys: ['tileArea'],
      requiresQtyKeys: ['tileArea'],
      section: 'Pardoseală',
    },
    {
      key: 'screed',
      label: 'Șapă & autonivelare',
      helpText: 'Șapă de egalizare / autonivelantă înainte de montajul pardoselii. Se introduce suprafața.',
      defaultEnabled: false,
      stageCodes: ['pardoseala'],
      fieldKeys: ['screedArea'],
      requiresQtyKeys: ['screedArea'],
      section: 'Pardoseală',
    },
    {
      key: 'flooring',
      label: 'Laminat / vinil / linoleum',
      helpText: 'Pardoseală laminat, LVT-vinil sau linoleum + substrat. Pentru parchet din lemn folosiți modulul separat.',
      defaultEnabled: false,
      stageCodes: ['pardoseala'],
      fieldKeys: ['flooringArea'],
      requiresQtyKeys: ['flooringArea'],
      section: 'Pardoseală',
    },
    {
      key: 'parquet',
      label: 'Parchet din lemn / triplustratificat',
      helpText: 'Parchet masiv sau triplustratificat (preț mai ridicat decât laminatul). Se introduce suprafața.',
      defaultEnabled: false,
      stageCodes: ['pardoseala'],
      fieldKeys: ['parquetArea'],
      requiresQtyKeys: ['parquetArea'],
      section: 'Pardoseală',
    },
    // ---- Detalii & finalizare ----
    {
      key: 'baseboards',
      label: 'Plinte',
      helpText: 'Montaj plinte MDF/PVC pe perimetru. Lungimea se estimează automat din suprafața camerei.',
      defaultEnabled: false,
      stageCodes: ['finisaje_detalii'],
      fieldKeys: ['baseboardLengthM'],
      section: 'Detalii',
    },
    {
      key: 'slopes',
      label: 'Glafuri uși & ferestre (spaleți)',
      helpText: 'Finisarea spaleților (glafurilor) la uși și ferestre cu gips-carton sau tencuială. Se introduce lungimea totală.',
      defaultEnabled: false,
      stageCodes: ['finisaje_detalii'],
      fieldKeys: ['doorSlopeLengthM'],
      requiresQtyKeys: ['doorSlopeLengthM'],
      section: 'Detalii',
    },
    {
      key: 'cleaning',
      label: 'Curățenie finală',
      helpText: 'Curățenie post-șantier înainte de predare. Suprafața = suprafața finisată.',
      defaultEnabled: false,
      stageCodes: ['curatenie_predare'],
      fieldKeys: [],
      section: 'Detalii',
    },
  ],
  customFields: [
    // ---- General (always visible) ----
    {
      key: 'finishArea',
      label: 'Suprafață finisaj (podea)',
      type: 'number',
      unit: 'm²',
      required: true,
      defaultValue: 30,
      validation: { min: 1 },
      helpText: 'Suprafața totală a podelei camerelor de finisat. Stă la baza calculului pereților și tavanului.',
      placeholder: 'ex. 30',
      section: 'General',
    },
    {
      key: 'wallHeight',
      label: 'Înălțime camere',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 2.7,
      validation: { min: 2, max: 5 },
      helpText: 'Influențează suprafața pereților calculată automat (standard 2.7 m).',
      placeholder: 'ex. 2.7',
      section: 'General',
    },
    {
      key: 'surfaceCondition',
      label: 'Stare suprafață',
      type: 'select',
      options: ['new', 'old', 'very_bad'],
      required: false,
      defaultValue: 'new',
      helpText: 'Starea suportului existent — crește automat manopera pentru suprafețe vechi/deteriorate.',
      warningRules: [
        { when: "surfaceCondition === 'old'", message: 'Suprafață veche — manopera crește automat cu +15%.' },
        { when: "surfaceCondition === 'very_bad'", message: 'Suprafață foarte deteriorată — manopera crește automat cu +35%.' },
      ],
      section: 'General',
    },
    {
      key: 'finishLevel',
      label: 'Nivel finisaj',
      type: 'select',
      options: ['economic', 'standard', 'premium'],
      required: false,
      defaultValue: 'standard',
      helpText: 'Nivelul de calitate dorit. Premium crește automat manopera.',
      warningRules: [
        { when: "finishLevel === 'premium'", message: 'Finisaj premium — manopera crește automat cu +15%.' },
      ],
      section: 'General',
    },
    {
      key: 'materialIncluded',
      label: 'Materiale incluse în ofertă',
      type: 'boolean',
      required: false,
      defaultValue: true,
      helpText: 'Dezactivați dacă clientul cumpără singur materialele — oferta va conține doar manopera.',
      section: 'General',
    },
    // ---- Avansat (collapsed; per-module quantities) ----
    {
      key: 'demolitionArea',
      label: 'Suprafață demontare',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Suprafața finisajelor vechi de înlăturat.',
      section: 'Pregătire',
    },
    {
      key: 'preparationArea',
      label: 'Suprafață pregătire / Площадь грунтовки',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Gol = se folosește suprafața pereților calculată automat.',
      section: 'Pregătire',
    },
    {
      key: 'puttyArea',
      label: 'Suprafață gletuită / Площадь шпаклевки',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Gol = se folosește suprafața pereților calculată automat.',
      section: 'Pereți',
    },
    {
      key: 'plasterArea',
      label: 'Suprafață tencuială',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Gol = se folosește suprafața pereților calculată automat.',
      section: 'Pregătire',
    },
    {
      key: 'partitionArea',
      label: 'Suprafață pereți despărțitori GK',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Lungime × înălțime pentru fiecare perete nou.',
      section: 'Pereți',
    },
    {
      key: 'ceilingArea',
      label: 'Suprafață tavan',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Gol = egală cu suprafața podelei. Folosită la glet, vopsire și tavane.',
      section: 'Tavane',
    },
    {
      key: 'drywallArea',
      label: 'Suprafață gips-carton (tavan/structuri)',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Suprafața placată cu gips-carton.',
      section: 'Tavane',
    },
    {
      key: 'stretchCeilingArea',
      label: 'Suprafață tavan tensionat',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Gol = egală cu suprafața podelei.',
      section: 'Tavane',
    },
    {
      key: 'decorativePlasterArea',
      label: 'Suprafață tencuială decorativă',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Suprafața pereților de accent cu finisaj decorativ.',
      section: 'Pereți',
    },
    {
      key: 'wallpaperArea',
      label: 'Suprafață tapet',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Suprafața pereților de tapetat.',
      section: 'Pereți',
    },
    {
      key: 'paintArea',
      label: 'Suprafață vopsire',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Gol = pereți + tavan, minus suprafața de tapet / decorativă, calculate automat.',
      section: 'Pereți',
    },
    {
      key: 'waterproofingArea',
      label: 'Suprafață hidroizolație',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Suprafața din zonele umede (de obicei podeaua băii + 30 cm pe pereți).',
      section: 'Pardoseală',
    },
    {
      key: 'tileArea',
      label: 'Suprafață gresie/faianță',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Suprafața totală de placat (pardoseală + pereți).',
      section: 'Pardoseală',
    },
    {
      key: 'screedArea',
      label: 'Suprafață șapă',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Suprafața de egalizat înainte de pardoseală.',
      section: 'Pardoseală',
    },
    {
      key: 'flooringArea',
      label: 'Suprafață laminat/vinil',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Suprafața de pardoseală laminat/vinil/linoleum.',
      section: 'Pardoseală',
    },
    {
      key: 'parquetArea',
      label: 'Suprafață parchet lemn',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Suprafața de parchet din lemn / triplustratificat.',
      section: 'Pardoseală',
    },
    {
      key: 'baseboardLengthM',
      label: 'Lungime plinte',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      helpText: 'Gol = perimetrul camerei estimat automat.',
      section: 'Detalii',
    },
    {
      key: 'doorSlopeLengthM',
      label: 'Lungime glafuri uși/ferestre',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      helpText: 'Lungimea totală a spaleților de finisat.',
      section: 'Detalii',
    },
  ],
  diagnosticQuestions: [],
  defaultStages: [
    { code: 'demontare', name: 'Demontare & evacuare', kind: 'LABOR', defaultLaborHours: 6, durationDays: 2, checklist: ['Demontare finisaje vechi', 'Evacuare deșeuri'], optional: true, moduleKey: 'demolition' },
    { code: 'pregatire', name: 'Pregătire & amorsare', kind: 'LABOR', defaultLaborHours: 5, durationDays: 1, checklist: ['Curățare strat suport', 'Aplicare amorsă'], optional: true, moduleKey: 'surface_preparation' },
    { code: 'pereti_gk', name: 'Pereți despărțitori gips-carton', kind: 'MIXED', defaultLaborHours: 10, durationDays: 2, checklist: ['Montaj schelet metalic', 'Izolație fonică', 'Dublă placare GKL'], optional: true, moduleKey: 'partition' },
    { code: 'tencuiala', name: 'Tencuială & nivelare', kind: 'MIXED', defaultLaborHours: 10, durationDays: 3, checklist: ['Montaj profile', 'Aplicare tencuială'], optional: true, moduleKey: 'plaster' },
    { code: 'glet', name: 'Glet & șlefuire', kind: 'MIXED', defaultLaborHours: 12, durationDays: 3, checklist: ['Strat glet start', 'Strat glet finiș', 'Șlefuire fină'], optional: true, moduleKey: 'putty' },
    { code: 'tavane', name: 'Tavane (GK / tensionat)', kind: 'MIXED', defaultLaborHours: 8, durationDays: 2, checklist: ['Structură tavan', 'Placare / montaj pânză'], optional: true, moduleKey: 'ceiling' },
    { code: 'gresie_faianta', name: 'Hidroizolație, gresie & faianță', kind: 'MIXED', defaultLaborHours: 14, durationDays: 4, checklist: ['Hidroizolație zone umede', 'Lipire plăci', 'Rostuire'], optional: true, moduleKey: 'tile' },
    { code: 'pardoseala', name: 'Șapă & pardoseală', kind: 'MIXED', defaultLaborHours: 12, durationDays: 3, checklist: ['Șapă autonivelantă', 'Montaj pardoseală'], optional: true, moduleKey: 'flooring' },
    { code: 'vopsire_tapet', name: 'Vopsire, tapet & decorativă', kind: 'MIXED', defaultLaborHours: 8, durationDays: 2, checklist: ['Protecție elemente', 'Finisare decorativă'], optional: true, moduleKey: 'paint' },
    { code: 'finisaje_detalii', name: 'Plinte & glafuri', kind: 'MIXED', defaultLaborHours: 4, durationDays: 1, checklist: ['Montaj plinte', 'Finisaj glafuri'], optional: true, moduleKey: 'baseboards' },
    { code: 'curatenie_predare', name: 'Curățenie & predare', kind: 'LABOR', defaultLaborHours: 3, durationDays: 1, checklist: ['Curățenie post-șantier', 'Predare client'], optional: true, moduleKey: 'cleaning' },
  ],
  pricingRules: [
    // Demontare
    { stageCode: 'demontare', description: 'Lucrări demontare finisaje', unit: 'm²', qtyKey: 'demolitionAreaLabor', unitPrice: 45, kind: 'labor', moduleKey: 'demolition', enabledWhen: { anyQtyKeys: ['demolitionArea'] } },
    // Pregătire
    { stageCode: 'pregatire', description: 'Amorsă & pregătire suprafețe', unit: 'm²', qtyKey: 'preparationAreaLabor', unitPrice: 18, kind: 'labor', moduleKey: 'surface_preparation' },
    // Pereți despărțitori GK
    { stageCode: 'pereti_gk', description: 'Perete gips-carton dublu placat + izolație (material)', unit: 'm²', qtyKey: 'partitionArea', unitPrice: 130, wastePct: 10, kind: 'material', moduleKey: 'partition', enabledWhen: { anyQtyKeys: ['partitionArea'] } },
    { stageCode: 'pereti_gk', description: 'Lucrări montaj perete gips-carton', unit: 'm²', qtyKey: 'partitionAreaLabor', unitPrice: 95, kind: 'labor', moduleKey: 'partition', enabledWhen: { anyQtyKeys: ['partitionArea'] } },
    // Tencuială
    { stageCode: 'tencuiala', description: 'Tencuială (material)', unit: 'm²', qtyKey: 'plasterArea', unitPrice: 35, wastePct: 10, kind: 'material', moduleKey: 'plaster', enabledWhen: { anyQtyKeys: ['plasterArea'] } },
    { stageCode: 'tencuiala', description: 'Lucrări tencuială', unit: 'm²', qtyKey: 'plasterAreaLabor', unitPrice: 55, kind: 'labor', moduleKey: 'plaster', enabledWhen: { anyQtyKeys: ['plasterArea'] } },
    // Glet
    { stageCode: 'glet', description: 'Glet de finisare (material)', unit: 'm²', qtyKey: 'puttyArea', unitPrice: 28, wastePct: 12, kind: 'material', moduleKey: 'putty' },
    { stageCode: 'glet', description: 'Lucrări gletuire & șlefuire', unit: 'm²', qtyKey: 'puttyAreaLabor', unitPrice: 42, kind: 'labor', moduleKey: 'putty' },
    // Tavane: gips-carton
    { stageCode: 'tavane', description: 'Placaj gips-carton (material)', unit: 'm²', qtyKey: 'drywallArea', unitPrice: 95, wastePct: 10, kind: 'material', moduleKey: 'drywall', enabledWhen: { anyQtyKeys: ['drywallArea'] } },
    { stageCode: 'tavane', description: 'Lucrări montaj gips-carton', unit: 'm²', qtyKey: 'drywallAreaLabor', unitPrice: 85, kind: 'labor', moduleKey: 'drywall', enabledWhen: { anyQtyKeys: ['drywallArea'] } },
    // Tavane: tensionat
    { stageCode: 'tavane', description: 'Tavan tensionat (material PVC + profile)', unit: 'm²', qtyKey: 'stretchCeilingArea', unitPrice: 180, wastePct: 5, kind: 'material', moduleKey: 'stretch_ceiling', enabledWhen: { anyQtyKeys: ['stretchCeilingArea'] } },
    { stageCode: 'tavane', description: 'Lucrări montaj tavan tensionat', unit: 'm²', qtyKey: 'stretchCeilingAreaLabor', unitPrice: 90, kind: 'labor', moduleKey: 'stretch_ceiling', enabledWhen: { anyQtyKeys: ['stretchCeilingArea'] } },
    // Tavane: finisaj clasic (glet/vopsire tavan)
    { stageCode: 'tavane', description: 'Finisaj tavan (glet + vopsire)', unit: 'm²', qtyKey: 'ceilingAreaLabor', unitPrice: 38, kind: 'labor', moduleKey: 'ceiling', enabledWhen: { anyQtyKeys: ['ceilingArea'] } },
    // Gresie & faianță + hidroizolație
    { stageCode: 'gresie_faianta', description: 'Hidroizolație (material)', unit: 'm²', qtyKey: 'waterproofingArea', unitPrice: 55, wastePct: 8, kind: 'material', moduleKey: 'waterproofing', enabledWhen: { anyQtyKeys: ['waterproofingArea'] } },
    { stageCode: 'gresie_faianta', description: 'Lucrări hidroizolație', unit: 'm²', qtyKey: 'waterproofingAreaLabor', unitPrice: 45, kind: 'labor', moduleKey: 'waterproofing', enabledWhen: { anyQtyKeys: ['waterproofingArea'] } },
    { stageCode: 'gresie_faianta', description: 'Gresie/faianță (material)', unit: 'm²', qtyKey: 'tileArea', unitPrice: 120, wastePct: 10, kind: 'material', moduleKey: 'tile', enabledWhen: { anyQtyKeys: ['tileArea'] } },
    { stageCode: 'gresie_faianta', description: 'Lucrări placare gresie/faianță', unit: 'm²', qtyKey: 'tileAreaLabor', unitPrice: 95, kind: 'labor', moduleKey: 'tile', enabledWhen: { anyQtyKeys: ['tileArea'] } },
    // Pardoseală: șapă
    { stageCode: 'pardoseala', description: 'Șapă autonivelantă (material)', unit: 'm²', qtyKey: 'screedArea', unitPrice: 45, wastePct: 5, kind: 'material', moduleKey: 'screed', enabledWhen: { anyQtyKeys: ['screedArea'] } },
    { stageCode: 'pardoseala', description: 'Lucrări șapă', unit: 'm²', qtyKey: 'screedAreaLabor', unitPrice: 35, kind: 'labor', moduleKey: 'screed', enabledWhen: { anyQtyKeys: ['screedArea'] } },
    // Pardoseală: laminat/vinil
    { stageCode: 'pardoseala', description: 'Pardoseală laminat/vinil (material)', unit: 'm²', qtyKey: 'flooringArea', unitPrice: 85, wastePct: 8, kind: 'material', moduleKey: 'flooring', enabledWhen: { anyQtyKeys: ['flooringArea'] } },
    { stageCode: 'pardoseala', description: 'Lucrări montaj laminat/vinil', unit: 'm²', qtyKey: 'flooringAreaLabor', unitPrice: 48, kind: 'labor', moduleKey: 'flooring', enabledWhen: { anyQtyKeys: ['flooringArea'] } },
    // Pardoseală: parchet lemn
    { stageCode: 'pardoseala', description: 'Parchet lemn / triplustratificat (material)', unit: 'm²', qtyKey: 'parquetArea', unitPrice: 320, wastePct: 8, kind: 'material', moduleKey: 'parquet', enabledWhen: { anyQtyKeys: ['parquetArea'] } },
    { stageCode: 'pardoseala', description: 'Lucrări montaj parchet', unit: 'm²', qtyKey: 'parquetAreaLabor', unitPrice: 95, kind: 'labor', moduleKey: 'parquet', enabledWhen: { anyQtyKeys: ['parquetArea'] } },
    // Vopsire / tapet / decorativă
    { stageCode: 'vopsire_tapet', description: 'Vopsea lavabilă (material)', unit: 'm²', qtyKey: 'paintArea', unitPrice: 22, wastePct: 12, kind: 'material', moduleKey: 'paint' },
    { stageCode: 'vopsire_tapet', description: 'Lucrări vopsire lavabilă', unit: 'm²', qtyKey: 'paintAreaLabor', unitPrice: 38, kind: 'labor', moduleKey: 'paint' },
    { stageCode: 'vopsire_tapet', description: 'Tencuială decorativă interior (material)', unit: 'm²', qtyKey: 'decorativePlasterArea', unitPrice: 75, wastePct: 10, kind: 'material', moduleKey: 'decorative_plaster', enabledWhen: { anyQtyKeys: ['decorativePlasterArea'] } },
    { stageCode: 'vopsire_tapet', description: 'Lucrări tencuială decorativă', unit: 'm²', qtyKey: 'decorativePlasterAreaLabor', unitPrice: 110, kind: 'labor', moduleKey: 'decorative_plaster', enabledWhen: { anyQtyKeys: ['decorativePlasterArea'] } },
    { stageCode: 'vopsire_tapet', description: 'Tapet decorativ (material)', unit: 'm²', qtyKey: 'wallpaperArea', unitPrice: 65, wastePct: 10, kind: 'material', moduleKey: 'wallpaper', enabledWhen: { anyQtyKeys: ['wallpaperArea'] } },
    { stageCode: 'vopsire_tapet', description: 'Lucrări tapet', unit: 'm²', qtyKey: 'wallpaperAreaLabor', unitPrice: 42, kind: 'labor', moduleKey: 'wallpaper', enabledWhen: { anyQtyKeys: ['wallpaperArea'] } },
    // Plinte & glafuri
    { stageCode: 'finisaje_detalii', description: 'Plinte MDF/PVC (material)', unit: 'm', qtyKey: 'baseboardLengthM', unitPrice: 28, kind: 'material', moduleKey: 'baseboards' },
    { stageCode: 'finisaje_detalii', description: 'Lucrări montaj plinte', unit: 'm', qtyKey: 'baseboardLengthM', unitPrice: 18, kind: 'labor', moduleKey: 'baseboards' },
    { stageCode: 'finisaje_detalii', description: 'Glafuri uși/ferestre (material)', unit: 'm', qtyKey: 'doorSlopeLengthM', unitPrice: 35, kind: 'material', moduleKey: 'slopes', enabledWhen: { anyQtyKeys: ['doorSlopeLengthM'] } },
    { stageCode: 'finisaje_detalii', description: 'Lucrări glafuri uși/ferestre', unit: 'm', qtyKey: 'doorSlopeLengthM', unitPrice: 60, kind: 'labor', moduleKey: 'slopes', enabledWhen: { anyQtyKeys: ['doorSlopeLengthM'] } },
    // Curățenie
    { stageCode: 'curatenie_predare', description: 'Curățenie post-șantier', unit: 'm²', qtyKey: 'cleaningArea', unitPrice: 12, kind: 'labor', moduleKey: 'cleaning' },
  ],
});
