import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

export const lucrariFinisajBlueprint: EstimateBlueprintConfig = baseConfig({
  wizardSteps: ['object', 'diagnostic', 'stages', 'review'],
  accessDifficultyImpact: { easy: 1.0, medium: 1.05, difficult: 1.15 },
  urgencyImpact: { urgent: 1.15, emergency: 1.35 },
  planPointTypes: [
    { type: 'wall', label: 'Perete', color: '#c084fc' },
    { type: 'ceiling', label: 'Tavan', color: '#e879f9' },
    { type: 'floor', label: 'Pardoseală', color: '#fb7185' },
    { type: 'door', label: 'Ușă', color: '#f43f5e' },
  ],
  workModules: [
    {
      key: 'demolition',
      label: 'Demontare',
      defaultEnabled: false,
      stageCodes: ['demontare'],
      fieldKeys: ['demolitionArea'],
      requiresQtyKeys: ['demolitionArea'],
    },
    {
      key: 'surface_preparation',
      label: 'Pregătire suprafețe',
      defaultEnabled: true,
      stageCodes: ['pregatire'],
      fieldKeys: ['surfaceCondition', 'finishLevel'],
    },
    {
      key: 'plaster',
      label: 'Tencuială',
      defaultEnabled: false,
      stageCodes: ['tencuiala'],
      fieldKeys: ['plasterArea'],
      requiresQtyKeys: ['plasterArea'],
    },
    {
      key: 'putty',
      label: 'Glet / chit',
      defaultEnabled: true,
      stageCodes: ['glet'],
      fieldKeys: ['puttyArea'],
    },
    {
      key: 'paint',
      label: 'Vopsire',
      defaultEnabled: true,
      stageCodes: ['vopsire_tapet'],
      fieldKeys: ['paintArea', 'materialIncluded'],
    },
    {
      key: 'wallpaper',
      label: 'Tapet',
      defaultEnabled: false,
      stageCodes: ['vopsire_tapet'],
      fieldKeys: ['wallpaperArea'],
      requiresQtyKeys: ['wallpaperArea'],
    },
    {
      key: 'drywall',
      label: 'Gips-carton',
      defaultEnabled: false,
      stageCodes: ['tavane'],
      fieldKeys: ['drywallArea'],
      requiresQtyKeys: ['drywallArea'],
    },
    {
      key: 'ceiling',
      label: 'Tavane',
      defaultEnabled: false,
      stageCodes: ['tavane'],
      fieldKeys: ['ceilingArea'],
    },
    {
      key: 'tile',
      label: 'Gresie & faianță',
      defaultEnabled: false,
      stageCodes: ['gresie_faianta'],
      fieldKeys: ['tileArea'],
      requiresQtyKeys: ['tileArea'],
    },
    {
      key: 'flooring',
      label: 'Pardoseală',
      defaultEnabled: false,
      stageCodes: ['pardoseala'],
      fieldKeys: ['flooringArea'],
      requiresQtyKeys: ['flooringArea'],
    },
    {
      key: 'screed',
      label: 'Șapă',
      defaultEnabled: false,
      stageCodes: ['pardoseala'],
      fieldKeys: ['screedArea'],
      requiresQtyKeys: ['screedArea'],
    },
    {
      key: 'baseboards',
      label: 'Plinte',
      defaultEnabled: false,
      stageCodes: ['finisaje_detalii'],
      fieldKeys: ['baseboardLengthM'],
    },
    {
      key: 'slopes',
      label: 'Obloane uși/ferestre',
      defaultEnabled: false,
      stageCodes: ['finisaje_detalii'],
      fieldKeys: ['doorSlopeLengthM'],
      requiresQtyKeys: ['doorSlopeLengthM'],
    },
    {
      key: 'cleaning',
      label: 'Curățenie finală',
      defaultEnabled: false,
      stageCodes: ['curatenie_predare'],
      fieldKeys: [],
    },
  ],
  customFields: [
    {
      key: 'finishArea',
      label: 'Suprafață finisaj (podea)',
      type: 'number',
      unit: 'm²',
      required: true,
      defaultValue: 30,
      validation: { min: 1 },
      section: 'General',
    },
    {
      key: 'wallHeight',
      label: 'Înălțime camere',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 2.7,
      validation: { min: 2, max: 5 },
      section: 'General',
    },
    {
      key: 'demolitionArea',
      label: 'Suprafață demontare',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      section: 'Demontare',
    },
    {
      key: 'plasterArea',
      label: 'Suprafață tencuială',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      section: 'Tencuială',
    },
    {
      key: 'puttyArea',
      label: 'Suprafață glet',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      section: 'Glet',
    },
    {
      key: 'paintArea',
      label: 'Suprafață vopsire',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Lăsat 0 = pereți + tavan calculați automat.',
      section: 'Vopsire',
    },
    {
      key: 'ceilingArea',
      label: 'Suprafață tavan',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      section: 'Tavane',
    },
    {
      key: 'tileArea',
      label: 'Suprafață gresie/faiantă',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      section: 'Gresie',
    },
    {
      key: 'flooringArea',
      label: 'Suprafață pardoseală finisată',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      section: 'Pardoseală',
    },
    {
      key: 'screedArea',
      label: 'Suprafață șapă',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      section: 'Pardoseală',
    },
    {
      key: 'drywallArea',
      label: 'Suprafață gips-carton',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      section: 'Gips-carton',
    },
    {
      key: 'wallpaperArea',
      label: 'Suprafață tapet',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      section: 'Tapet',
    },
    {
      key: 'baseboardLengthM',
      label: 'Lungime plinte',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      section: 'Detalii',
    },
    {
      key: 'doorSlopeLengthM',
      label: 'Lungime obloane uși',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      section: 'Detalii',
    },
    {
      key: 'surfaceCondition',
      label: 'Stare suprafață',
      type: 'select',
      options: ['new', 'old', 'very_bad'],
      required: false,
      defaultValue: 'new',
      section: 'General',
    },
    {
      key: 'finishLevel',
      label: 'Nivel finisaj',
      type: 'select',
      options: ['economic', 'standard', 'premium'],
      required: false,
      defaultValue: 'standard',
      section: 'General',
    },
    {
      key: 'materialIncluded',
      label: 'Materiale incluse în ofertă',
      type: 'boolean',
      required: false,
      defaultValue: true,
      section: 'General',
    },
  ],
  diagnosticQuestions: [
    { key: 'finishArea', label: 'Suprafață finisaj (m²)', type: 'number' },
    { key: 'wallHeight', label: 'Înălțime camere (m)', type: 'number' },
  ],
  defaultStages: [
    { code: 'demontare', name: 'Demontare & pregătire', kind: 'LABOR', defaultLaborHours: 6, durationDays: 2, checklist: ['Demontare finisaje vechi', 'Evacuare deșeuri'], optional: true, moduleKey: 'demolition' },
    { code: 'pregatire', name: 'Pregătire suprafețe', kind: 'LABOR', defaultLaborHours: 5, durationDays: 1, checklist: ['Curățare strat suport', 'Aplicare amorsă'], moduleKey: 'surface_preparation' },
    { code: 'tencuiala', name: 'Tencuială & nivelare', kind: 'MIXED', defaultLaborHours: 10, durationDays: 3, checklist: ['Montaj profile', 'Aplicare tencuială'], optional: true, moduleKey: 'plaster' },
    { code: 'glet', name: 'Glet & șlefuire', kind: 'MIXED', defaultLaborHours: 12, durationDays: 3, checklist: ['Strat glet gros', 'Șlefuire fină'], moduleKey: 'putty' },
    { code: 'tavane', name: 'Tavane & gips-carton', kind: 'MIXED', defaultLaborHours: 8, durationDays: 2, checklist: ['Structură tavan', 'Placare GKL'], optional: true, moduleKey: 'ceiling' },
    { code: 'gresie_faianta', name: 'Gresie & faianță', kind: 'MIXED', defaultLaborHours: 14, durationDays: 4, checklist: ['Hidroizolație', 'Lipire plăci'], optional: true, moduleKey: 'tile' },
    { code: 'pardoseala', name: 'Șapă & pardoseală', kind: 'MIXED', defaultLaborHours: 12, durationDays: 3, checklist: ['Șapă autonivelantă', 'Montaj pardoseală'], optional: true, moduleKey: 'flooring' },
    { code: 'vopsire_tapet', name: 'Vopsire & tapet', kind: 'MIXED', defaultLaborHours: 8, durationDays: 2, checklist: ['Protecție elemente', 'Finisare decorativă'], moduleKey: 'paint' },
    { code: 'finisaje_detalii', name: 'Plinte & obloane', kind: 'MIXED', defaultLaborHours: 4, durationDays: 1, checklist: ['Montaj plinte', 'Obloane uși'], optional: true, moduleKey: 'baseboards' },
    { code: 'curatenie_predare', name: 'Curățenie & predare', kind: 'LABOR', defaultLaborHours: 3, durationDays: 1, checklist: ['Curățenie post-șantier', 'Predare client'], optional: true, moduleKey: 'cleaning' },
  ],
  pricingRules: [
    { stageCode: 'demontare', description: 'Lucrări demontare finisaje', unit: 'm²', qtyKey: 'demolitionAreaLabor', unitPrice: 45, kind: 'labor', moduleKey: 'demolition', enabledWhen: { anyQtyKeys: ['demolitionArea'] } },
    { stageCode: 'pregatire', description: 'Amorsă & pregătire suprafețe', unit: 'm²', qtyKey: 'preparationAreaLabor', unitPrice: 18, kind: 'labor', moduleKey: 'surface_preparation' },
    { stageCode: 'tencuiala', description: 'Tencuială (material)', unit: 'm²', qtyKey: 'plasterArea', unitPrice: 35, wastePct: 10, kind: 'material', moduleKey: 'plaster', enabledWhen: { anyQtyKeys: ['plasterArea'] } },
    { stageCode: 'tencuiala', description: 'Lucrări tencuială', unit: 'm²', qtyKey: 'plasterAreaLabor', unitPrice: 55, kind: 'labor', moduleKey: 'plaster', enabledWhen: { anyQtyKeys: ['plasterArea'] } },
    { stageCode: 'glet', description: 'Glet de încărcare (material)', unit: 'm²', qtyKey: 'puttyArea', unitPrice: 28, wastePct: 12, kind: 'material', moduleKey: 'putty', enabledWhen: { anyQtyKeys: ['puttyArea'] } },
    { stageCode: 'glet', description: 'Lucrări gletuire', unit: 'm²', qtyKey: 'puttyAreaLabor', unitPrice: 42, kind: 'labor', moduleKey: 'putty', enabledWhen: { anyQtyKeys: ['puttyArea'] } },
    { stageCode: 'tavane', description: 'Placaj gips-carton (material)', unit: 'm²', qtyKey: 'drywallArea', unitPrice: 95, wastePct: 10, kind: 'material', moduleKey: 'drywall', enabledWhen: { anyQtyKeys: ['drywallArea'] } },
    { stageCode: 'tavane', description: 'Lucrări montaj gips-carton', unit: 'm²', qtyKey: 'drywallAreaLabor', unitPrice: 85, kind: 'labor', moduleKey: 'drywall', enabledWhen: { anyQtyKeys: ['drywallArea'] } },
    { stageCode: 'tavane', description: 'Finisaj tavan', unit: 'm²', qtyKey: 'ceilingAreaLabor', unitPrice: 38, kind: 'labor', moduleKey: 'ceiling', enabledWhen: { anyQtyKeys: ['ceilingArea'] } },
    { stageCode: 'gresie_faianta', description: 'Gresie/faiantă (material)', unit: 'm²', qtyKey: 'tileArea', unitPrice: 120, wastePct: 10, kind: 'material', moduleKey: 'tile', enabledWhen: { anyQtyKeys: ['tileArea'] } },
    { stageCode: 'gresie_faianta', description: 'Lucrări placare gresie', unit: 'm²', qtyKey: 'tileAreaLabor', unitPrice: 95, kind: 'labor', moduleKey: 'tile', enabledWhen: { anyQtyKeys: ['tileArea'] } },
    { stageCode: 'pardoseala', description: 'Șapă autonivelantă (material)', unit: 'm²', qtyKey: 'screedArea', unitPrice: 45, wastePct: 5, kind: 'material', moduleKey: 'screed', enabledWhen: { anyQtyKeys: ['screedArea'] } },
    { stageCode: 'pardoseala', description: 'Lucrări șapă', unit: 'm²', qtyKey: 'screedAreaLabor', unitPrice: 35, kind: 'labor', moduleKey: 'screed', enabledWhen: { anyQtyKeys: ['screedArea'] } },
    { stageCode: 'pardoseala', description: 'Pardoseală laminat/vinil (material)', unit: 'm²', qtyKey: 'flooringArea', unitPrice: 85, wastePct: 8, kind: 'material', moduleKey: 'flooring', enabledWhen: { anyQtyKeys: ['flooringArea'] } },
    { stageCode: 'pardoseala', description: 'Lucrări montaj pardoseală', unit: 'm²', qtyKey: 'flooringAreaLabor', unitPrice: 48, kind: 'labor', moduleKey: 'flooring', enabledWhen: { anyQtyKeys: ['flooringArea'] } },
    { stageCode: 'vopsire_tapet', description: 'Vopsea lavabilă (material)', unit: 'm²', qtyKey: 'paintArea', unitPrice: 22, wastePct: 12, kind: 'material', moduleKey: 'paint' },
    { stageCode: 'vopsire_tapet', description: 'Lucrări vopsire lavabilă', unit: 'm²', qtyKey: 'paintAreaLabor', unitPrice: 38, kind: 'labor', moduleKey: 'paint' },
    { stageCode: 'vopsire_tapet', description: 'Tapet decorativ (material)', unit: 'm²', qtyKey: 'wallpaperArea', unitPrice: 65, wastePct: 10, kind: 'material', moduleKey: 'wallpaper', enabledWhen: { anyQtyKeys: ['wallpaperArea'] } },
    { stageCode: 'vopsire_tapet', description: 'Lucrări tapet', unit: 'm²', qtyKey: 'wallpaperAreaLabor', unitPrice: 42, kind: 'labor', moduleKey: 'wallpaper', enabledWhen: { anyQtyKeys: ['wallpaperArea'] } },
    { stageCode: 'finisaje_detalii', description: 'Plinte MDF/PVC (material)', unit: 'm', qtyKey: 'baseboardLengthM', unitPrice: 28, kind: 'material', moduleKey: 'baseboards' },
    { stageCode: 'finisaje_detalii', description: 'Lucrări montaj plinte', unit: 'm', qtyKey: 'baseboardLengthM', unitPrice: 18, kind: 'labor', moduleKey: 'baseboards' },
    { stageCode: 'finisaje_detalii', description: 'Obloane uși (material + manoperă)', unit: 'm', qtyKey: 'doorSlopeLengthM', unitPrice: 95, kind: 'labor', moduleKey: 'slopes', enabledWhen: { anyQtyKeys: ['doorSlopeLengthM'] } },
    { stageCode: 'curatenie_predare', description: 'Curățenie post-șantier', unit: 'm²', qtyKey: 'cleaningArea', unitPrice: 12, kind: 'labor', moduleKey: 'cleaning' },
  ],
});
