import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

export const mobilaBlueprint: EstimateBlueprintConfig = baseConfig({
  wizardSteps: ['object', 'diagnostic', 'stages', 'review'],
  accessDifficultyImpact: { easy: 1.0, medium: 1.2, difficult: 1.4, appliesToMaterial: true },
  urgencyImpact: { urgent: 1.2, emergency: 1.4 },
  planPointTypes: [
    { type: 'kitchen_cabinet', label: 'Corp bucătărie', color: '#14b8a6' },
    { type: 'wardrobe', label: 'Dulap dressing', color: '#0f766e' },
    { type: 'bed', label: 'Pat dormitor', color: '#115e59' },
    { type: 'table', label: 'Masă / Birou', color: '#134e4a' },
  ],
  workModules: [
    {
      key: 'design',
      label: 'Măsurători & proiect',
      defaultEnabled: true,
      stageCodes: ['masurare_design'],
      fieldKeys: ['cabinetCount', 'wardrobeCount', 'linearMeters', 'materialType'],
    },
    {
      key: 'cutting',
      label: 'Debitare & cant',
      defaultEnabled: true,
      stageCodes: ['debitare'],
      fieldKeys: ['linearMeters', 'materialType'],
    },
    {
      key: 'hardware',
      label: 'Feronerie & accesorii',
      defaultEnabled: true,
      stageCodes: ['feronerie'],
      fieldKeys: ['hardwareTier', 'drawerCount', 'hingeCount'],
    },
    {
      key: 'assembly',
      label: 'Asamblare corpuri',
      defaultEnabled: true,
      stageCodes: ['asamblare'],
      fieldKeys: ['cabinetCount', 'wardrobeCount'],
    },
    {
      key: 'countertop',
      label: 'Blat & decupaje',
      defaultEnabled: false,
      stageCodes: ['asamblare'],
      fieldKeys: ['countertopLengthM'],
      requiresQtyKeys: ['countertopLengthM'],
    },
    {
      key: 'delivery',
      label: 'Livrare & transport',
      defaultEnabled: false,
      stageCodes: ['livrare'],
      fieldKeys: ['deliveryRequired'],
      requiresQtyKeys: ['deliveryQty'],
    },
    {
      key: 'installation',
      label: 'Montaj la client',
      defaultEnabled: false,
      stageCodes: ['instalare'],
      fieldKeys: ['installationRequired'],
      requiresQtyKeys: ['installationQty'],
    },
  ],
  customFields: [
    {
      key: 'cabinetCount',
      label: 'Număr corpuri mobilier',
      type: 'number',
      unit: 'buc',
      required: true,
      defaultValue: 0,
      validation: { min: 0 },
      section: 'General',
    },
    {
      key: 'wardrobeCount',
      label: 'Număr dulapuri mari',
      type: 'number',
      unit: 'buc',
      required: true,
      defaultValue: 0,
      validation: { min: 0 },
      section: 'General',
    },
    {
      key: 'linearMeters',
      label: 'Metri liniari (prioritar)',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      helpText: 'Dacă e completat, se folosește pentru debitare în locul estimării din corpuri.',
      section: 'Dimensiuni',
    },
    {
      key: 'materialType',
      label: 'Material principal',
      type: 'select',
      options: ['pal', 'mdf', 'lemn', 'hpl'],
      required: false,
      defaultValue: 'pal',
      section: 'Material',
    },
    {
      key: 'hardwareTier',
      label: 'Clasă feronerie',
      type: 'select',
      options: ['basic', 'standard', 'premium'],
      required: false,
      defaultValue: 'basic',
      section: 'Feronerie',
    },
    {
      key: 'drawerCount',
      label: 'Număr sertare',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Feronerie',
    },
    {
      key: 'hingeCount',
      label: 'Număr balamale',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Feronerie',
    },
    {
      key: 'countertopLengthM',
      label: 'Lungime blat',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      section: 'Blat',
    },
    {
      key: 'deliveryRequired',
      label: 'Livrare inclusă',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Livrare',
    },
    {
      key: 'installationRequired',
      label: 'Montaj la client inclus',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Montaj',
    },
  ],
  diagnosticQuestions: [
    { key: 'cabinetCount', label: 'Număr corpuri mobilier', type: 'number' },
    { key: 'wardrobeCount', label: 'Număr dulapuri mari', type: 'number' },
  ],
  defaultStages: [
    { code: 'masurare_design', name: 'Măsurători & proiect', kind: 'LABOR', defaultLaborHours: 4, durationDays: 1, checklist: ['Măsurători la fața locului', 'Schiță aprobată'], moduleKey: 'design' },
    { code: 'debitare', name: 'Debitare & cant PAL/MDF', kind: 'MIXED', defaultLaborHours: 8, durationDays: 2, checklist: ['Optimizare debitare', 'Canturi aplicate'], moduleKey: 'cutting' },
    { code: 'feronerie', name: 'Feronerie & accesorii', kind: 'MATERIAL', defaultLaborHours: 2, durationDays: 1, checklist: ['Balamale', 'Glisiere sertare', 'Mânere'], moduleKey: 'hardware' },
    { code: 'asamblare', name: 'Asamblare corpuri', kind: 'MIXED', defaultLaborHours: 12, durationDays: 3, checklist: ['Carcase asamblate', 'Fațade montate'], moduleKey: 'assembly' },
    { code: 'livrare', name: 'Livrare & transport', kind: 'LABOR', defaultLaborHours: 3, durationDays: 1, checklist: ['Transport protejat', 'Predare pe șantier'], optional: true, moduleKey: 'delivery' },
    { code: 'instalare', name: 'Montaj & reglaj', kind: 'LABOR', defaultLaborHours: 6, durationDays: 1, checklist: ['Fixare perete', 'Reglaj uși & sertare'], optional: true, moduleKey: 'installation' },
    { code: 'predare', name: 'Predare & garanție', kind: 'LABOR', defaultLaborHours: 1, durationDays: 1, checklist: ['Checklist predare', 'Garanție explicată'], moduleKey: 'design' },
  ],
  pricingRules: [
    { stageCode: 'masurare_design', description: 'Proiectare mobilier', unit: 'ore', qtyKey: 'designHours', unitPrice: 180, kind: 'labor', moduleKey: 'design', enabledWhen: { anyQtyKeys: ['designHours'] } },
    { stageCode: 'debitare', description: 'Plăci PAL/MDF (debitare)', unit: 'm', qtyKey: 'cuttingLinearM', unitPrice: 420, wastePct: 12, kind: 'material', moduleKey: 'cutting', enabledWhen: { anyQtyKeys: ['cuttingLinearM'] } },
    { stageCode: 'debitare', description: 'Manoperă debitare & cant', unit: 'm', qtyKey: 'cuttingLinearM', unitPrice: 95, kind: 'labor', moduleKey: 'cutting', enabledWhen: { anyQtyKeys: ['cuttingLinearM'] } },
    { stageCode: 'feronerie', description: 'Feronerie (cost ajustat tier)', unit: 'buc', qtyKey: 'hardwareCostQty', unitPrice: 35, kind: 'material', moduleKey: 'hardware', enabledWhen: { anyQtyKeys: ['hardwareCostQty'] } },
    { stageCode: 'asamblare', description: 'Manoperă asamblare corpuri', unit: 'buc', qtyKey: 'assemblyCabinetQty', unitPrice: 350, kind: 'labor', moduleKey: 'assembly', enabledWhen: { anyQtyKeys: ['assemblyCabinetQty'] } },
    { stageCode: 'asamblare', description: 'Manoperă asamblare dulap', unit: 'buc', qtyKey: 'assemblyWardrobeQty', unitPrice: 950, kind: 'labor', moduleKey: 'assembly', enabledWhen: { anyQtyKeys: ['assemblyWardrobeQty'] } },
    { stageCode: 'asamblare', description: 'Blat bucătărie (material)', unit: 'm', qtyKey: 'countertopLengthM', unitPrice: 380, kind: 'material', moduleKey: 'countertop', enabledWhen: { anyQtyKeys: ['countertopLengthM'] } },
    { stageCode: 'asamblare', description: 'Manoperă montaj blat & decupaje', unit: 'm', qtyKey: 'countertopLengthM', unitPrice: 120, kind: 'labor', moduleKey: 'countertop', enabledWhen: { anyQtyKeys: ['countertopLengthM'] } },
    { stageCode: 'livrare', description: 'Livrare & transport mobilier', unit: 'buc', qtyKey: 'deliveryQty', unitPrice: 450, kind: 'labor', moduleKey: 'delivery', enabledWhen: { moduleEnabled: 'delivery', anyQtyKeys: ['deliveryQty'] } },
    { stageCode: 'instalare', description: 'Montaj la client', unit: 'buc', qtyKey: 'installationQty', unitPrice: 280, kind: 'labor', moduleKey: 'installation', enabledWhen: { moduleEnabled: 'installation', anyQtyKeys: ['installationQty'] } },
    { stageCode: 'predare', description: 'Predare & documentație garanție', unit: 'buc', qtyKey: 'handoverUnits', unitPrice: 150, kind: 'labor', moduleKey: 'design', enabledWhen: { anyQtyKeys: ['handoverUnits'] } },
  ],
});
