import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

export const oknaDveriBlueprint: EstimateBlueprintConfig = baseConfig({
  wizardSteps: ['object', 'diagnostic', 'stages', 'review'],
  accessDifficultyImpact: { easy: 1.0, medium: 1.2, difficult: 1.4, appliesToMaterial: true },
  urgencyImpact: { urgent: 1.15, emergency: 1.3 },
  planPointTypes: [
    { type: 'window', label: 'Fereastră', color: '#2563eb' },
    { type: 'door', label: 'Ușă exterioară', color: '#1d4ed8' },
    { type: 'sliding_door', label: 'Ușă culisantă', color: '#1e3a8a' },
  ],
  workModules: [
    // ---- Pregătire ----
    {
      key: 'measurement',
      label: 'Măsurători & ofertare',
      helpText: 'Deplasare la fața locului pentru măsurători exacte și confirmarea dimensiunilor.',
      defaultEnabled: true,
      stageCodes: ['masurare'],
      fieldKeys: ['windowCount', 'doorCount'],
      section: 'Pregătire',
    },
    {
      key: 'removal',
      label: 'Demontare tâmplărie veche',
      helpText: 'Scoaterea ferestrelor/ușilor existente și curățarea golurilor. Activați pentru înlocuiri.',
      defaultEnabled: false,
      stageCodes: ['demontare'],
      fieldKeys: ['oldFrameRemoval'],
      requiresQtyKeys: ['oldRemovalQty'],
      section: 'Pregătire',
    },
    {
      key: 'disposal',
      label: 'Evacuare tâmplărie veche',
      helpText: 'Transportul și eliminarea tâmplăriei demontate.',
      defaultEnabled: false,
      stageCodes: ['demontare'],
      fieldKeys: ['oldFrameRemoval'],
      requiresQtyKeys: ['disposalQty'],
      section: 'Pregătire',
    },
    // ---- Montaj ----
    {
      key: 'windows',
      label: 'Montaj ferestre',
      helpText: 'Fixarea mecanică și verificarea planeității ferestrelor.',
      defaultEnabled: true,
      stageCodes: ['montaj', 'etanșare'],
      fieldKeys: ['windowCount', 'installationType'],
      section: 'Montaj',
    },
    {
      key: 'doors',
      label: 'Montaj uși',
      helpText: 'Montajul ușilor exterioare / culisante.',
      defaultEnabled: true,
      stageCodes: ['montaj', 'etanșare'],
      fieldKeys: ['doorCount', 'installationType'],
      section: 'Montaj',
    },
    {
      key: 'warm_installation',
      label: 'Montaj termic (benzi)',
      helpText: 'Montaj cu benzi de etanșare interior/exterior (sistem „cald") — crește manopera dar elimină punțile termice.',
      defaultEnabled: false,
      stageCodes: ['etanșare'],
      fieldKeys: ['installationType'],
      requiresQtyKeys: ['warmInstallationUnits'],
      section: 'Montaj',
    },
    // ---- Finisaje ----
    {
      key: 'sills',
      label: 'Glafuri & pervazuri',
      helpText: 'Glafuri interioare și pervazuri exterioare la ferestre.',
      defaultEnabled: true,
      stageCodes: ['glafuri'],
      fieldKeys: ['sillCount'],
      section: 'Finisaje',
    },
    {
      key: 'slopes',
      label: 'Obloane interioare (spaleți)',
      helpText: 'Finisarea spaleților interiori din jurul golurilor după montaj.',
      defaultEnabled: true,
      stageCodes: ['glafuri'],
      fieldKeys: [],
      section: 'Finisaje',
    },
    {
      key: 'nets',
      label: 'Plase anti-insecte',
      helpText: 'Plase mobile / fixe contra insectelor pentru ferestre.',
      defaultEnabled: false,
      stageCodes: ['reglaj'],
      fieldKeys: ['mosquitoNetCount'],
      requiresQtyKeys: ['mosquitoNetCount'],
      section: 'Finisaje',
    },
  ],
  customFields: [
    // ---- General ----
    {
      key: 'windowCount',
      label: 'Număr ferestre',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      validation: { min: 0 },
      helpText: 'Numărul de ferestre de montat.',
      placeholder: 'ex. 5',
      section: 'General',
    },
    {
      key: 'doorCount',
      label: 'Număr uși exterioare',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      validation: { min: 0 },
      helpText: 'Numărul de uși exterioare / culisante de montat.',
      placeholder: 'ex. 1',
      section: 'General',
    },
    {
      key: 'installationType',
      label: 'Tip montaj',
      type: 'select',
      options: ['standard', 'warm_installation', 'renovation'],
      required: false,
      defaultValue: 'standard',
      helpText: 'Standard, montaj termic (benzi) sau renovare (goluri neregulate).',
      warningRules: [
        { when: "installationType === 'warm_installation'", message: 'Montaj termic — manopera crește automat cu +35%.' },
        { when: "installationType === 'renovation'", message: 'Montaj în renovare — manopera crește automat cu +20%.' },
      ],
      section: 'General',
    },
    // ---- Avansat ----
    {
      key: 'oldFrameRemoval',
      label: 'Demontare tâmplărie veche',
      type: 'boolean',
      required: false,
      defaultValue: false,
      helpText: 'Activează liniile de demontare și evacuare (per gol).',
      section: 'Avansat',
    },
    {
      key: 'sillCount',
      label: 'Număr glafuri / pervazuri',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      helpText: 'Gol = câte unul per fereastră.',
      section: 'Avansat',
    },
    {
      key: 'mosquitoNetCount',
      label: 'Plase anti-insecte',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      helpText: 'Numărul de plase de montat (activați modulul „Plase anti-insecte").',
      section: 'Avansat',
    },
  ],
  diagnosticQuestions: [],
  defaultStages: [
    { code: 'masurare', name: 'Măsurători & acord', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Măsurători la fața locului', 'Confirmare dimensiuni'], moduleKey: 'measurement' },
    { code: 'demontare', name: 'Demontare tâmplărie veche', kind: 'LABOR', defaultLaborHours: 3, durationDays: 1, checklist: ['Demontare cercevele', 'Curățare goluri'], optional: true, moduleKey: 'removal' },
    { code: 'montaj', name: 'Montaj ferestre & uși', kind: 'MIXED', defaultLaborHours: 8, durationDays: 2, checklist: ['Fixare mecanică', 'Verificare laser planeitate'], moduleKey: 'windows' },
    { code: 'etanșare', name: 'Etanșare & spumă', kind: 'MIXED', defaultLaborHours: 4, durationDays: 1, checklist: ['Spumă PU profesională', 'Benzi etanșare'], moduleKey: 'windows' },
    { code: 'glafuri', name: 'Glafuri, pervazuri, obloane', kind: 'MIXED', defaultLaborHours: 4, durationDays: 1, checklist: ['Montaj glaf exterior/interior', 'Obloane interioare'], moduleKey: 'sills' },
    { code: 'reglaj', name: 'Reglaj & predare', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Reglaj feronerie', 'Test etanșeitate'], moduleKey: 'windows' },
  ],
  pricingRules: [
    { stageCode: 'masurare', description: 'Măsurători & plan montaj', unit: 'buc', qtyKey: 'measurementUnits', unitPrice: 350, kind: 'labor', moduleKey: 'measurement', enabledWhen: { anyQtyKeys: ['measurementUnits'] } },
    { stageCode: 'demontare', description: 'Demontare tâmplărie veche', unit: 'buc', qtyKey: 'oldRemovalQty', unitPrice: 120, kind: 'labor', moduleKey: 'removal', enabledWhen: { anyQtyKeys: ['oldRemovalQty'] } },
    { stageCode: 'demontare', description: 'Evacuare tâmplărie veche', unit: 'buc', qtyKey: 'disposalQty', unitPrice: 45, kind: 'labor', moduleKey: 'disposal', enabledWhen: { moduleEnabled: 'disposal', anyQtyKeys: ['disposalQty'] } },
    { stageCode: 'montaj', description: 'Lucrări montaj fereastră', unit: 'buc', qtyKey: 'windowCountLabor', unitPrice: 380, kind: 'labor', moduleKey: 'windows', enabledWhen: { anyQtyKeys: ['windowCount'] } },
    { stageCode: 'montaj', description: 'Lucrări montaj ușă', unit: 'buc', qtyKey: 'doorCountLabor', unitPrice: 750, kind: 'labor', moduleKey: 'doors', enabledWhen: { anyQtyKeys: ['doorCount'] } },
    { stageCode: 'etanșare', description: 'Spumă montaj profesională', unit: 'buc', qtyKey: 'foamTubes', unitPrice: 85, kind: 'material', moduleKey: 'windows' },
    { stageCode: 'etanșare', description: 'Montaj termic (benzi interior/exterior)', unit: 'buc', qtyKey: 'warmInstallationUnits', unitPrice: 220, kind: 'labor', moduleKey: 'warm_installation', enabledWhen: { moduleEnabled: 'warm_installation', anyQtyKeys: ['warmInstallationUnits'] } },
    { stageCode: 'glafuri', description: 'Glaf / pervaz (material)', unit: 'm', qtyKey: 'sillLengthM', unitPrice: 95, kind: 'material', moduleKey: 'sills', enabledWhen: { anyQtyKeys: ['sillLengthM'] } },
    { stageCode: 'glafuri', description: 'Lucrări montaj glafuri', unit: 'm', qtyKey: 'sillLengthM', unitPrice: 55, kind: 'labor', moduleKey: 'sills', enabledWhen: { anyQtyKeys: ['sillLengthM'] } },
    { stageCode: 'glafuri', description: 'Obloane interioare', unit: 'm', qtyKey: 'slopesLengthM', unitPrice: 65, kind: 'labor', moduleKey: 'slopes', enabledWhen: { anyQtyKeys: ['slopesLengthM'] } },
    { stageCode: 'reglaj', description: 'Plase anti-insecte', unit: 'buc', qtyKey: 'mosquitoNetCount', unitPrice: 180, kind: 'material', moduleKey: 'nets', enabledWhen: { moduleEnabled: 'nets', anyQtyKeys: ['mosquitoNetCount'] } },
    { stageCode: 'reglaj', description: 'Reglaj feronerie & predare', unit: 'buc', qtyKey: 'regulationUnits', unitPrice: 85, kind: 'labor', moduleKey: 'windows', enabledWhen: { anyQtyKeys: ['regulationUnits'] } },
  ],
});
