import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

export const oknaDveriBlueprint: EstimateBlueprintConfig = baseConfig({
  wizardSteps: ['object', 'diagnostic', 'stages', 'review'],
  accessDifficultyImpact: { easy: 1.0, medium: 1.2, difficult: 1.4, appliesToMaterial: true },
  urgencyImpact: { urgent: 1.15, emergency: 1.3 },
  planPointTypes: [
    { type: 'window', label: 'Fereastră', color: '#2563eb' },
    { type: 'door', label: 'Ușă exterioară', color: '#1d4ed8' },
    { type: 'sliding_door', label: 'Ușă culisantă', color: '#1e3a8a' },
  ],
  workModules: [
    {
      key: 'measurement',
      label: 'Măsurători & ofertare',
      defaultEnabled: true,
      stageCodes: ['masurare'],
      fieldKeys: ['windowCount', 'doorCount', 'windowAreaM2', 'doorAreaM2'],
    },
    {
      key: 'removal',
      label: 'Demontare tâmplărie veche',
      defaultEnabled: false,
      stageCodes: ['demontare'],
      fieldKeys: ['oldFrameRemoval'],
      requiresQtyKeys: ['oldRemovalQty'],
    },
    {
      key: 'windows',
      label: 'Montaj ferestre',
      defaultEnabled: true,
      stageCodes: ['montaj', 'etanșare'],
      fieldKeys: ['windowCount', 'installationType', 'profileClass', 'glassPackage'],
    },
    {
      key: 'doors',
      label: 'Montaj uși',
      defaultEnabled: true,
      stageCodes: ['montaj', 'etanșare'],
      fieldKeys: ['doorCount', 'installationType'],
    },
    {
      key: 'warm_installation',
      label: 'Montaj termic (benzi)',
      defaultEnabled: false,
      stageCodes: ['etanșare'],
      fieldKeys: ['installationType'],
      requiresQtyKeys: ['warmInstallationUnits'],
    },
    {
      key: 'sills',
      label: 'Glafuri & pervazuri',
      defaultEnabled: true,
      stageCodes: ['glafuri'],
      fieldKeys: ['sillCount'],
    },
    {
      key: 'slopes',
      label: 'Obloane interioare',
      defaultEnabled: true,
      stageCodes: ['glafuri'],
      fieldKeys: [],
    },
    {
      key: 'nets',
      label: 'Plase anti-insecte',
      defaultEnabled: false,
      stageCodes: ['reglaj'],
      fieldKeys: ['mosquitoNetCount'],
      requiresQtyKeys: ['mosquitoNetCount'],
    },
    {
      key: 'disposal',
      label: 'Evacuare tâmplărie veche',
      defaultEnabled: false,
      stageCodes: ['demontare'],
      fieldKeys: ['oldFrameRemoval'],
      requiresQtyKeys: ['disposalQty'],
    },
  ],
  customFields: [
    {
      key: 'windowCount',
      label: 'Număr ferestre',
      type: 'number',
      unit: 'buc',
      required: true,
      defaultValue: 0,
      validation: { min: 0 },
      section: 'General',
    },
    {
      key: 'doorCount',
      label: 'Număr uși exterioare',
      type: 'number',
      unit: 'buc',
      required: true,
      defaultValue: 0,
      validation: { min: 0 },
      section: 'General',
    },
    {
      key: 'windowAreaM2',
      label: 'Suprafață totală ferestre',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      section: 'Dimensiuni',
    },
    {
      key: 'doorAreaM2',
      label: 'Suprafață totală uși',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      section: 'Dimensiuni',
    },
    {
      key: 'oldFrameRemoval',
      label: 'Demontare tâmplărie veche',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Demontare',
    },
    {
      key: 'sillCount',
      label: 'Număr glafuri / pervazuri',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Glafuri',
    },
    {
      key: 'mosquitoNetCount',
      label: 'Plase anti-insecte',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      section: 'Accesorii',
    },
    {
      key: 'installationType',
      label: 'Tip montaj',
      type: 'select',
      options: ['standard', 'warm_installation', 'renovation'],
      required: false,
      defaultValue: 'standard',
      helpText: 'Montaj termic crește manopera cu 35%.',
      section: 'Montaj',
    },
    {
      key: 'profileClass',
      label: 'Clasă profil',
      type: 'select',
      options: ['econom', 'standard', 'premium'],
      required: false,
      defaultValue: 'standard',
      section: 'Material',
    },
    {
      key: 'glassPackage',
      label: 'Pachet sticlă',
      type: 'select',
      options: ['double', 'triple', 'low_e'],
      required: false,
      defaultValue: 'double',
      section: 'Material',
    },
  ],
  diagnosticQuestions: [
    { key: 'windowCount', label: 'Număr ferestre', type: 'number' },
    { key: 'doorCount', label: 'Număr uși exterioare', type: 'number' },
  ],
  defaultStages: [
    { code: 'masurare', name: 'Măsurători & acord', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Măsurători la fața locului', 'Confirmare dimensiuni'], moduleKey: 'measurement' },
    { code: 'demontare', name: 'Demontare tâmplărie veche', kind: 'LABOR', defaultLaborHours: 3, durationDays: 1, checklist: ['Demontare cercevele', 'Curățare goluri'], optional: true, moduleKey: 'removal' },
    { code: 'montaj', name: 'Montaj ferestre & uși', kind: 'MIXED', defaultLaborHours: 8, durationDays: 2, checklist: ['Fixare mecanică', 'Verificare laser planeitate'], moduleKey: 'windows' },
    { code: 'etanșare', name: 'Etanșare & spumă', kind: 'MIXED', defaultLaborHours: 4, durationDays: 1, checklist: ['Spumă PU profesională', 'Benzi etanșare'], moduleKey: 'windows' },
    { code: 'glafuri', name: 'Glafuri, pervazuri, obloane', kind: 'MIXED', defaultLaborHours: 4, durationDays: 1, checklist: ['Montaj glaf exterior/interior', 'Obloane interioare'], moduleKey: 'sills' },
    { code: 'reglaj', name: 'Reglaj & predare', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Reglaj feronerie', 'Test etanșeitate'], moduleKey: 'windows' },
  ],
  pricingRules: [
    { stageCode: 'masurare', description: 'Măsurători & plan montaj', unit: 'buc', qtyKey: 'measurementUnits', unitPrice: 350, kind: 'labor', moduleKey: 'measurement', enabledWhen: { anyQtyKeys: ['measurementUnits'] } },
    { stageCode: 'demontare', description: 'Demontare tâmplărie veche', unit: 'buc', qtyKey: 'oldRemovalQty', unitPrice: 120, kind: 'labor', moduleKey: 'removal', enabledWhen: { anyQtyKeys: ['oldRemovalQty'] } },
    { stageCode: 'demontare', description: 'Evacuare tâmplărie veche', unit: 'buc', qtyKey: 'disposalQty', unitPrice: 45, kind: 'labor', moduleKey: 'disposal', enabledWhen: { moduleEnabled: 'disposal', anyQtyKeys: ['disposalQty'] } },
    { stageCode: 'montaj', description: 'Lucrări montaj fereastră', unit: 'buc', qtyKey: 'windowCountLabor', unitPrice: 380, kind: 'labor', moduleKey: 'windows', enabledWhen: { anyQtyKeys: ['windowCount'] } },
    { stageCode: 'montaj', description: 'Lucrări montaj ușă', unit: 'buc', qtyKey: 'doorCountLabor', unitPrice: 750, kind: 'labor', moduleKey: 'doors', enabledWhen: { anyQtyKeys: ['doorCount'] } },
    { stageCode: 'etanșare', description: 'Spumă montaj profesională', unit: 'buc', qtyKey: 'foamTubes', unitPrice: 85, kind: 'material', moduleKey: 'windows' },
    { stageCode: 'etanșare', description: 'Montaj termic (benzi interior/exterior)', unit: 'buc', qtyKey: 'warmInstallationUnits', unitPrice: 220, kind: 'labor', moduleKey: 'warm_installation', enabledWhen: { moduleEnabled: 'warm_installation', anyQtyKeys: ['warmInstallationUnits'] } },
    { stageCode: 'glafuri', description: 'Glaf / pervaz (material)', unit: 'm', qtyKey: 'sillLengthM', unitPrice: 95, kind: 'material', moduleKey: 'sills', enabledWhen: { anyQtyKeys: ['sillLengthM'] } },
    { stageCode: 'glafuri', description: 'Lucrări montaj glafuri', unit: 'm', qtyKey: 'sillLengthM', unitPrice: 55, kind: 'labor', moduleKey: 'sills', enabledWhen: { anyQtyKeys: ['sillLengthM'] } },
    { stageCode: 'glafuri', description: 'Obloane interioare', unit: 'm', qtyKey: 'slopesLengthM', unitPrice: 65, kind: 'labor', moduleKey: 'slopes', enabledWhen: { anyQtyKeys: ['slopesLengthM'] } },
    { stageCode: 'reglaj', description: 'Plase anti-insecte', unit: 'buc', qtyKey: 'mosquitoNetCount', unitPrice: 180, kind: 'material', moduleKey: 'nets', enabledWhen: { moduleEnabled: 'nets', anyQtyKeys: ['mosquitoNetCount'] } },
    { stageCode: 'reglaj', description: 'Reglaj feronerie & predare', unit: 'buc', qtyKey: 'regulationUnits', unitPrice: 85, kind: 'labor', moduleKey: 'windows', enabledWhen: { anyQtyKeys: ['regulationUnits'] } },
  ],
});
