import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

export const panouriSolareBlueprint: EstimateBlueprintConfig = baseConfig({
  wizardSteps: ['object', 'diagnostic', 'stages', 'review'],
  accessDifficultyImpact: { easy: 1.0, medium: 1.2, difficult: 1.35 },
  urgencyImpact: { urgent: 1.1, emergency: 1.2 },
  planPointTypes: [
    { type: 'solar_panel', label: 'Panou solar fotovoltaic', color: '#10b981' },
    { type: 'inverter', label: 'Invertor hibrid', color: '#047857' },
    { type: 'battery', label: 'Acumulator baterii', color: '#065f46' },
    { type: 'meter', label: 'Contor bidirecțional', color: '#064e3b' },
  ],
  workModules: [
    // ---- Proiectare ----
    {
      key: 'audit',
      label: 'Audit & dimensionare',
      helpText: 'Inspecția acoperișului și calculul puterii necesare. Stă la baza întregii oferte.',
      defaultEnabled: true,
      stageCodes: ['audit'],
      fieldKeys: ['panelCount', 'systemPowerKw', 'panelWp', 'roofType'],
      section: 'Proiectare',
    },
    {
      key: 'project',
      label: 'Proiect & documentație',
      helpText: 'Schema unifilară, lista de materiale și documentația tehnică a sistemului.',
      defaultEnabled: true,
      stageCodes: ['proiectare'],
      fieldKeys: ['gridConnection'],
      section: 'Proiectare',
    },
    {
      key: 'permits',
      label: 'Autorizații & avize',
      helpText: 'Avize de racordare și autorizații pentru sistemele on-grid (prosumator). Activați dacă sunt necesare.',
      defaultEnabled: false,
      stageCodes: ['proiectare'],
      fieldKeys: ['permitsRequired'],
      requiresQtyKeys: ['permitUnits'],
      section: 'Proiectare',
    },
    // ---- Montaj ----
    {
      key: 'mounts',
      label: 'Structură de prindere',
      helpText: 'Profile de aluminiu și prinderi adaptate tipului de acoperiș. Câte 1 set per panou.',
      defaultEnabled: true,
      stageCodes: ['suport'],
      fieldKeys: ['roofType', 'panelCount'],
      requiresQtyKeys: ['structureQty'],
      section: 'Montaj',
    },
    {
      key: 'panels',
      label: 'Montaj panouri',
      helpText: 'Fixarea panourilor pe structură și conexiunile DC dintre ele.',
      defaultEnabled: true,
      stageCodes: ['panouri'],
      fieldKeys: ['panelCount'],
      requiresQtyKeys: ['panelCount'],
      section: 'Montaj',
    },
    {
      key: 'optimizers',
      label: 'Optimizatoare / micro-invertoare',
      helpText: 'Optimizatoare de putere per panou — recomandate pentru acoperișuri cu umbrire parțială. Câte 1 per panou.',
      defaultEnabled: false,
      stageCodes: ['panouri'],
      fieldKeys: [],
      section: 'Montaj',
    },
    // ---- Echipamente ----
    {
      key: 'inverter',
      label: 'Invertor',
      helpText: 'Convertește curentul DC al panourilor în AC. Numărul nu se calculează automat din panouri.',
      defaultEnabled: true,
      stageCodes: ['invertor_baterii'],
      fieldKeys: ['inverterCount', 'gridConnection'],
      requiresQtyKeys: ['inverterCount'],
      section: 'Echipamente',
    },
    {
      key: 'batteries',
      label: 'Acumulatori',
      helpText: 'Stocare LiFePO4 pentru consum nocturn / backup. Lăsați 0 kWh pentru sisteme fără baterii.',
      defaultEnabled: true,
      stageCodes: ['invertor_baterii'],
      fieldKeys: ['batteryCapacity'],
      requiresQtyKeys: ['batteryCapacity'],
      section: 'Echipamente',
    },
    // ---- Electric ----
    {
      key: 'protection',
      label: 'Protecții DC/AC & împământare',
      helpText: 'Tablouri de protecție DC/AC, cablare și împământare cu protecție la descărcări.',
      defaultEnabled: true,
      stageCodes: ['electric'],
      fieldKeys: ['cableLengthM'],
      section: 'Electric',
    },
    {
      key: 'ev_charger',
      label: 'Stație de încărcare auto (wallbox)',
      helpText: 'Stație de încărcare pentru mașina electrică, alimentată din sistemul fotovoltaic.',
      defaultEnabled: false,
      stageCodes: ['electric'],
      fieldKeys: ['evChargerCount'],
      requiresQtyKeys: ['evChargerCount'],
      section: 'Electric',
    },
    // ---- Finalizare ----
    {
      key: 'grid_connection',
      label: 'Conectare la rețea',
      helpText: 'Contor bidirecțional și punerea sub tensiune. Nu se aplică sistemelor off-grid.',
      defaultEnabled: true,
      stageCodes: ['conectare'],
      fieldKeys: ['gridConnection'],
      requiresQtyKeys: ['gridConnectionUnits'],
      section: 'Finalizare',
    },
    {
      key: 'monitoring',
      label: 'Monitorizare & telemetrie',
      helpText: 'Gateway de monitorizare și aplicație pentru client (producție în timp real).',
      defaultEnabled: false,
      stageCodes: ['monitorizare'],
      fieldKeys: ['monitoringRequired'],
      requiresQtyKeys: ['monitoringUnits'],
      section: 'Finalizare',
    },
  ],
  customFields: [
    // ---- General (always visible) ----
    {
      key: 'panelCount',
      label: 'Număr panouri solare',
      type: 'number',
      unit: 'buc',
      required: true,
      defaultValue: 1,
      validation: { min: 1, max: 100 },
      helpText: 'Numărul total de panouri fotovoltaice. Determină structura, optimizatoarele și manopera.',
      placeholder: 'ex. 12',
      warningRules: [
        { when: 'panelCount > 30', message: 'Sistem mare (>30 panouri) — devizul este orientativ și necesită verificare manuală.' },
      ],
      section: 'General',
    },
    {
      key: 'systemPowerKw',
      label: 'Putere instalată (kW)',
      type: 'number',
      required: false,
      defaultValue: 0,
      helpText: 'Gol = se calculează automat din numărul de panouri × puterea unui panou (Wp).',
      placeholder: 'ex. 5',
      section: 'General',
    },
    {
      key: 'roofType',
      label: 'Tip acoperiș / amplasare',
      type: 'select',
      options: ['metal', 'tile', 'flat', 'ground'],
      required: false,
      defaultValue: 'metal',
      helpText: 'Tipul suportului — influențează automat manopera structurii de prindere.',
      warningRules: [
        { when: "roofType === 'tile'", message: 'Acoperiș din țiglă — manopera structurii crește automat cu +15%.' },
        { when: "roofType === 'flat'", message: 'Acoperiș plat (balast/înclinare) — manopera structurii crește automat cu +25%.' },
        { when: "roofType === 'ground'", message: 'Montaj la sol — manopera structurii crește automat cu +35%.' },
      ],
      section: 'General',
    },
    {
      key: 'gridConnection',
      label: 'Tip conectare',
      type: 'select',
      options: ['on_grid', 'off_grid', 'hybrid'],
      required: false,
      defaultValue: 'on_grid',
      helpText: 'On-grid (prosumator), off-grid (autonom) sau hibrid (rețea + baterii).',
      section: 'General',
    },
    // ---- Avansat (collapsed) ----
    {
      key: 'panelWp',
      label: 'Putere per panou (Wp)',
      type: 'number',
      required: false,
      defaultValue: 0,
      helpText: 'Puterea nominală a unui panou (ex. 450 W). Folosită pentru a calcula puterea totală a sistemului.',
      placeholder: 'ex. 450',
      section: 'Avansat',
    },
    {
      key: 'inverterCount',
      label: 'Număr invertoare',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 1,
      validation: { min: 1 },
      helpText: 'De obicei 1. Nu se calculează automat din numărul de panouri.',
      section: 'Avansat',
    },
    {
      key: 'batteryCapacity',
      label: 'Capacitate acumulator',
      type: 'number',
      unit: 'kWh',
      required: false,
      defaultValue: 0,
      validation: { min: 0 },
      helpText: 'Capacitatea totală de stocare. Lăsați 0 pentru sisteme fără baterii.',
      placeholder: 'ex. 10',
      section: 'Avansat',
    },
    {
      key: 'cableLengthM',
      label: 'Lungime cablu DC/AC',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      helpText: 'Gol = se estimează automat 2,5 m per panou.',
      section: 'Avansat',
    },
    {
      key: 'evChargerCount',
      label: 'Stații de încărcare auto',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      helpText: 'Numărul de wallbox-uri de instalat (activați modulul „Stație de încărcare auto").',
      section: 'Avansat',
    },
    {
      key: 'permitsRequired',
      label: 'Autorizații / avize necesare',
      type: 'boolean',
      required: false,
      defaultValue: false,
      helpText: 'Activează linia de cost pentru avizele de racordare (prosumator).',
      section: 'Avansat',
    },
    {
      key: 'monitoringRequired',
      label: 'Monitorizare online',
      type: 'boolean',
      required: false,
      defaultValue: false,
      helpText: 'Activează sistemul de monitorizare a producției în timp real.',
      section: 'Avansat',
    },
  ],
  diagnosticQuestions: [],
  defaultStages: [
    { code: 'audit', name: 'Audit acoperiș & dimensionare', kind: 'LABOR', defaultLaborHours: 4, durationDays: 1, checklist: ['Inspecție acoperiș', 'Calcul producție'], moduleKey: 'audit' },
    { code: 'proiectare', name: 'Proiect & scheme electrice', kind: 'LABOR', defaultLaborHours: 8, durationDays: 2, checklist: ['Schema unifilară', 'Listă materiale'], moduleKey: 'project' },
    { code: 'suport', name: 'Structură de prindere', kind: 'MIXED', defaultLaborHours: 8, durationDays: 2, checklist: ['Profile aluminiu', 'Etanșare penetrări'], moduleKey: 'mounts' },
    { code: 'panouri', name: 'Montaj panouri fotovoltaice', kind: 'MIXED', defaultLaborHours: 12, durationDays: 2, checklist: ['Fixare panouri', 'Conexiuni DC'], moduleKey: 'panels' },
    { code: 'electric', name: 'Cablare, protecții & împământare', kind: 'MIXED', defaultLaborHours: 8, durationDays: 1, checklist: ['Tablouri DC/AC', 'Împământare'], moduleKey: 'protection' },
    { code: 'invertor_baterii', name: 'Invertor & acumulatori', kind: 'MIXED', defaultLaborHours: 8, durationDays: 1, checklist: ['Montaj invertor', 'Conectare baterii'], moduleKey: 'inverter' },
    { code: 'conectare', name: 'Conectare la rețea', kind: 'LABOR', defaultLaborHours: 4, durationDays: 1, checklist: ['Contor bidirecțional', 'Punere sub tensiune'], moduleKey: 'grid_connection' },
    { code: 'monitorizare', name: 'Monitorizare & telemetrie', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Gateway monitoring', 'Aplicație client'], optional: true, moduleKey: 'monitoring' },
    { code: 'predare', name: 'Predare & instruire client', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Teste funcționare', 'Instruire utilizare'], moduleKey: 'audit' },
  ],
  pricingRules: [
    { stageCode: 'audit', description: 'Audit acoperiș & dimensionare sistem', unit: 'ore', qtyKey: 'auditHours', unitPrice: 280, kind: 'labor', moduleKey: 'audit' },
    { stageCode: 'proiectare', description: 'Proiectare & documentație tehnică', unit: 'ore', qtyKey: 'projectHours', unitPrice: 320, kind: 'labor', moduleKey: 'project' },
    { stageCode: 'proiectare', description: 'Autorizații & avize', unit: 'buc', qtyKey: 'permitUnits', unitPrice: 2500, kind: 'labor', moduleKey: 'permits', enabledWhen: { moduleEnabled: 'permits', anyQtyKeys: ['permitUnits'] } },
    { stageCode: 'suport', description: 'Structură prindere acoperiș (material)', unit: 'buc', qtyKey: 'structureQty', unitPrice: 450, kind: 'material', moduleKey: 'mounts', enabledWhen: { anyQtyKeys: ['structureQty'] } },
    { stageCode: 'suport', description: 'Montaj structură prindere', unit: 'buc', qtyKey: 'structureLaborQty', unitPrice: 120, kind: 'labor', moduleKey: 'mounts', enabledWhen: { anyQtyKeys: ['structureLaborQty'] } },
    { stageCode: 'panouri', description: 'Lucrări montaj panou fotovoltaic', unit: 'buc', qtyKey: 'panelLaborQty', unitPrice: 350, kind: 'labor', moduleKey: 'panels', enabledWhen: { anyQtyKeys: ['panelLaborQty'] } },
    { stageCode: 'panouri', description: 'Optimizatoare de putere / micro-invertoare (material)', unit: 'buc', qtyKey: 'optimizerCount', unitPrice: 650, kind: 'material', moduleKey: 'optimizers', enabledWhen: { moduleEnabled: 'optimizers', anyQtyKeys: ['optimizerCount'] } },
    { stageCode: 'electric', description: 'Cablu solar DC/AC (material)', unit: 'm', qtyKey: 'cableLengthM', unitPrice: 18, wastePct: 10, kind: 'material', moduleKey: 'protection', enabledWhen: { anyQtyKeys: ['cableLengthM'] } },
    { stageCode: 'electric', description: 'Tablou protecție DC/AC', unit: 'buc', qtyKey: 'protectionPanelUnits', unitPrice: 1800, kind: 'material', moduleKey: 'protection' },
    { stageCode: 'electric', description: 'Împământare & protecție descărcări', unit: 'buc', qtyKey: 'groundingUnits', unitPrice: 950, kind: 'labor', moduleKey: 'protection' },
    { stageCode: 'electric', description: 'Stație de încărcare auto (wallbox)', unit: 'buc', qtyKey: 'evChargerCount', unitPrice: 12000, kind: 'material', moduleKey: 'ev_charger', enabledWhen: { moduleEnabled: 'ev_charger', anyQtyKeys: ['evChargerCount'] } },
    { stageCode: 'electric', description: 'Lucrări montaj stație de încărcare', unit: 'buc', qtyKey: 'evChargerCount', unitPrice: 1500, kind: 'labor', moduleKey: 'ev_charger', enabledWhen: { moduleEnabled: 'ev_charger', anyQtyKeys: ['evChargerCount'] } },
    { stageCode: 'invertor_baterii', description: 'Lucrări instalare invertor', unit: 'buc', qtyKey: 'inverterCount', unitPrice: 2200, kind: 'labor', moduleKey: 'inverter', enabledWhen: { anyQtyKeys: ['inverterCount'] } },
    { stageCode: 'invertor_baterii', description: 'Acumulator LiFePO4 (stocare)', unit: 'kWh', qtyKey: 'batteryCapacity', unitPrice: 7500, kind: 'material', moduleKey: 'batteries', enabledWhen: { anyQtyKeys: ['batteryCapacity'] } },
    { stageCode: 'conectare', description: 'Conectare la rețea & contor bidirecțional', unit: 'buc', qtyKey: 'gridConnectionUnits', unitPrice: 3200, kind: 'labor', moduleKey: 'grid_connection', enabledWhen: { anyQtyKeys: ['gridConnectionUnits'] } },
    { stageCode: 'monitorizare', description: 'Sistem monitorizare online', unit: 'buc', qtyKey: 'monitoringUnits', unitPrice: 1800, kind: 'labor', moduleKey: 'monitoring', enabledWhen: { moduleEnabled: 'monitoring', anyQtyKeys: ['monitoringUnits'] } },
    { stageCode: 'predare', description: 'Predare & instruire client', unit: 'buc', qtyKey: 'handoverUnits', unitPrice: 450, kind: 'labor', moduleKey: 'audit' },
  ],
});
