import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

export const panouriSolareBlueprint: EstimateBlueprintConfig = baseConfig({
  planPointTypes: [
    { type: 'solar_panel', label: 'Panou solar fotovoltaic', color: '#10b981' },
    { type: 'inverter', label: 'Invertor hibrid', color: '#047857' },
    { type: 'battery', label: 'Acumulator baterii', color: '#065f46' },
    { type: 'meter', label: 'Contor bidirecțional', color: '#064e3b' },
  ],
  workModules: [
    {
      key: 'audit',
      label: 'Audit & dimensionare',
      defaultEnabled: true,
      stageCodes: ['audit'],
      fieldKeys: ['panelCount', 'systemPowerKw', 'roofType'],
    },
    {
      key: 'project',
      label: 'Proiect & documentație',
      defaultEnabled: true,
      stageCodes: ['proiectare'],
      fieldKeys: ['gridConnection', 'structureType'],
    },
    {
      key: 'mounts',
      label: 'Structură de prindere',
      defaultEnabled: true,
      stageCodes: ['suport'],
      fieldKeys: ['roofType', 'structureType', 'panelCount'],
      requiresQtyKeys: ['structureQty'],
    },
    {
      key: 'panels',
      label: 'Montaj panouri',
      defaultEnabled: true,
      stageCodes: ['panouri'],
      fieldKeys: ['panelCount'],
      requiresQtyKeys: ['panelCount'],
    },
    {
      key: 'inverter',
      label: 'Invertor',
      defaultEnabled: true,
      stageCodes: ['invertor_baterii'],
      fieldKeys: ['inverterCount', 'gridConnection'],
      requiresQtyKeys: ['inverterCount'],
    },
    {
      key: 'batteries',
      label: 'Acumulatori',
      defaultEnabled: true,
      stageCodes: ['invertor_baterii'],
      fieldKeys: ['batteryCapacity'],
      requiresQtyKeys: ['batteryCapacity'],
    },
    {
      key: 'protection',
      label: 'Protecții DC/AC & împământare',
      defaultEnabled: true,
      stageCodes: ['electric'],
      fieldKeys: ['cableLengthM'],
    },
    {
      key: 'grid_connection',
      label: 'Conectare la rețea',
      defaultEnabled: true,
      stageCodes: ['conectare'],
      fieldKeys: ['gridConnection'],
      requiresQtyKeys: ['gridConnectionUnits'],
    },
    {
      key: 'permits',
      label: 'Autorizații & avize',
      defaultEnabled: false,
      stageCodes: ['proiectare'],
      fieldKeys: ['permitsRequired'],
      requiresQtyKeys: ['permitUnits'],
    },
    {
      key: 'monitoring',
      label: 'Monitorizare & telemetrie',
      defaultEnabled: false,
      stageCodes: ['monitorizare'],
      fieldKeys: ['monitoringRequired'],
      requiresQtyKeys: ['monitoringUnits'],
    },
  ],
  customFields: [
    {
      key: 'panelCount',
      label: 'Număr panouri solare',
      type: 'number',
      unit: 'buc',
      required: true,
      defaultValue: 1,
      validation: { min: 1, max: 100 },
      section: 'General',
    },
    {
      key: 'batteryCapacity',
      label: 'Capacitate acumulator',
      type: 'number',
      unit: 'kWh',
      required: true,
      defaultValue: 0,
      validation: { min: 0 },
      section: 'Stocare',
    },
    {
      key: 'inverterCount',
      label: 'Număr invertoare',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 1,
      validation: { min: 1 },
      helpText: 'Nu se calculează automat din numărul de panouri.',
      section: 'Echipamente',
    },
    {
      key: 'systemPowerKw',
      label: 'Putere instalată (kW)',
      type: 'number',
      required: false,
      defaultValue: 0,
      section: 'General',
    },
    {
      key: 'roofType',
      label: 'Tip acoperiș / amplasare',
      type: 'select',
      options: ['metal', 'tile', 'flat', 'ground'],
      required: false,
      defaultValue: 'metal',
      section: 'Montaj',
    },
    {
      key: 'gridConnection',
      label: 'Tip conectare',
      type: 'select',
      options: ['on_grid', 'off_grid', 'hybrid'],
      required: false,
      defaultValue: 'on_grid',
      section: 'Rețea',
    },
    {
      key: 'cableLengthM',
      label: 'Lungime cablu DC/AC',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      helpText: 'Dacă lipsește, se estimează 2,5 m per panou.',
      section: 'Cablare',
    },
    {
      key: 'structureType',
      label: 'Tip structură',
      type: 'select',
      options: ['roof_mount', 'ground_mount', 'ballasted'],
      required: false,
      defaultValue: 'roof_mount',
      section: 'Montaj',
    },
    {
      key: 'permitsRequired',
      label: 'Autorizații / avize necesare',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Documente',
    },
    {
      key: 'monitoringRequired',
      label: 'Monitorizare online',
      type: 'boolean',
      required: false,
      defaultValue: false,
      section: 'Monitorizare',
    },
  ],
  diagnosticQuestions: [
    { key: 'panelCount', label: 'Număr panouri solare', type: 'number' },
    { key: 'batteryCapacity', label: 'Capacitate acumulator (kWh)', type: 'number' },
    { key: 'roofType', label: 'Tip acoperiș', type: 'select', options: ['metal', 'tile', 'flat', 'ground'] },
    { key: 'gridConnection', label: 'Conectare la rețea', type: 'select', options: ['on_grid', 'off_grid', 'hybrid'] },
  ],
  defaultStages: [
    { code: 'audit', name: 'Audit acoperiș & dimensionare', kind: 'LABOR', defaultLaborHours: 4, durationDays: 1, checklist: ['Inspecție acoperiș', 'Calcul producție'], moduleKey: 'audit' },
    { code: 'proiectare', name: 'Proiect & scheme electrice', kind: 'LABOR', defaultLaborHours: 8, durationDays: 2, checklist: ['Schema unifilară', 'Listă materiale'], moduleKey: 'project' },
    { code: 'suport', name: 'Structură de prindere', kind: 'MIXED', defaultLaborHours: 8, durationDays: 2, checklist: ['Profile aluminiu', 'Etanșare penetrări'], moduleKey: 'mounts' },
    { code: 'panouri', name: 'Montaj panouri fotovoltaice', kind: 'MIXED', defaultLaborHours: 12, durationDays: 2, checklist: ['Fixare panouri', 'Conexiuni DC'], moduleKey: 'panels' },
    { code: 'electric', name: 'Cablare, protecții & împământare', kind: 'MIXED', defaultLaborHours: 8, durationDays: 1, checklist: ['Tablouri DC/AC', 'Împământare'], moduleKey: 'protection' },
    { code: 'invertor_baterii', name: 'Invertor & acumulatori', kind: 'MIXED', defaultLaborHours: 8, durationDays: 1, checklist: ['Montaj invertor', 'Conectare baterii'], moduleKey: 'inverter' },
    { code: 'conectare', name: 'Conectare la rețea', kind: 'LABOR', defaultLaborHours: 4, durationDays: 1, checklist: ['Contor bidirecțional', 'Punere sub tensiune'], moduleKey: 'grid_connection' },
    { code: 'monitorizare', name: 'Monitorizare & telemetrie', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Gateway monitoring', 'Aplicație client'], optional: true, moduleKey: 'monitoring' },
    { code: 'predare', name: 'Predare & instruire client', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Teste funcționare', 'Instruire utilizare'], moduleKey: 'audit' },
  ],
  pricingRules: [
    { stageCode: 'audit', description: 'Audit acoperiș & dimensionare sistem', unit: 'ore', qtyKey: 'auditHours', unitPrice: 280, kind: 'labor', moduleKey: 'audit' },
    { stageCode: 'proiectare', description: 'Proiectare & documentație tehnică', unit: 'ore', qtyKey: 'projectHours', unitPrice: 320, kind: 'labor', moduleKey: 'project' },
    { stageCode: 'proiectare', description: 'Autorizații & avize', unit: 'buc', qtyKey: 'permitUnits', unitPrice: 2500, kind: 'labor', moduleKey: 'permits', enabledWhen: { moduleEnabled: 'permits', anyQtyKeys: ['permitUnits'] } },
    { stageCode: 'suport', description: 'Structură prindere acoperiș (material)', unit: 'buc', qtyKey: 'structureQty', unitPrice: 450, kind: 'material', moduleKey: 'mounts', enabledWhen: { anyQtyKeys: ['structureQty'] } },
    { stageCode: 'suport', description: 'Montaj structură prindere', unit: 'buc', qtyKey: 'structureLaborQty', unitPrice: 120, kind: 'labor', moduleKey: 'mounts', enabledWhen: { anyQtyKeys: ['structureLaborQty'] } },
    { stageCode: 'panouri', description: 'Manoperă montaj panou fotovoltaic', unit: 'buc', qtyKey: 'panelLaborQty', unitPrice: 350, kind: 'labor', moduleKey: 'panels', enabledWhen: { anyQtyKeys: ['panelLaborQty'] } },
    { stageCode: 'electric', description: 'Cablu solar DC/AC (material)', unit: 'm', qtyKey: 'cableLengthM', unitPrice: 18, wastePct: 10, kind: 'material', moduleKey: 'protection', enabledWhen: { anyQtyKeys: ['cableLengthM'] } },
    { stageCode: 'electric', description: 'Tablou protecție DC/AC', unit: 'buc', qtyKey: 'protectionPanelUnits', unitPrice: 1800, kind: 'material', moduleKey: 'protection' },
    { stageCode: 'electric', description: 'Împământare & protecție descărcări', unit: 'buc', qtyKey: 'groundingUnits', unitPrice: 950, kind: 'labor', moduleKey: 'protection' },
    { stageCode: 'invertor_baterii', description: 'Manoperă instalare invertor', unit: 'buc', qtyKey: 'inverterCount', unitPrice: 2200, kind: 'labor', moduleKey: 'inverter', enabledWhen: { anyQtyKeys: ['inverterCount'] } },
    { stageCode: 'invertor_baterii', description: 'Acumulator LiFePO4 (stocare)', unit: 'kWh', qtyKey: 'batteryCapacity', unitPrice: 7500, kind: 'material', moduleKey: 'batteries', enabledWhen: { anyQtyKeys: ['batteryCapacity'] } },
    { stageCode: 'conectare', description: 'Conectare la rețea & contor bidirecțional', unit: 'buc', qtyKey: 'gridConnectionUnits', unitPrice: 3200, kind: 'labor', moduleKey: 'grid_connection', enabledWhen: { anyQtyKeys: ['gridConnectionUnits'] } },
    { stageCode: 'monitorizare', description: 'Sistem monitorizare online', unit: 'buc', qtyKey: 'monitoringUnits', unitPrice: 1800, kind: 'labor', moduleKey: 'monitoring', enabledWhen: { moduleEnabled: 'monitoring', anyQtyKeys: ['monitoringUnits'] } },
    { stageCode: 'predare', description: 'Predare & instruire client', unit: 'buc', qtyKey: 'handoverUnits', unitPrice: 450, kind: 'labor', moduleKey: 'audit' },
  ],
});
