import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

export const pavajBlueprint: EstimateBlueprintConfig = baseConfig({
  wizardSteps: ['object', 'diagnostic', 'stages', 'review'],
  accessDifficultyImpact: { easy: 1.0, medium: 1.1, difficult: 1.2 },
  urgencyImpact: { urgent: 1.15, emergency: 1.3 },
  planPointTypes: [
    { type: 'pavement_area', label: 'Zonă pavaj', color: '#6b7280' },
    { type: 'border', label: 'Bordură limitare', color: '#374151' },
    { type: 'drainage', label: 'Rigolă evacuare apă', color: '#1f2937' },
  ],
  workModules: [
    // ---- Pregătire ----
    {
      key: 'removal',
      label: 'Demontare suprafață veche',
      helpText: 'Spargerea și evacuarea pavajului / betonului existent. Activați pentru refaceri.',
      defaultEnabled: false,
      stageCodes: ['demontare'],
      fieldKeys: ['oldSurfaceRemovalArea'],
      requiresQtyKeys: ['oldSurfaceRemovalArea'],
      section: 'Pregătire',
    },
    {
      key: 'excavation',
      label: 'Săpături & pregătire teren',
      helpText: 'Decopertare la cota stratului suport și nivelarea terenului. Volumul se calculează din suprafață × adâncime.',
      defaultEnabled: true,
      stageCodes: ['sapaturi'],
      fieldKeys: ['pavementArea', 'baseLayerCm'],
      requiresQtyKeys: ['excavationVolumeM3'],
      section: 'Pregătire',
    },
    // ---- Strat suport ----
    {
      key: 'geotextile',
      label: 'Geotextil de separare',
      helpText: 'Folie geotextilă între pământ și balast care împiedică amestecarea straturilor. Recomandat.',
      defaultEnabled: true,
      stageCodes: ['suport'],
      fieldKeys: ['geotextileRequired'],
      requiresQtyKeys: ['geotextileArea'],
      section: 'Strat suport',
    },
    {
      key: 'gravel',
      label: 'Balast / piatră spartă',
      helpText: 'Strat portant compactat. Grosimea crește pentru trafic auto/greu.',
      defaultEnabled: true,
      stageCodes: ['suport'],
      fieldKeys: ['gravelLayerCm', 'vehicleLoad'],
      requiresQtyKeys: ['gravelVolumeM3'],
      section: 'Strat suport',
    },
    {
      key: 'sand',
      label: 'Strat nisip de poză',
      helpText: 'Pat de nisip fin pe care se așază pavelele.',
      defaultEnabled: true,
      stageCodes: ['suport'],
      fieldKeys: ['sandLayerCm'],
      requiresQtyKeys: ['sandVolumeM3'],
      section: 'Strat suport',
    },
    {
      key: 'concrete_base',
      label: 'Pat de beton (trafic greu)',
      helpText: 'Fundație rigidă din beton armat sub pavaj, pentru trafic greu / camioane (alternativă la patul de nisip).',
      defaultEnabled: false,
      stageCodes: ['suport'],
      fieldKeys: ['concreteBaseArea'],
      requiresQtyKeys: ['concreteBaseArea'],
      section: 'Strat suport',
    },
    // ---- Pavaj ----
    {
      key: 'borders',
      label: 'Borduri',
      helpText: 'Borduri de limitare pe pat de beton, pentru fixarea perimetrului pavajului.',
      defaultEnabled: true,
      stageCodes: ['borduri'],
      fieldKeys: ['borderLengthM'],
      requiresQtyKeys: ['borderLengthM'],
      section: 'Pavaj',
    },
    {
      key: 'paving',
      label: 'Montaj pavele',
      helpText: 'Așezarea pavelelor după model. Manopera crește pentru modele decorative și trafic greu.',
      defaultEnabled: true,
      stageCodes: ['montaj'],
      fieldKeys: ['pavementArea', 'patternComplexity', 'vehicleLoad'],
      requiresQtyKeys: ['pavementArea'],
      section: 'Pavaj',
    },
    {
      key: 'steps',
      label: 'Trepte din pavaj',
      helpText: 'Trepte / scări din pavele sau borduri speciale. Se introduce lungimea totală.',
      defaultEnabled: false,
      stageCodes: ['montaj'],
      fieldKeys: ['stepsLengthM'],
      requiresQtyKeys: ['stepsLengthM'],
      section: 'Pavaj',
    },
    // ---- Finalizare ----
    {
      key: 'drainage',
      label: 'Drenaj & rigole',
      helpText: 'Rigole liniare pentru evacuarea apei pluviale. Verificați pantele de scurgere.',
      defaultEnabled: true,
      stageCodes: ['drenaj'],
      fieldKeys: ['drainageRequired'],
      requiresQtyKeys: ['drainageLengthM'],
      section: 'Finalizare',
    },
    {
      key: 'manholes',
      label: 'Reglare cămine / capace',
      helpText: 'Aducerea la cotă a capacelor de canalizare / cămine din zona pavată. Se introduce numărul.',
      defaultEnabled: false,
      stageCodes: ['compactare'],
      fieldKeys: ['manholeCount'],
      requiresQtyKeys: ['manholeCount'],
      section: 'Finalizare',
    },
    {
      key: 'compaction',
      label: 'Compactare & rosturi',
      helpText: 'Umplerea rosturilor cu nisip și compactarea finală cu placă vibratoare.',
      defaultEnabled: true,
      stageCodes: ['compactare'],
      fieldKeys: [],
      requiresQtyKeys: ['compactionArea'],
      section: 'Finalizare',
    },
  ],
  customFields: [
    // ---- General ----
    {
      key: 'pavementArea',
      label: 'Suprafață pavat',
      type: 'number',
      unit: 'm²',
      required: true,
      validation: { min: 1 },
      helpText: 'Suprafața totală de pavat. Determină straturile suport, pavelele și manopera.',
      placeholder: 'ex. 50',
      section: 'General',
    },
    {
      key: 'borderLengthM',
      label: 'Lungime borduri',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      helpText: 'Gol = perimetrul se estimează automat din suprafață (4·√S).',
      placeholder: 'ex. 30',
      section: 'General',
    },
    {
      key: 'vehicleLoad',
      label: 'Sarcină / trafic',
      type: 'select',
      options: ['pedestrian', 'car', 'heavy'],
      required: false,
      defaultValue: 'pedestrian',
      helpText: 'Tipul de trafic — crește automat grosimea suportului și manopera.',
      warningRules: [
        { when: "vehicleLoad === 'car'", message: 'Trafic auto ușor — stratul suport și manopera cresc automat cu +15%.' },
        { when: "vehicleLoad === 'heavy'", message: 'Trafic greu / camioane — stratul suport și manopera cresc automat cu +35%. Recomandat pat de beton.' },
      ],
      section: 'General',
    },
    {
      key: 'drainageRequired',
      label: 'Drenaj / rigole necesare',
      type: 'boolean',
      required: false,
      defaultValue: false,
      helpText: 'Verificați căderile și evacuarea apei pluviale.',
      section: 'General',
    },
    // ---- Avansat ----
    {
      key: 'patternComplexity',
      label: 'Complexitate model',
      type: 'select',
      options: ['simple', 'mixed', 'decorative'],
      required: false,
      defaultValue: 'simple',
      helpText: 'Modelul de pozare — crește manopera de montaj.',
      warningRules: [
        { when: "patternComplexity === 'mixed'", message: 'Model mixt — manopera de montaj crește automat cu +15%.' },
        { when: "patternComplexity === 'decorative'", message: 'Model decorativ / complex — manopera de montaj crește automat cu +30%.' },
      ],
      section: 'Avansat',
    },
    {
      key: 'baseLayerCm',
      label: 'Adâncime săpătură / strat suport (cm)',
      type: 'number',
      required: false,
      defaultValue: 25,
      validation: { min: 10, max: 60 },
      helpText: 'Adâncimea totală de decopertat (balast + nisip + pavele).',
      section: 'Avansat',
    },
    {
      key: 'gravelLayerCm',
      label: 'Strat balast / piatră (cm)',
      type: 'number',
      required: false,
      defaultValue: 15,
      validation: { min: 8, max: 30 },
      helpText: 'Grosimea stratului portant compactat.',
      section: 'Avansat',
    },
    {
      key: 'sandLayerCm',
      label: 'Strat nisip (cm)',
      type: 'number',
      required: false,
      defaultValue: 5,
      validation: { min: 3, max: 15 },
      helpText: 'Grosimea patului de nisip de poză.',
      section: 'Avansat',
    },
    {
      key: 'geotextileRequired',
      label: 'Geotextil de separare',
      type: 'boolean',
      required: false,
      defaultValue: true,
      helpText: 'Recomandat ON — împiedică amestecarea balastului cu pământul.',
      section: 'Avansat',
    },
    {
      key: 'concreteBaseArea',
      label: 'Suprafață pat de beton',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Suprafața cu fundație rigidă din beton (trafic greu). Activați modulul „Pat de beton".',
      section: 'Avansat',
    },
    {
      key: 'stepsLengthM',
      label: 'Lungime trepte',
      type: 'number',
      unit: 'm',
      required: false,
      defaultValue: 0,
      helpText: 'Lungimea totală a treptelor din pavaj.',
      section: 'Avansat',
    },
    {
      key: 'manholeCount',
      label: 'Cămine / capace de reglat',
      type: 'number',
      unit: 'buc',
      required: false,
      defaultValue: 0,
      helpText: 'Numărul de capace de canalizare aduse la cotă în zona pavată.',
      section: 'Avansat',
    },
    {
      key: 'oldSurfaceRemovalArea',
      label: 'Suprafață demontat vechi',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      helpText: 'Suprafața pavajului / betonului existent de demontat.',
      section: 'Avansat',
    },
  ],
  diagnosticQuestions: [],
  defaultStages: [
    { code: 'demontare', name: 'Demontare suprafață veche', kind: 'LABOR', defaultLaborHours: 6, durationDays: 1, checklist: ['Demontare', 'Evacuare deșeuri'], optional: true, moduleKey: 'removal' },
    { code: 'sapaturi', name: 'Decopertare & pregătire teren', kind: 'LABOR', defaultLaborHours: 8, durationDays: 2, checklist: ['Săpătură', 'Nivelare'], moduleKey: 'excavation' },
    { code: 'suport', name: 'Geotextil, balast & nisip', kind: 'MIXED', defaultLaborHours: 10, durationDays: 2, checklist: ['Geotextil', 'Balast compactat', 'Nisip fin'], moduleKey: 'gravel' },
    { code: 'borduri', name: 'Montaj borduri', kind: 'MIXED', defaultLaborHours: 6, durationDays: 1, checklist: ['Pat beton', 'Borduri'], moduleKey: 'borders' },
    { code: 'drenaj', name: 'Drenaj & rigole', kind: 'MIXED', defaultLaborHours: 4, durationDays: 1, checklist: ['Rigole', 'Căderi verificate'], optional: true, moduleKey: 'drainage' },
    { code: 'montaj', name: 'Montaj pavele', kind: 'MIXED', defaultLaborHours: 16, durationDays: 3, checklist: ['Așezare model', 'Tăieri'], moduleKey: 'paving' },
    { code: 'compactare', name: 'Rosturi & compactare finală', kind: 'LABOR', defaultLaborHours: 4, durationDays: 1, checklist: ['Umplere rosturi', 'Compactare vibrator'], moduleKey: 'compaction' },
    { code: 'predare', name: 'Predare & verificare căderi', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Verificare pante', 'Predare'], moduleKey: 'compaction' },
  ],
  pricingRules: [
    { stageCode: 'demontare', description: 'Demontare suprafață veche', unit: 'm²', qtyKey: 'oldSurfaceRemovalArea', unitPrice: 55, kind: 'labor', moduleKey: 'removal', enabledWhen: { anyQtyKeys: ['oldSurfaceRemovalArea'] } },
    { stageCode: 'sapaturi', description: 'Săpătură & pregătire teren', unit: 'm³', qtyKey: 'excavationVolumeM3', unitPrice: 85, kind: 'labor', moduleKey: 'excavation', enabledWhen: { anyQtyKeys: ['excavationVolumeM3'] } },
    { stageCode: 'suport', description: 'Geotextil separare', unit: 'm²', qtyKey: 'geotextileArea', unitPrice: 12, wastePct: 5, kind: 'material', moduleKey: 'geotextile', enabledWhen: { anyQtyKeys: ['geotextileArea'] } },
    { stageCode: 'suport', description: 'Balast / piatră spartă', unit: 'm³', qtyKey: 'gravelVolumeM3', unitPrice: 320, wastePct: 5, kind: 'material', moduleKey: 'gravel', enabledWhen: { anyQtyKeys: ['gravelVolumeM3'] } },
    { stageCode: 'suport', description: 'Strat nisip fin', unit: 'm³', qtyKey: 'sandVolumeM3', unitPrice: 180, kind: 'material', moduleKey: 'sand', enabledWhen: { anyQtyKeys: ['sandVolumeM3'] } },
    { stageCode: 'suport', description: 'Pat de beton armat (material)', unit: 'm²', qtyKey: 'concreteBaseArea', unitPrice: 220, wastePct: 5, kind: 'material', moduleKey: 'concrete_base', enabledWhen: { moduleEnabled: 'concrete_base', anyQtyKeys: ['concreteBaseArea'] } },
    { stageCode: 'suport', description: 'Lucrări turnare pat beton', unit: 'm²', qtyKey: 'concreteBaseArea', unitPrice: 75, kind: 'labor', moduleKey: 'concrete_base', enabledWhen: { moduleEnabled: 'concrete_base', anyQtyKeys: ['concreteBaseArea'] } },
    { stageCode: 'borduri', description: 'Bordură (material)', unit: 'm', qtyKey: 'borderLengthM', unitPrice: 40, kind: 'material', moduleKey: 'borders', enabledWhen: { anyQtyKeys: ['borderLengthM'] } },
    { stageCode: 'borduri', description: 'Lucrări montaj borduri', unit: 'm', qtyKey: 'borderLengthM', unitPrice: 65, kind: 'labor', moduleKey: 'borders', enabledWhen: { anyQtyKeys: ['borderLengthM'] } },
    { stageCode: 'drenaj', description: 'Rigole / drenaj linear', unit: 'm', qtyKey: 'drainageLengthM', unitPrice: 120, kind: 'labor', moduleKey: 'drainage', enabledWhen: { moduleEnabled: 'drainage', anyQtyKeys: ['drainageLengthM'] } },
    { stageCode: 'montaj', description: 'Pavele vibropresate (material)', unit: 'm²', qtyKey: 'pavementArea', unitPrice: 195, wastePct: 8, kind: 'material', moduleKey: 'paving', enabledWhen: { anyQtyKeys: ['pavementArea'] } },
    { stageCode: 'montaj', description: 'Lucrări montaj pavele', unit: 'm²', qtyKey: 'pavementLaborQty', unitPrice: 110, kind: 'labor', moduleKey: 'paving', enabledWhen: { anyQtyKeys: ['pavementLaborQty'] } },
    { stageCode: 'montaj', description: 'Trepte pavaj (material)', unit: 'm', qtyKey: 'stepsLengthM', unitPrice: 280, wastePct: 8, kind: 'material', moduleKey: 'steps', enabledWhen: { moduleEnabled: 'steps', anyQtyKeys: ['stepsLengthM'] } },
    { stageCode: 'montaj', description: 'Lucrări montaj trepte', unit: 'm', qtyKey: 'stepsLengthM', unitPrice: 160, kind: 'labor', moduleKey: 'steps', enabledWhen: { moduleEnabled: 'steps', anyQtyKeys: ['stepsLengthM'] } },
    { stageCode: 'compactare', description: 'Umplere rosturi & compactare', unit: 'm²', qtyKey: 'compactionArea', unitPrice: 35, kind: 'labor', moduleKey: 'compaction', enabledWhen: { anyQtyKeys: ['compactionArea'] } },
    { stageCode: 'compactare', description: 'Reglare cămine / capace la cotă', unit: 'buc', qtyKey: 'manholeCount', unitPrice: 450, kind: 'labor', moduleKey: 'manholes', enabledWhen: { moduleEnabled: 'manholes', anyQtyKeys: ['manholeCount'] } },
    { stageCode: 'predare', description: 'Verificare căderi & predare', unit: 'buc', qtyKey: 'handoverUnits', unitPrice: 350, kind: 'labor', moduleKey: 'compaction' },
  ],
});
