import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

export const pavajBlueprint: EstimateBlueprintConfig = baseConfig({
  planPointTypes: [
    { type: 'pavement_area', label: 'Zonă pavaj', color: '#6b7280' },
    { type: 'border', label: 'Bordură limitare', color: '#374151' },
    { type: 'drainage', label: 'Rigolă evacuare apă', color: '#1f2937' },
  ],
  workModules: [
    {
      key: 'removal',
      label: 'Demontare suprafață veche',
      defaultEnabled: false,
      stageCodes: ['demontare'],
      fieldKeys: ['oldSurfaceRemovalArea'],
      requiresQtyKeys: ['oldSurfaceRemovalArea'],
    },
    {
      key: 'excavation',
      label: 'Săpături & pregătire teren',
      defaultEnabled: true,
      stageCodes: ['sapaturi'],
      fieldKeys: ['pavementArea', 'baseLayerCm'],
      requiresQtyKeys: ['excavationVolumeM3'],
    },
    {
      key: 'geotextile',
      label: 'Geotextil',
      defaultEnabled: true,
      stageCodes: ['suport'],
      fieldKeys: ['geotextileRequired'],
      requiresQtyKeys: ['geotextileArea'],
    },
    {
      key: 'gravel',
      label: 'Balast / piatră spartă',
      defaultEnabled: true,
      stageCodes: ['suport'],
      fieldKeys: ['gravelLayerCm', 'vehicleLoad'],
      requiresQtyKeys: ['gravelVolumeM3'],
    },
    {
      key: 'sand',
      label: 'Strat nisip',
      defaultEnabled: true,
      stageCodes: ['suport'],
      fieldKeys: ['sandLayerCm'],
      requiresQtyKeys: ['sandVolumeM3'],
    },
    {
      key: 'borders',
      label: 'Borduri',
      defaultEnabled: true,
      stageCodes: ['borduri'],
      fieldKeys: ['borderLengthM'],
      requiresQtyKeys: ['borderLengthM'],
    },
    {
      key: 'drainage',
      label: 'Drenaj & rigole',
      defaultEnabled: true,
      stageCodes: ['drenaj'],
      fieldKeys: ['drainageRequired'],
      requiresQtyKeys: ['drainageLengthM'],
    },
    {
      key: 'paving',
      label: 'Montaj pavele',
      defaultEnabled: true,
      stageCodes: ['montaj'],
      fieldKeys: ['pavementArea', 'patternComplexity', 'vehicleLoad', 'paverThicknessCm'],
      requiresQtyKeys: ['pavementArea'],
    },
    {
      key: 'compaction',
      label: 'Compactare & rosturi',
      defaultEnabled: true,
      stageCodes: ['compactare'],
      fieldKeys: [],
      requiresQtyKeys: ['compactionArea'],
    },
  ],
  customFields: [
    {
      key: 'pavementArea',
      label: 'Suprafață pavat',
      type: 'number',
      unit: 'm²',
      required: true,
      validation: { min: 1 },
      section: 'General',
    },
    {
      key: 'borderLengthM',
      label: 'Lungime borduri',
      type: 'number',
      unit: 'm',
      required: true,
      validation: { min: 1 },
      helpText: 'Dacă lipsește, se estimează perimetrul din suprafață.',
      section: 'General',
    },
    {
      key: 'baseLayerCm',
      label: 'Adâncime săpătură / strat suport',
      type: 'number',
      required: false,
      defaultValue: 25,
      validation: { min: 10, max: 60 },
      section: 'Suport',
    },
    {
      key: 'paverThicknessCm',
      label: 'Grosime pavele',
      type: 'number',
      required: false,
      defaultValue: 6,
      validation: { min: 4, max: 12 },
      section: 'Pavaj',
    },
    {
      key: 'drainageRequired',
      label: 'Drenaj / rigole necesare',
      type: 'boolean',
      required: true,
      defaultValue: false,
      helpText: 'Verificați căderile și evacuarea apei — întrebare obligatorie.',
      section: 'Drenaj',
    },
    {
      key: 'oldSurfaceRemovalArea',
      label: 'Suprafață demontat vechi',
      type: 'number',
      unit: 'm²',
      required: false,
      defaultValue: 0,
      section: 'Demontare',
    },
    {
      key: 'geotextileRequired',
      label: 'Geotextil de separare',
      type: 'boolean',
      required: false,
      defaultValue: true,
      section: 'Suport',
    },
    {
      key: 'sandLayerCm',
      label: 'Strat nisip',
      type: 'number',
      required: false,
      defaultValue: 5,
      validation: { min: 3, max: 15 },
      section: 'Suport',
    },
    {
      key: 'gravelLayerCm',
      label: 'Strat balast / piatră',
      type: 'number',
      required: false,
      defaultValue: 15,
      validation: { min: 8, max: 30 },
      section: 'Suport',
    },
    {
      key: 'patternComplexity',
      label: 'Complexitate model',
      type: 'select',
      options: ['simple', 'mixed', 'decorative'],
      required: false,
      defaultValue: 'simple',
      section: 'Pavaj',
    },
    {
      key: 'vehicleLoad',
      label: 'Sarcină / trafic',
      type: 'select',
      options: ['pedestrian', 'car', 'heavy'],
      required: false,
      defaultValue: 'pedestrian',
      section: 'Pavaj',
    },
  ],
  diagnosticQuestions: [
    { key: 'pavementArea', label: 'Suprafață pavat (m²)', type: 'number' },
    { key: 'borderLengthM', label: 'Lungime borduri (m)', type: 'number' },
    { key: 'drainageRequired', label: 'Este necesar drenaj / rigole?', type: 'boolean' },
    { key: 'vehicleLoad', label: 'Trafic prevăzut', type: 'select', options: ['pedestrian', 'car', 'heavy'] },
  ],
  defaultStages: [
    { code: 'demontare', name: 'Demontare suprafață veche', kind: 'LABOR', defaultLaborHours: 6, durationDays: 1, checklist: ['Demontare', 'Evacuare deșeuri'], optional: true, moduleKey: 'removal' },
    { code: 'sapaturi', name: 'Decopertare & pregătire teren', kind: 'LABOR', defaultLaborHours: 8, durationDays: 2, checklist: ['Săpătură', 'Nivelare'], moduleKey: 'excavation' },
    { code: 'suport', name: 'Geotextil, balast & nisip', kind: 'MIXED', defaultLaborHours: 10, durationDays: 2, checklist: ['Geotextil', 'Balast compactat', 'Nisip fin'], moduleKey: 'gravel' },
    { code: 'borduri', name: 'Montaj borduri', kind: 'MIXED', defaultLaborHours: 6, durationDays: 1, checklist: ['Pat beton', 'Borduri'], moduleKey: 'borders' },
    { code: 'drenaj', name: 'Drenaj & rigole', kind: 'MIXED', defaultLaborHours: 4, durationDays: 1, checklist: ['Rigole', 'Căderi verificate'], optional: true, moduleKey: 'drainage' },
    { code: 'montaj', name: 'Montaj pavele', kind: 'MIXED', defaultLaborHours: 16, durationDays: 3, checklist: ['Așezare model', 'Tăieri'], moduleKey: 'paving' },
    { code: 'compactare', name: 'Rosturi & compactare finală', kind: 'LABOR', defaultLaborHours: 4, durationDays: 1, checklist: ['Umplere rosturi', 'Compactare vibrator'], moduleKey: 'compaction' },
    { code: 'predare', name: 'Predare & verificare căderi', kind: 'LABOR', defaultLaborHours: 2, durationDays: 1, checklist: ['Verificare pante', 'Predare'], moduleKey: 'compaction' },
  ],
  pricingRules: [
    { stageCode: 'demontare', description: 'Demontare suprafață veche', unit: 'm²', qtyKey: 'oldSurfaceRemovalArea', unitPrice: 55, kind: 'labor', moduleKey: 'removal', enabledWhen: { anyQtyKeys: ['oldSurfaceRemovalArea'] } },
    { stageCode: 'sapaturi', description: 'Săpătură & pregătire teren', unit: 'm³', qtyKey: 'excavationVolumeM3', unitPrice: 85, kind: 'labor', moduleKey: 'excavation', enabledWhen: { anyQtyKeys: ['excavationVolumeM3'] } },
    { stageCode: 'suport', description: 'Geotextil separare', unit: 'm²', qtyKey: 'geotextileArea', unitPrice: 12, wastePct: 5, kind: 'material', moduleKey: 'geotextile', enabledWhen: { anyQtyKeys: ['geotextileArea'] } },
    { stageCode: 'suport', description: 'Balast / piatră spartă', unit: 'm³', qtyKey: 'gravelVolumeM3', unitPrice: 320, wastePct: 5, kind: 'material', moduleKey: 'gravel', enabledWhen: { anyQtyKeys: ['gravelVolumeM3'] } },
    { stageCode: 'suport', description: 'Strat nisip fin', unit: 'm³', qtyKey: 'sandVolumeM3', unitPrice: 180, kind: 'material', moduleKey: 'sand', enabledWhen: { anyQtyKeys: ['sandVolumeM3'] } },
    { stageCode: 'borduri', description: 'Bordură (material)', unit: 'm', qtyKey: 'borderLengthM', unitPrice: 40, kind: 'material', moduleKey: 'borders', enabledWhen: { anyQtyKeys: ['borderLengthM'] } },
    { stageCode: 'borduri', description: 'Manoperă montaj borduri', unit: 'm', qtyKey: 'borderLengthM', unitPrice: 65, kind: 'labor', moduleKey: 'borders', enabledWhen: { anyQtyKeys: ['borderLengthM'] } },
    { stageCode: 'drenaj', description: 'Rigole / drenaj linear', unit: 'm', qtyKey: 'drainageLengthM', unitPrice: 120, kind: 'labor', moduleKey: 'drainage', enabledWhen: { moduleEnabled: 'drainage', anyQtyKeys: ['drainageLengthM'] } },
    { stageCode: 'montaj', description: 'Pavele vibropresate (material)', unit: 'm²', qtyKey: 'pavementArea', unitPrice: 195, wastePct: 8, kind: 'material', moduleKey: 'paving', enabledWhen: { anyQtyKeys: ['pavementArea'] } },
    { stageCode: 'montaj', description: 'Manoperă montaj pavele', unit: 'm²', qtyKey: 'pavementLaborQty', unitPrice: 110, kind: 'labor', moduleKey: 'paving', enabledWhen: { anyQtyKeys: ['pavementLaborQty'] } },
    { stageCode: 'compactare', description: 'Umplere rosturi & compactare', unit: 'm²', qtyKey: 'compactionArea', unitPrice: 35, kind: 'labor', moduleKey: 'compaction', enabledWhen: { anyQtyKeys: ['compactionArea'] } },
    { stageCode: 'predare', description: 'Verificare căderi & predare', unit: 'buc', qtyKey: 'handoverUnits', unitPrice: 350, kind: 'labor', moduleKey: 'compaction' },
  ],
});
