import type { EstimateBlueprintConfig } from '../../estimate-blueprint-config.types';
import { baseConfig } from '../base';

export const santehnikaBlueprint: EstimateBlueprintConfig = baseConfig({
    wizardSteps: ['object', 'diagnostic', 'stages', 'review'],
    accessDifficultyImpact: { easy: 1.0, medium: 1.1, difficult: 1.25 },
    urgencyImpact: { urgent: 1.25, emergency: 1.8 },
    planPointTypes: [
      { type: 'water', label: 'Apă rece/caldă', color: '#3b82f6' },
      { type: 'drain', label: 'Canalizare', color: '#64748b' },
      { type: 'mixer', label: 'Baterie / mixer', color: '#06b6d4' },
      { type: 'toilet', label: 'WC', color: '#8b5cf6' },
    ],
    workModules: [
      {
        key: 'water_pipes',
        label: 'Trasee apă',
        defaultEnabled: true,
        stageCodes: ['demontare', 'trasee', 'tevi'],
        fieldKeys: ['replacePipes', 'pipeMaterial', 'wallChasingM'],
      },
      {
        key: 'drain',
        label: 'Canalizare',
        defaultEnabled: true,
        stageCodes: ['tevi'],
        fieldKeys: ['drainReplacement', 'kitchenPoints', 'bathroomPoints'],
      },
      {
        key: 'sanitary_objects',
        label: 'Obiecte sanitare',
        defaultEnabled: true,
        stageCodes: ['obiecte'],
        fieldKeys: ['bathroomCount'],
      },
      {
        key: 'boiler',
        label: 'Boiler',
        defaultEnabled: false,
        stageCodes: ['obiecte'],
        fieldKeys: ['waterHeater'],
        requiresQtyKeys: ['waterHeaterCount'],
      },
      {
        key: 'wall_chasing',
        label: 'Ștrobire pereți',
        defaultEnabled: false,
        stageCodes: ['trasee'],
        fieldKeys: ['wallChasingM'],
        requiresQtyKeys: ['wallChasingM'],
      },
      {
        key: 'testing',
        label: 'Testare & predare',
        defaultEnabled: true,
        stageCodes: ['test'],
        fieldKeys: [],
      },
    ],
    customFields: [
      {
        key: 'replacePipes',
        label: 'Înlocuire completă țevi?',
        type: 'boolean',
        required: false,
        defaultValue: false,
        section: 'Trasee apă',
      },
      {
        key: 'filterSystem',
        label: 'Montaj sistem filtrare apă / Фильтр воды',
        type: 'boolean',
        required: false,
        defaultValue: false,
        section: 'Obiecte sanitare',
      },
      {
        key: 'riserReplacement',
        label: 'Înlocuire coloană principală / Замена стояка',
        type: 'boolean',
        required: false,
        defaultValue: false,
        section: 'Canalizare',
      },
      {
        key: 'bathroomCount',
        label: 'Număr băi',
        type: 'number',
        unit: 'buc',
        required: true,
        defaultValue: 1,
        validation: { min: 1, max: 10 },
        helpText: 'Include toate grupurile sanitare cu duș/cadă sau cadă.',
        section: 'Obiecte sanitare',
      },
      {
        key: 'kitchenPoints',
        label: 'Puncte apă bucătărie',
        type: 'number',
        unit: 'buc',
        required: false,
        defaultValue: 0,
        section: 'Canalizare',
      },
      {
        key: 'bathroomPoints',
        label: 'Puncte apă baie',
        type: 'number',
        unit: 'buc',
        required: false,
        defaultValue: 0,
        section: 'Canalizare',
      },
      {
        key: 'waterHeater',
        label: 'Montaj boiler',
        type: 'boolean',
        required: false,
        defaultValue: false,
        section: 'Boiler',
      },
      {
        key: 'pipeMaterial',
        label: 'Material țevi',
        type: 'select',
        options: ['ppr', 'pex', 'multistrat', 'cupru'],
        required: false,
        section: 'Trasee apă',
      },
      {
        key: 'drainReplacement',
        label: 'Înlocuire canalizare',
        type: 'boolean',
        required: false,
        defaultValue: false,
        section: 'Canalizare',
      },
      {
        key: 'wallChasingM',
        label: 'Ștrobire pereți',
        type: 'number',
        unit: 'm',
        required: false,
        defaultValue: 0,
        section: 'Ștrobire',
      },
    ],
    diagnosticQuestions: [
      { key: 'bathroomCount', label: 'Număr băi', type: 'number' },
    ],
    defaultStages: [
      { code: 'demontare', name: 'Demontare', kind: 'LABOR', defaultLaborHours: 3, durationDays: 1, checklist: ['Oprire apă', 'Protejare finisaje'], optional: true, moduleKey: 'water_pipes' },
      { code: 'trasee', name: 'Ștrobire & pregătire trasee', kind: 'LABOR', defaultLaborHours: 4, durationDays: 1, checklist: ['Traseu marcat', 'Praf colectat'], optional: true, moduleKey: 'wall_chasing' },
      { code: 'tevi', name: 'Montaj țevi', kind: 'MIXED', defaultLaborHours: 6, durationDays: 2, checklist: ['Traseu aprobat', 'Presiune test'], moduleKey: 'water_pipes' },
      { code: 'obiecte', name: 'Montaj obiecte sanitare', kind: 'MIXED', defaultLaborHours: 4, durationDays: 1, checklist: ['Etanșare', 'Scurgere OK'], moduleKey: 'sanitary_objects' },
      { code: 'test', name: 'Test & predare', kind: 'LABOR', defaultLaborHours: 1, durationDays: 1, checklist: ['Fără scurgeri', 'Client informat'], moduleKey: 'testing' },
    ],
    pricingRules: [
      { stageCode: 'demontare', description: 'Demontare instalații vechi', unit: 'ore', qtyKey: 'demolitionHours', unitPrice: 180, kind: 'labor', moduleKey: 'water_pipes' },
      { stageCode: 'trasee', description: 'Ștrobire pereți', unit: 'm', qtyKey: 'wallChasingM', unitPrice: 120, kind: 'labor', moduleKey: 'wall_chasing', enabledWhen: { moduleEnabled: 'wall_chasing', anyQtyKeys: ['wallChasingM'] } },
      { stageCode: 'tevi', description: 'Țeavă PPR + fitinguri', unit: 'm', qtyKey: 'pipeLengthM', unitPrice: 95, wastePct: 8, kind: 'material', moduleKey: 'water_pipes' },
      { stageCode: 'tevi', description: 'Manoperă montaj țevi apă', unit: 'm', qtyKey: 'pipeLengthMLabor', unitPrice: 65, kind: 'labor', moduleKey: 'water_pipes' },
      { stageCode: 'tevi', description: 'Fitinguri apă', unit: 'buc', qtyKey: 'fittingsQty', unitPrice: 35, wastePct: 3, kind: 'material', moduleKey: 'water_pipes' },
      { stageCode: 'tevi', description: 'Țeavă canalizare', unit: 'm', qtyKey: 'drainLengthM', unitPrice: 85, wastePct: 5, kind: 'material', moduleKey: 'drain' },
      { stageCode: 'tevi', description: 'Manoperă canalizare', unit: 'm', qtyKey: 'drainLengthMLabor', unitPrice: 55, kind: 'labor', moduleKey: 'drain' },
      { stageCode: 'obiecte', description: 'Punct apă / canalizare', unit: 'buc', qtyKey: 'plumbingPointsLabor', unitPrice: 450, kind: 'labor', moduleKey: 'sanitary_objects' },
      { stageCode: 'obiecte', description: 'Montaj boiler', unit: 'buc', qtyKey: 'waterHeaterCount', unitPrice: 850, kind: 'labor', moduleKey: 'boiler', enabledWhen: { moduleEnabled: 'boiler', anyQtyKeys: ['waterHeaterCount'] } },
      { stageCode: 'test', description: 'Test presiune & predare', unit: 'buc', qtyKey: 'plumbingPoints', unitPrice: 120, kind: 'labor', moduleKey: 'testing' },
    ],
});
